### ISSUE TITLE
Revisar as justificativas para a obrigatoriedade do elemento *counts*

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#104]
Até então a justificativa para esse elemento é o de não perder metadados no cenário onde o SciELO PS é um formato derivado, ou realizar verificações após as transformações para outros formatos. 

A questão é que não estou convencido de que a justificativa seja forte o suficiente para que seja traduzida em um regra. Devemos avaliar.

**Comment by RPostalli** [comment]
Lembro-me que em alguma reunião você mesmo levantou a importância de termos estes metadados contabilizados, pois poderíamos gerar relatórios mencionando a quantidade de figuras por exemplo por artigo / fascículo / revista. E por algum motivo isso era importante.

**Comment by gustavofonseca** [comment]
A justificativa está na descrição do ticket.. Eu achava que seria importante, mas não foi até agora e estou duvidando que passe a ser rs.

**Comment by RPostalli** [comment]
Será que o lance que tenho ouvido falar de entrarmos no Fig Share onde os dados de figuras, tabelas e etc não terão relação com os dados de <counts>.

**Comment by lpanebr** [comment]
Não sei o quanto isto é relevante ou útil para vcs mas deixarei aqui:

 - boxed text podem usar figs ou tables
 - equações podem usar figs
 - tables podem ser usadas para "alinhar" equações
 - tables podem ser usadas para criar fig-pannels
 - fig pannels podem ser feitos como uma só imagem
 - equações pode ser do tipo display ou inline (picadas no meio de parágrafos)
 - equações inline pode ser usadas como display...
 - pages um dia estarão deprecadas para revistas que adotarem o HTML como a _version of record_ 
 - etc

Para prestadores que usam pessoas para classificar e taggear manualmente direto no XML pode ser muito difícil documentar os detalhes.

Para prestadores que usam sistemas mais automáticos de geração buscando se alinhar com o estado da arte é também muito complicado configurar e revisar para toda$ a$ poSSibilidades.

um abraço!

**Comment by robertatakenaka** [comment]
Luciano, um comentário a parte da discussão. Quando se refere a contagem
dos elementos se considera seu conteúdo/semântica e não sua forma de
representação, ou seja, estando a tabela representada como imagem, conta
como tabela e não como figura.
Assim sendo,

   - equações podem usar figs (contam como equações e não figuras)
   - tables podem ser usadas para "alinhar" equações (não contam)
   - tables podem ser usadas para criar fig-pannels (não contam)



Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-08-27 9:40 GMT-03:00 Luciano <notifications@github.com>:

**Comment by lpanebr** [comment]
Ah sim Roberta..  eu sei sim que o que conta para o counts (rs) é a
semântica do elemento...

Na verdade meu comment tem dois lados:
1. lado mais colaborativo: avaliação dos usos vs semântica
2. lado mais combativo: avaliação de necessidade vs custo

*1. lado mais colaborativo: avaliação dos usos vs semântica*

Sabemos que tem muito autor e editor etc que usa elementos de forma
semanticamente errada. O caso mais comum é usar Tabelas quando deveria usar
um Quadro ou uma simples Bullet list e vice-versa. Sei que pouco importa
para scielo se o autor/editor se preocupa com o uso semanticamente correto
dos elementos. Então penso que, justamente por isso, talvez não seja tão
relevante tabular esses counts para talvez usar uma métrica no futuro...

*2. lado mais combativo: avaliação de necessidade vs custo*

Como prestador, gostaria que ao pesar e avaliar a inclusão de uma nova
regra levassem em conta o quanto ela é:

 - "crucial para as métricas scielo"
 - vs "complexa, custosa ou propensa a erros para os prestadores"

(observe o uso errado de bullets) rs

obrigado!

-- 

Atenciosamente,

*Luciano Panepucci*

Cofundador e Diretor de Tecnologia

+55 (16) 3307-2068 | +55 (16) 991 728 681 | skype: lpanebr


*Editora Cubo*

soluções para o universo acadêmico

Rua Marechal Deodoro 2709

13560-201 São Carlos - SP

www.editoracubo.com.br

**Comment by gustavofonseca** [comment]
@robertatakenaka e @lpanebr, vocês podem apontar aonde conta essa definição de que utilizamos o critério por conteúdo/semântica e não por forma de representação? Eu sempre pensei que fosse o contrário, inclusive o stylechecker conta com base no elemento. 

Mais uma evidência de que essa regra não agrega nada e deve ser removida. =]

**Comment by lpanebr** [comment]
Não está definido em lugar algum que eu saiba.. No PMC o counts não é
exigido.

Em qui, 27 de ago de 2015 13:44, Gustavo Fonseca <notifications@github.com>
escreveu:

> @robertatakenaka <https://github.com/robertatakenaka> e @lpanebr
> <https://github.com/lpanebr>, vocês podem apontar aonde conta essa
> definição de que utilizamos o critério por conteúdo/semântica e não por
> forma de representação? Eu sempre pensei que fosse o contrário, inclusive o
> stylechecker conta com base no elemento.
>
> Mais uma evidência de que essa regra não agrega nada e deve ser removida.
> =]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/scielo_publishing_schema/issues/104#issuecomment-135488592>
> .
>
-- 

Atenciosamente,

*Luciano Panepucci*

Cofundador e Diretor de Tecnologia

+55 (16) 3307-2068 | +55 (16) 991 728 681 | skype: lpanebr


*Editora Cubo*

soluções para o universo acadêmico

Rua Marechal Deodoro 2709

13560-201 São Carlos - SP

www.editoracubo.com.br

**Comment by gustavofonseca** [comment]
Implementado no packtools no commit https://github.com/scieloorg/packtools/commit/c7bfcfbdc22dba8d46986d9a49336f0d2f5f0ea7
