### ISSUE TITLE
Avaliar tags para identificaçao de Ensaio Clínico

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#111]
Verificar a possibilidade de utilizar o elemento ```<ext-link>``` para identificar ensaios clínicos. Ex.:

Número de registro clínico: NCT00981734

Número de registro clínico:```<ext-link ext-link-type="ClinicalTrial" xlink:href="https://clinicaltrials.gov/ct2/show/NCT00981734">NCT00981734</ext-link>```

Ou utilizando o elemento ```<uri>```:

Número de registro clínico:```<uri xlink:href="https://clinicaltrials.gov/ct2/show/NCT00981734">NCT00981734</uri>```

**Comment by lpanebr** [comment]
Oi gente,

Sabemos que JATS permite marcar a mesma informação de diversas formas válidas. Como fazer marcar determinada informação é uma questão muito importante e que continuará recorrente e por bastante tempo.

Para atacar essa questão em 2014 foi criado[1] um grupo de trabalho chamado JATS4R (JATS for Resuse)[2].

Acredito que Scielo poderia/deveria ser uma das _Organisations currently endorsing JATS4R_.

Nota: por tratar-se de um grupo de trabalho o processo é lento e por isso toda colaboração é bem-vinda. Atualmente o grupo tem recomendações em duas áreas:

- permissions and licenses, and 
- math formulas.


Sobre identificaçao de Ensaio Clínico
---

Hoje justamente uma dúvida e sugestão apareceram na JATS-List[3] acerca de qual seria uma forma recomendada para **registrar ensaios clínicos**! A maneira sugerida foi incluida [como exemplo](https://github.com/JATS4R/elements/blob/master/clinical-trials.md) no GitHub da JATS4R[4].

[1] http://www.ncbi.nlm.nih.gov/books/NBK279901/
[2] http://jats4r.org/
[3] http://www.mulberrytech.com/JATS/JATS-List/
[4] https://github.com/JATS4R/

**Comment by scielo** [comment]
Ola Luciano,

Nós acompanhamos sim este grupo, mas sem um vínculo formal. Atualmente
nossos esforços estão direcionados ao estabelecimento de regras e boas
práticas para o SciELO PS.

As indicações do JATS4R quando pertinentes e devidamente avaliadas pelo
SciELO podem ser incorporadas também como regra para o SciELO PS.

Abraços,

*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

2015-08-21 8:45 GMT-03:00 Luciano <notifications@github.com>:

**Comment by lpanebr** [comment]
Obrigado pelo feedback Fábio!

Entendo. Tem que ter foco mesmo. Sei que a equipe de vcs não grande e sempre me admiro com o quanto estão evoluindo! 
PArabéns a todos!

**Comment by gustavofonseca** [comment]
=]

**Comment by robertatakenaka** [comment]
@leticiaquino : 
SciELO vai aceitar os dois? Eu sugiro adotar apenas 1.

O XC já está considerando 
``uri[@content-type='clinicial-trial']``
 (tudo minúsculo com hífen).
Faltaria considerar ext-link.

Note que é importante haver uma **identificação** tanto no ext-link como no uri de que se refere a um clinical trial. E sugiro que o valor se "clinical-trial" e não "ClinicalTrial", pois que já estava sendo adotado clinical-trail.

``<ext-link ext-link-type="clinical-trial" xlink:href="https://clinicaltrials.gov/ct2/show/NCT00981734">NCT00981734</ext-link>``


E se for usar ``<uri>``, usar o atributo content-type='clinical-trial'

``<uri content-type="clinical-trial" xlink:href="https://clinicaltrials.gov/ct2/show/NCT00981734">NCT00981734</uri>``

**Comment by leticiaquino** [comment]
@robertatakenaka decidimos utilizar o ```<ext-link>```. Podemos aceitar o valor dessa forma, como "clinical-trial".

**Comment by lpanebr** [comment]
Fiquei na dúvida se é `clinical-trial` como sugerido pela @robertatakenaka e @leticiaquino ou `ClinicalTrial` como está aparecendo [na documentação](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.4-branch/faq.html?highlight=ensaio)?

![image](https://cloud.githubusercontent.com/assets/129185/15230026/237ee144-186a-11e6-8b68-7b40db8a81cc.png)

**Comment by leticiaquino** [comment]
@lpanebr considerar "ClinicalTrial" como consta na documentação.

**Comment by lpanebr** [comment]
obrigado!
