### ISSUE TITLE
Artigos que iniciam na mesma página

### ISSUE THREAD

**Issue by renatogaldino** [scieloorg/scielo_publishing_schema#114]
Baseado na dúvida do e-mail abaixo onde os artigos se inciam na mesma página, encontrei essa possível solução na [JATS] (http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-qap0.html) inserindo um atributo ***seq*** em `<fpage>`:

`<fpage seq="a">`

```
Bom dia.
Estou fazendo um xml de um artigo onde os pdfs iniciam-se na mesma página. O arquivo 1 e o 2 estão juntos, conforme pdf anexo. Só que na hora do programa gerar o xml, ele ‘queima’ o anterior, e acaba ficando errado. Como proceder neste caso?
 
Aguardo,
```

**Comment by gustavofonseca** [comment]
Essa regra também deve ser aplicada em **elocation-id**?

**Comment by leticiaquino** [comment]
Olá @gustavofonseca !
a meu ver não deveria, mas há a possibilidade de incluir esse atributo @seq em ```<elocation-id>```. Veja:
http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-4su0.html

**Comment by renatogaldino** [comment]
Como é um identificador para casos que não haja número de páginas impressas
tradicionais, provavelmente não seja necessário.

Atenciosamente,



*_ _ _ _Renato Galdino*

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FAP - UNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-08-11 8:06 GMT-03:00 Letícia Aquino <notifications@github.com>:

**Comment by gustavofonseca** [comment]
Encontrei um post que dá uma idéia boa sobre *elocation-id*: http://pogue.blogs.nytimes.com/2011/02/08/page-numbers-for-kindle-books-an-imperfect-solution/?_r=0

**Comment by renatogaldino** [comment]
@gustavofonseca os testes foram realizados para esse atributo? Ele funcionará sem problemas?

**Comment by gustavofonseca** [comment]
Até onde verifiquei, vai funcionar sim.
