### ISSUE TITLE
Incluir o Package Maker como Ferramenta de Validação.

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#122]
Verificar a possibilidade de incluir o Package Maker como ferramenta de apoio em:

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.2-branch/index.html#ferramentas-de-apoio

**Comment by gustavofonseca** [comment]
@leticiaquino existem instruções de instalação e uso do package maker?

**Comment by robertatakenaka** [comment]
Nos próximos dias terminarei a documentacao no docs.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-08-05 14:47 GMT-03:00 Gustavo Fonseca <notifications@github.com>:

**Comment by gustavofonseca** [comment]
Ok. Vou aguardar a documentação para realizar esse ticket.
