### ISSUE TITLE
Retirar valores "announcement" e "abstract" para @article-type 

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#124]
Foi solicitado que os valores "announcement" e "abstract" sejam retirados da tabela de tipos de article, pois esses valores não são utilizados.

**Comment by gustavofonseca** [comment]
Esses valores não estão sendo utilizados até o momento ou o SciELO não suporta a indexação desses tipos de documento? 

No caso específico do tipo "abstract", como serão representados documentos como por exemplo: http://www.scielosp.org/scielo.php?script=sci_abstract&pid=S0042-96862015000600369&lng=en&nrm=iso&tlng=en  ?

**Comment by leticiaquino** [comment]
@gustavofonseca  note que esse arquivo que você apresenta é um artigo original que possui resumo em mais que um idioma. 
http://www.scielosp.org/scielo.php?script=sci_arttext&pid=S0042-96862015000600369&lng=en&nrm=iso&tlng=en

De acordo com os novos critérios, os documentos que não serão indexados no SciELO são os que seguem abaixo:
anúncio, calendário, chamadas, livros recebidos, notícia, obituário, reimpressão, relatório de reunião, resumo, revisão de produto, tese, tradução.

Ver página 9 dos novos critérios

**Comment by gustavofonseca** [comment]
@leticiaquino ok eu quase nunca sou feliz em te mostrar exemplos... 
Mas independentemente dos novos critérios de SciELO BR, esses tipos de documento ocorrem ou já ocorreram em alguma coleção?

**Comment by leticiaquino** [comment]
@gustavofonseca confirmei com a equipe e para SciELO BR já ocorreu, mas os arquivos que foram processados como "abstract" em SciELO BR estão com o tipo incorreto. Isso porque o processo de marcação com o Markup é um pouco automático e às vezes os responsáveis pela marcação não se atentam para o tipo de documento.

Fui informada de que pode ser que a Rede SciELO publica resumos e anúncios, mas isso não é uma certeza.
