### ISSUE TITLE
Ausência de resumo no idioma do texto original.

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#127]
Exemplo: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0100-40422015000100030&lng=en&nrm=iso&tlng=pt

**Comment by gustavofonseca** [comment]
@leticiaquino a ausência do resumo no idioma original será permitida para todos os tipos de documento que atualmente obrigam a ocorrência de resumo (somente `research-article` e `review-article`)?

**Comment by leticiaquino** [comment]
@gustavofonseca sim, pois recebemos arquivos de alguns periódicos do tipo "research-article" sem resumo no idioma principal.

**Comment by gustavofonseca** [comment]
@leticiaquino blz :+1:

**Comment by leticiaquino** [comment]
@gustavofonseca blza  :ok_hand:  :trollface:

**Comment by gustavofonseca** [comment]
Resolvido no packtools, commit https://github.com/scieloorg/packtools/commit/c72d4987377bf11a6a9fb97461dcb408ed1127d6
