### ISSUE TITLE
Identificar *funding-source* e *award-id* também na fonte 

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#13]
O XML a seguir ilustra a proposta:

```
...
<front>
  ...
  <article-meta>
    ...
    <funding-group>
      <award-group>
        <funding-source rid="01">CNPq</funding-source>
        <award-id rid="02">16362 2010/2011</award-id>
      </award-group>
    </funding-group>
    ...    
  </article-meta>
  ...
</front>
...
<back>
  <ack>
    <title>ACKNOWLEDGEMENTS</title>
    <p>The authors acknowledge the support of <funding-source id="01">CNPq</funding-source>-PIBIC for Scientific Initiation scholarship (Process number <award-id id="02">16362 2010/2011</award-id>) granted to carry out this research.</p>
  </ack>
</back>
...
```

A justificativa é de simplificar o processo de validação destes metadados, podendo ser implementado em Schematron e distribuído junto com as demais validações. (acho que preciso melhorar essa justificativa... )

**Comment by gustavofonseca** [comment]
@lpanebr, se não me engano essa mudança foi proposta por você, estou certo?

**Comment by lpanebr** [comment]
Está certo @gustavofonseca

**Comment by gustavofonseca** [comment]
@lpanebr, sem querer abusar da sua memória.. mas você consegue detalhar alguns casos de uso para essa identificação mais completa?

**Comment by lpanebr** [comment]
Sem problema Gustavo.

Minha motivação tinha um motivo principal era egoísta: meu filtro de export nativamente gera o XML com essas referências cruzadas conforme exemplo abaixo.
Entretanto [nesta discussão](https://github.com/scieloorg/packtools/issues/16) eu imaginei que essa marcação poderia ter um caso de uso facilitando a facilitar a validação eliminando as regras de regex.. (mas já não tenho certeza disso)

Outro caso de uso mais direto seria a  possibilidade de criar links no HTML entre as informações e suas citações..  (também não vejo muita vantagem nisso..). O importante na minha opinião é ter as informações de fomento marcadas para "fundref crawlers" e visivelmente e facilmente acessíveis para humanos. 

Outra coisa é que o modelo do nosso export nativo (abaixo) é diferente do descrito neste issue. **Diferenças:**
 1. Aqui no issue a ID é definida na citação e não no `funding-group`. Acredito que o ideal seria definir os IDs  no `funding-group`, pois assim caso necessário podemos citar funding-sources e award-ids mais de uma vez, assim como ocorre com as refs.
 2. Aqui no issue o ID é definido tanto para o funding-source quanto para o award-id. No modelo abaixo o ID fica somente na `<funding-source>`.
3. A SPS somente permite só 1 `<funding-group>`. Permitir múltiplos elementos como na [JATS](http://jats.nlm.nih.gov/publishing/tag-library/1.1d3/element/funding-group.html) possibilitaria uma marcação mais rica onde pode-se identificar o pesquisador (`<principal-award-recipient>`) que recebeu o grant.

```xml
...
<front>
  ...
  <article-meta>
    ...
                    <funding-group>
                        <award-group>
                            <funding-source id="sp1">FAPESP</funding-source>
                            <award-id rid="sp1">01-1231/2013</award-id>
                        </award-group>
                    </funding-group>
                    <funding-group>
                        <award-group>
                            <funding-source id="sp2">CNPq</funding-source>
                            <award-id rid="sp2">2013.1299/1</award-id>
                        </award-group>
                    </funding-group>
    ...    
  </article-meta>
  ...
</front>
...
<back>
  <ack>
    <title>ACKNOWLEDGEMENTS</title>
    <p>The authors acknowledge the support 
    of <funding-source rid="sp2">CNPq</funding-source>-PIBIC for Scientific Initiation 
    scholarship (Process number <award-id rid="sp1">2013.1299/1</award-id>) 
    granted to carry out this research, and  <funding-source rid="sp2">FAPESP</funding-source> grant <award-id rid="sp1">01-1231/2013</award-id>.</p>
  </ack>
</back>
...
```

**Comment by gustavofonseca** [comment]
Rejeitamos essa solicitação por hora, mas podemos rever sua relevância caso apareçam novas demandas semelhantes.
