### ISSUE TITLE
<volume> e <issue> não devem ser obrigatórios

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#132]
Verificar a possibilidade de alterar a informação:
"Ocorre: 1 vez"
para
"Ocorre: "0 ou 1 vez"

para ```<volume>``` e ```<issue>```.

**Comment by robertatakenaka** [comment]
Acrescentar que pelo menos um deles é obrigatório. E incluir caso de aop se já não está considerado (que é forçar ambos mas com valor 0)

**Comment by gustavofonseca** [comment]
@robertatakenaka essas restrições são motivadas por detalhe de implementação dos programas tipo conversor, processamento etc?

**Comment by robertatakenaka** [comment]
@gustavofonseca : no momento o que limita isso é a questão de que no processamento há necessidade de ou volume ou número existir (ou suplemento). O formato da scilista é:

acronimo v1n1s1

variações aceitáveis:
acronimo n1
acronimo v1
acronimo s0

Uma convenção adotada é que <volume>00</volume> e <issue>00</issue> = aop.

No entanto, pode ser que a ausência de volume e issue pode ser interpretado pelo XML Converter (XC) que é um aop.

Neste caso, o converter gera na base como "label" do issue: <ano 4 digitos>nahead.

acronimo 2015nahead

**Comment by gustavofonseca** [comment]
@robertatakenaka, podemos seguir com a alteração partindo do princípio que o XML Converter passará a interpretar a ausência dos elementos de maneira equivalente ao valor **00**?

**Comment by robertatakenaka** [comment]
@gustavofonseca : sem problemas, se houver ajusto rapidamente.

**Comment by gustavofonseca** [comment]
:ok_hand:

**Comment by gustavofonseca** [comment]
Implementei as mudança no packtools (https://github.com/scieloorg/packtools/commit/bbd62b2351641465749ade6f055d1982f040907b). 

Além de trocar a cardinalidade na referência dos elementos *volume* e *issue*, devemos rever regras de AOP tb, certo @leticiaquino e @renatogaldino?

**Comment by gustavofonseca** [comment]
Quando digo "rever regras de AOP", quero dizer rever instruções para AOP.. :rewind:

**Comment by leticiaquino** [comment]
Ok @gustavofonseca :v:

**Comment by renatogaldino** [comment]
:ok_hand:
