### ISSUE TITLE
Excluir Nota da tag <license>

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#149]
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset.html#license

Existe uma nota em ```<license>``` que informa:

NOTA: O texto de ```<license-p>``` deve ser inserido na **língua principal do artigo**.

Esta nota deve ser retirada já que a língua escolhida não interfere atualmente em nada. Tanto site quando homologs,  não apresentam o texto da licença. Só apresenta a imagem que ao clicar vai para o link da licença.

Exemplo Atual:

![g](https://cloud.githubusercontent.com/assets/6084959/9227057/f9094ed6-40e7-11e5-8259-8b3a9ba93b46.jpg)

**Comment by gustavofonseca** [comment]
Como não? A função do texto de *license-p* é de comunicar os termos de uso para os interessados em utilizar o conteúdo. O idioma interfere totalmente na comunicação.... imagina só um artigo com o conteúdo em português e o texto de license-p em russo... 

Veja outro ticket sobre esse assunto: #71

**Comment by leticiaquino** [comment]
@gustavofonseca @RPostalli Acredito que o comentário acima e o do ticket #71 respondem este tciket, podemos então considerar como inválido?

**Comment by leticiaquino** [comment]
Sim. Inválido.
