### ISSUE TITLE
inlcuir nota explicativa sobre a não obrigatoriedade dos elementos <volume> e <issue>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#167]
Informar que os elementos ```<volume>```e ```<issue>``` não são obrigatórios quando não existirem.

**Comment by gustavofonseca** [comment]
isso na versão 1.3?

**Comment by gustavofonseca** [comment]
Outra pergunta: o texto "Zero ou uma vez em <front>" não está surtindo efeito?

**Comment by robertatakenaka** [comment]
@gustavofonseca : faltou uma melhor descrição. Comentei com @leticiaquino que o texto de 
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.3-branch/whatsnew-1.3.html

pode dar a entender que o usuário pode ou não optar por informar abstract e volume/número.

**Comment by robertatakenaka** [comment]
@gustavofonseca e @leticiaquino : talvez neste texto fosse interessante além do link para o ticket colocar o link para o elemento na SPS 1.3

**Comment by gustavofonseca** [comment]
@robertatakenaka mas é isso mesmo, não? Digo, semanticamente ``<volume>00</volume>`` (quantidade arbitrária de zeros) é igual à ausência do elemento.

**Comment by leticiaquino** [comment]
@gustavofonseca Acredito que a questão é que mesmo que o dado exista, o responsável pela produção do xml pode não inserir uma vez que informamos que não é obrigatório.

**Comment by gustavofonseca** [comment]
hm entendi

**Comment by leticiaquino** [comment]
Resolvido.
