### ISSUE TITLE
[est. 5 horas] Documentação da identificação do ID ORCID dos contribuidores

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#174]
* Ver documentação do elemento *contrib-id*: http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-t680.html
* Sobre ORCID: http://orcid.org/about/what-is-orcid

**Comment by leticiaquino** [comment]
Fazer um levantamento dos valores possíveis.

**Comment by robertatakenaka** [comment]
http://cshl.libguides.com/content.php?pid=240865&sid=1988232

**Comment by jfunez** [comment]
Acho que este link (doc oficial) pode ajudar na validação do dado no packtools por exemplo:
- **Structure of the ORCID Identifier** http://support.orcid.org/knowledgebase/articles/116780-structure-of-the-orcid-identifier

Também deixo aqui exemplos que eu fiz no manager para validação (do formato, e do checksum) segundo as explicações do link anterior:
* em python (validação de um formulário):
  * https://github.com/scieloorg/scielo-manager/blob/beta/scielomanager/editorialmanager/forms.py#L34-L61
* em JS (validação no frontend): 
  * https://github.com/scieloorg/scielo-manager/blob/beta/scielomanager/editorialmanager/templates/includes/add_member_form_loaded_callbacks.js#L140-L153
  * https://github.com/scieloorg/scielo-manager/blob/beta/scielomanager/editorialmanager/templates/includes/add_member_form_loaded_callbacks.js#L59-L84

**Comment by RPostalli** [comment]
Esboço para SPS

```<contrib-id>```

Aparece em
```<contrib>```

Atributos obrigatórios
contrib-id-type

Ocorre
Zero ou mais vezes

Representa um identificador digital atribuido á um pesquisador. 


O atributo @contrib-type pode possuir os valores: 

(tabela)
Valor
orcid (orcid-id?)

Descrição
identificador digital da ORCID organization.

Valor
researchid (research-id)

Descrição 
identificador digital da Thomson Reuters.

Valor
scopus ? scopus-id ? (Scopus Author Identifier)

Descrição
identificador digital da Scopus.

Exemplo:
```<contrib-group>
<contrib>
<contrib-id contrib-id-type="orcid">http://orcid.org/1792-3336-9172-961X</contrib-id>
<name>
<surname>Souza</surname>
<given-names>Maria</given-names>
</name>
</contrib>
</contrib-group>```
