### ISSUE TITLE
Números DOI distintos para cada idioma do documento

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#175]
Esse ticket é motivado por outro aberto no tracker do projeto scielo-manager[1]. A frase "Assigning separate DOIs to article translations is recommended but optional."[2] abre a possibilidade e inclusive recomenda o registro de um número DOI para cada versão/tradução do documento. 

[1]https://github.com/scieloorg/scielo-manager/issues/562
[2]http://help.crossref.org/translations

**Comment by javani** [comment]
@gustavofonseca do ponto da especificação não há problemas em ter DOIs distintos para o artigo principal e para o sub-article. Fiz a validação no Style Checker e no XPM e não houve problemas. Acho que esse ponto tem que ser tratado no processamento. Aguardo seus comentários

**Comment by gustavofonseca** [comment]
Sim, de fato a especificação permite e sua intuição também está correta sobre o ponto de tratamento.
