### ISSUE TITLE
[est. 2 horas] Sugestão de como tratar *counts/@page-count*, *fpage* e *lpage* diferentes em <sub-article>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#179]
Para tratar paginações diferentes em ```<sub-article>``` avaliar a possibilidade de aceitar o elemento ```<counts>``` em ```<front-stub>``` do ```<sub-article>```.

**Comment by leticiaquino** [comment]
Adicionar paginação.

**Comment by robertatakenaka** [comment]
Foi feita uma reunião sobre qual seria o impacto ao adotar fpage, lpage e elocation-id para sub-article e a conclusão foi não adotar pois não haveria como, no momento, implantar quaisquer funcionadades, serviços ou afins. Assim, no momento, a conclusão seria remover da documentação os elementos fpage, lpage e elocation-id, valendo apenas o que está identicado dentro de article-meta.

**Comment by gustavofonseca** [comment]
@leticiaquino e @robertatakenaka, vou reverter as modificações realizadas.
