### ISSUE TITLE
Criar seção de processos internos no SPS

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#183]
Avaliar a possibilidade de criar uma seção na documentação SPS para documentar os processos internos, tais como:
- uso do `<pub-date pub-type="collection">`
- `<article-id pub-id-type="publisher-id" specific-use="previous-pid">`
- processo de atualização do Delorean
- Envio de bases (ISIS, PubMed etc)
- Afiliação com mais que uma instituição

etc.
Obs.: a equipe SciELO também faz uso do guia.

**Comment by gustavofonseca** [comment]
Em reunião -- 04/01/2015 -- decidimos separar esse ticket em diversos outros de acordo com seu uso, que pode ser **operacional** ou **markup**.

**Comment by RPostalli** [comment]
Esboço de documentação, somente para tags de uso interno SciELO.

TAGS DE USO INTERNO

```<article-id pub-id-type="publisher-id" specific-use="previous-pid">```
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Tag utilizada exclusivamente para ahead of print que passa a ser incluído em um fascículo. Na tag deve constar o PID do documento, disponível na página web SciELO.

Exemplo:

```<article-id pub-id-type="publisher-id" specific-use="previous-pid">S0100-879X2015005054396</article-id>```

Nota: O PID deve ser obtido através da url do artigo
Exemplo: http://www.scielo.br/scielo.php?script=sci_arttext&nrm=iso&lng=pt&tlng=pt&pid=**S0100-879X2015005054396**

```<pub-date pub-type="collection">```
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Tag utilizada exclusivamente para ahead of print que passa a ser incluído em um fascículo. Na tag deve constar a data de publicação do fascículo.

Exemplo:

```<pub-date pub-type="epub">
				<day>29</day>
				<month>09</month>
				<year>2015</year>
			</pub-date>
			<pub-date pub-type="collection">
				<month>12</month>
				<year>2015</year>
			</pub-date>```



```<article-id pub-id-type="other">```
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Regra geral para criação do número de other é considerar obrigatoriamente, 5 números arábicos.

Nota: É proibido o uso de letras, pontuações ou outros caracteres.

Tag utlizada em 3 situações:

- Fascículo
Quando não há menção de número de páginas em um documento, ou o mesmo possui número de páginas diferente de números arábicos (como número romano), ou ainda, quando dois documentos possuem exatamente o mesmo número de página inicial e final. Para estes documentos em um fascículo deve-se inserir a tag ```<article-id pub-id-type="other">``` contendo a posição do documento dentro do sumário.

Exemplo para Editoril sendo o primeiro documento de um sumário de fascículo contendo número de página romano.

```<article-id pub-id-type="other">00001</article-id>```

- Ahead of Print
É um tipo de documento onde ainda não existe uma informação de número de páginas real, é considerado valor 00 ou 01. Deve-se inserir a tag ```<article-id pub-id-type="other">```, considerando a seguinte regra para compor o número other: 3 primeiros dígitos do lote +  2 últimos dígitos representará a quantidade de artigos no lote.

Exemplo lote bjmbr 0715 possui 5 artigos, o primeiro terá o other:

```<article-id pub-id-type="other">07101</article-id>```

- Rolling Pass

Em revistas que utilizam a modalidade publicação continuada, a tag ```<article-id pub-id-type="other">``` é utilizada para organizar as seções, sendo a regra utilizar uma centena para cada seção, exemplo: 100 para editorial, 200 para artigo original.

Exemplo do quarto documento publicado do tipo Artigo Original

```<article-id pub-id-type="other">00204</article-id>```

**Comment by leticiaquino** [comment]
Está fora do escopo da documentação do SciELO PS.
O ticket será mantido aberto porque é importante e não podemos esquecer.
