### ISSUE TITLE
Considerar diferentes protocolos para @xlink:href em <ext-link>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#185]
Verificar a possibilidade de documentar e validar @xlink:href para diferentes protocolos além do HTTP.
Atualmente links são identificados da seguinte forma:

```<ext-link ext-link-type="uri" xlink:href="http://www.scielo.org">```

Há casos em que o documento apresenta protocolo FTP, HTTP, HTTPS, SMTP entretanto não é possível a validação do arquivo.

Verificar a possibilidade de acrescentar um valor diferente em @ext-link-type. Exemplo:
```<ext-link ext-link-type="ftp" xlink:href="">```

**Comment by leticiaquino** [comment]
Exemplo de link:
 ftp://ftp.ibge.gov.br/

Considerar lista de valores para @ext-link-type da JATS:
http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-bnu0.html

**Comment by gustavofonseca** [comment]
Acredito que podemos continuar considerando apenas o valor *uri* válido para o atributo ``@ext-link-type``, pois as strings *ftp://ftp.ibge.gov.br/* e *http://www.scielo.org* são URIs válidas. Ver[1].

As únicas restrições que imagino são:
* O scheme deve ser explícito
* O scheme *file://* deve ser inválido.

[1] https://en.wikipedia.org/wiki/Uniform_Resource_Identifier
