### ISSUE TITLE
Reavaliar a lista de licenças permitidas no SPS

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#198]
Avaliar a possibilidade de considerar todos os tipo de licença Creative Commons em `<license>`:
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.3-branch/tagset.html#license

Apenas SciELO Brasil restringe o uso da licença CC.

**Comment by gustavofonseca** [comment]
Na realidade a idéia de considerar todos os tipos de licença CC deve ser aplicada apenas em */article/front/article-meta/permissions/license*, pois refere-se à licença de uso do documento. O uso do elemento *license* em outros locais não deve apresentar restrições quando à licença.

**Comment by leticiaquino** [comment]
Relacionado ao #373

**Comment by leticiaquino** [comment]
Após discussão em grupo, foi decidido flexibilizar essa questão. Portanto a lista de licenças Creative Commons deve ser retirada do tópico "Regras Específicas para SciELO Brasil".
