### ISSUE TITLE
Falta inserir um tipo article-type na tabela em <article> (mencionado já em <product>)

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#200]
em ```<product>``` mencionamos o seguinte:
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset.html#product>

 "É importante salientar que esta tag só deverá ser utilizada quando ```<article>``` possuir o atributo @article-type="book-review" ou @article-type="product-review"."

Mas em ```<article>``` o valor @article-type="product-review", não consta.
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset.html#article

É necessário acrescenta-lo

**Comment by RPostalli** [comment]
Pode ser também o caso de excluir o valor @article-type="product-review" da tag ```<product>``` ao invés de acrescentar o tipo em ```<article>```.

**Comment by RPostalli** [comment]
Critérios SciELO Brasil tópico 5.2.2. Tipos de documentos diz:

Os seguintes tipos de documentos não serão indexados, publicados e 
incluídos nas métricas de desempenho do SciELO: anúncio, calendário, chamadas, livros 
recebidos, notícia, obituário, reimpressão, relatório de reunião, resumo, **revisão de produto**, 
tese, tradução. O Anexo 1 descreve cada um destes tipos de documento.

**Comment by alexxpsilva** [comment]
Por favor reabrir ticket.
O Style Checker está validando o article-type com atributo de book-review quando o mesmo não possui a tag de product.

**Comment by gustavofonseca** [comment]
@alexxpsilva você está certo na afirmação sobre o stylechecker. Entretanto, trata-se de um bug na biblioteca https://github.com/scieloorg/packtools e reabrir esse ticket não faz sentido. 

Registrei o bug https://github.com/scieloorg/packtools/issues/71

**Comment by alexxpsilva** [comment]
Ok @gustavofonseca , obrigado.
