### ISSUE TITLE
Definição de missão e visão para o produto SciELO PS

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#203]
[descrever melhor aqui!]

**Comment by leticiaquino** [comment]
Abaixo um documento da SEBRAE sobre Missão e Visão:

[Orientação_Planejamento estratégico.pdf](https://github.com/scieloorg/scielo_publishing_schema/files/87248/Orientacao_Planejamento.estrategico.pdf)

**Comment by gustavofonseca** [comment]
Ver documento https://docs.google.com/a/scielo.org/document/d/1XTQujcbvFf3dRiGkTmAWZ-fmyULtwtd5zGLgrIDh0Y4/edit?usp=sharing (apenas usuários ``@scielo.org``)
