### ISSUE TITLE
Criar seções para apresentação de Tabelas e Figuras requeridas por SciELO

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#206]
Avaliar a possibilidade de criar dois itens: para falar apenas sobre tabelas requeridas por SciELO e outro sobre figuras.

**Tabelas:** 
Apresentar modelo de tabelas aceitáveis.. desde o label/caption, a tabela em si até a nota de rodapé.
Baseado no modelo da Plos: http://journals.plos.org/plosone/s/tables:

**Figuras**
Apresentar o modelo de label/caption, tamanho requerido, formato etc.
Com base no modelo Plos: http://journals.plos.org/plosone/s/figures

**Comment by javani** [comment]
Não é competência do SciELO PS
