### ISSUE TITLE
Voltar a discutir sobre o ISSN-L

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#209]
Voltar a discutir sobre o ISSN-L.
Atualmente nem na title existe campo para a inserção deste ISSN e também não temos documentado.
Seria importante aceitarmos este tipo de ISSN?

http://www.issn.org/understanding-the-issn/assignment-rules/the-issn-l-for-publications-on-multiple-media/

**Comment by gustavofonseca** [comment]
Qual a tua motiva��o para colocar esse t�pico em pauta, tendo em conta
os pontos que vc apontou sobre sua utilidade pr�tica no momento?

-- 
-Gustavo

**Comment by RPostalli** [comment]
Na verdade é só uma pergunta para discutirmos nas reuniões do grupo SPS agra que temos um esquema diário de encontro. Uma revista nova que entrou na coleção possui este tipo de ISSN e notei que não temos campo adequado para ele e também não temos este tipo documentado.
A motivação é só a discussão para ou fechamento do ticket ou a criação de um ticket que possa acrescentar algo na documentação.

**Comment by leticiaquino** [comment]
Observação:
Há revistas que apresentam 2 ISSN-L. Vejam:
![issn-l](https://cloud.githubusercontent.com/assets/4397365/17373252/bc562608-597d-11e6-9a89-3f796b334d10.jpg)

**Comment by gustavofonseca** [comment]
https://g.co/kgs/cTsGTH

-Gustavo


Em Qua 3 ago. 2016, às 15:19, Letícia Aquino escreveu:

**Comment by leticiaquino** [comment]
:joy:

**Comment by francine-curivil** [comment]
Na reunião do GT SciELO PS de 07/07/2017, sexta-feira, nós (Aline, Carolina, Francine, Gustavo, Renata, Roberta e Solange) decidimos que o campo para o cadastro do ISSN-L será criado na Title e que a equipe de produção cadastrará o ISSN-L dos periódicos da Coleção SciELO Brasil.

**Comment by RPostalli** [comment]
Demanda do Abel (maio de 2019)

**Comment by RPostalli** [comment]
Este campo não será acrescentado na title nem na title manager segundo informações da Roberta (10/09/2019), pois geraria um trabalho substancial nestas ferramentas antigas. Desta forma é inviável permitir o dado no XML uma vez que não terá como ser validado, já que não constaria no registro da revista no SciELO.
Ticket inválido
