### ISSUE TITLE
Criar seção sobre Publicação Contínua

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#211]
Verificar a possibilidade de criar seção sobre **Publicação Contínua**, assim como foi feito para Ahead Of Print e Errata:

![sections](https://cloud.githubusercontent.com/assets/4397365/12580073/bf8214b8-c413-11e5-8555-c9dd42ed547b.jpg)

**Comment by RPostalli** [comment]
Adendo: Acrescentar na Nomeação que o ISSN utilizado preferencialmente deve ser o ONLINE. [Sugestão Roberta]
