### ISSUE TITLE
Documentar exemplo de <ext-link> dentro de <mixed-citation>

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#212]
Para discussão se devemos ou não documentar esta "regra", segue emails trocados com o prestador de serviço GN1.
-------------------------------------
João Paulo Rui por  scielo.org 
Anexos25 de jan (Há 1 dia)

para Conversão, Javani, francine.curiv., GN1 
Prezados, bom dia.

Verificamos alguns problemas relacionados aos links das referências. Alguns fascículos processados durante o ano de 2016 estão apresentando uma falha no link da referência, eles não estão fazendo um hyperlink para que seja possível acessar ao site que o link se refere. Selecionei alguns exemplos de revistas enviadas pela GN1 neste começo de ano:

ABC-v105n1
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0066-782X2015002500560&lng=en&nrm=iso&tlng=en
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0066-782X2015002500573&lng=en&nrm=iso&tlng=en
 
REBEn-v68n6
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0034-71672015000601042&lng=en&nrm=iso&tlng=pt
 
RBSMI-v15n4
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1519-38292015000400451&lng=en&nrm=iso&tlng=pt
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1519-38292015000400425&lng=en&nrm=iso&tlng=en
 
RBTI-v27n4
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0103-507X2015000400369&lng=en&nrm=iso&tlng=pt

Notamos que nossos XMLs estão marcados de maneira correta, contendo a tag ext-link dentro de element-citation conforme é orientado pelo SciELO Publishing Schema, no entanto o MarkUp gera o XML com essa informação de ext-link dentro de mixed-citation. Diante disto, acreditamos que o XML esperado pelo sistema de vocês, esteja esperando o ext-link dentro de mixed-citation­ e não dentro de element-citation como estamos marcando.
 
Poderiam por gentileza verificar se o que está ocasionando este problema é a maneira como estamos marcando o XML?
Atenciosamente,
------------------------------------------------------------
Prezado João Bom dia.

Para que o link seja feito a marcação de <ext-link> deve estar em mixed-citation. O site SciELO apresenta na interface somente os dados dentro de mixed-citation.

Pode ocorrer de um link só marcado em element-citation apareça no site, mas neste caso existe um "match" automático, se o link estiver exatamente igual o site reconhece e gera o link, no entanto este "match" vai além do que vemos a olha nu. Se houver um espaço, uma quebra de linha esse reconhecimento automático não é realizado.

O markup gera este link automático dentro de mixed. 

Eu já falei com nossa equipe de TI e vamos acrescentar esta validação no Package Maker.

Fico a disposição
------------------------------------------------------------
https://github.com/scieloorg/PC-Programs/issues/1976
------------------------------------------------------------
João Paulo Rui
Anexos09:40 (Há 2 horas)

para mim, Conversão, Javani, Francine, GN1 
Prezada Renata, bom dia! Tudo bom?

Quando vimos estes links no site sem estarem com o hyperlink, imaginamos que o sistema de vocês esperava mesmo eles dentro de <mixed-citation>. Neste caso irei repassar essa informação ao restante da equipe GN1 e iremos começar a enviar nossos arquivos com o link marcado dentro de <mixed-citation> para alinhar nossos trabalhos com os de vocês.

No entanto, poderia nos ajudar com mais algumas dúvidas?

Nós buscamos realizar nossos trabalhos conforme o SciELO Publishing Schema 1.3, e nele não há no exemplo de referências que contenham URL a informação de <ext-link> dentro de <mixed-citation>, dessa forma, vocês poderiam por gentileza atualizar os exemplos para referências que tenham URL? Pois, apesar do Markup gerar essa informação, ao buscar adequar nosso arquivos com o máximo de compatibilidade possível com o SPS 1.3, quando não encontramos uma informação (ainda que gerada pelo Markup), acabamos por retirá-la.

E, adotando a marcação de <ext-link> dentro de <mixed-citation>, devemos continuar marcando <ext-link> dentro de <element-citation> também?

Agradeço a atenção e estamos à disposição.
Atenciosamente,
------------------------------------------------------------

Renata Postali de Almeida <renata.almeida@scielo.org>
10:06 (Há 1 hora)

para João, Conversão, Javani, Francine, GN1 
Prezado João, bom dia, tudo bom.

Eu entendo seu questionamento, e com certeza levarei a documentação desta regra ao grupo SPS para avaliar sua documentação efetiva.

No entanto todos os prestadores de serviço quando avaliarem a falta de alguma regra na documentação ou até mesmo erros de documentação, podem e devem abrir um ticket no GitHub para ajudar a melhorar este serviço.

O SPS não tem foco em apresentação de interface, apesar de ser sim algo importante, este não é o foco principal.

Informo também que é essencial que se faça a pesquisa na JATS uma vez que o SPS representa uma especialização da mesma. Note que na JATS é permitido o uso de <ext-link> e outros tangueamentos de formatação em <mixed-citation>.

De qualquer forma em caso de dúvidas, sempre entrem contato para que possamos alinhar nossos esforços em melhorar a marcação XML. Lembrem-se que este tipo de dúvida devem sem enviados para a lista de discussão aberta XML no email: <scielo-xml@googlegroups.com>

Referente a sua pergunta, sim, o uso de <ext-link> quando aparecer uma url na referência deve ser marcado tanto em <mixed-citation> quanto em <element-citation>.

Fico a disposição
------------------------------------------------------------

João Paulo Rui
Anexos10:25 (Há 1 hora)

para mim, Conversão, Javani, Francine, GN1 
Prezada Renata,

Muito obrigado pelos esclarecimentos e seguiremos conforme a sua orientação.

Estamos à disposição.
Atenciosamente,

**Comment by gustavofonseca** [comment]
Pelo que pude entender trata-se de um problema de responsabilidades. A responsabilidade do elemento ``mixed-citation`` é de identificar a referência bibliográfica na sua forma literal, que comporá a seção de referências no documento nos diversos formato de impressão. Sua responsabilidade não envolve “abrigar metadados”, mas somente “a referência conforme deve constar impressa nos documentos”. O conteúdo de ``ext-link`` é para metadado, que no caso é de responsabilidade do elemento ``element-citation``. Se no site final as URLs devem ser convertidas em hyperlink, por que é assim que a internet é, trata-se de uma responsabilidade e funcionalidade do site e apenas do site.

**Comment by RPostalli** [comment]
Mas pelo que entendi da Roberta que conversei hoje de manhã o site não faz isso e sempre usamos a identificação de <ext-link> dentro de mixed (inclusive o markup faz isso automático) o que é permitido pela JATS. Ou seja o mixed não serve só para "identificar a referência bibliográfica na sua forma literal" até por que outros prestadores que não usam o markup estão inserindo o <ext-link> em mixed.
Então talvez tenhamos um problema na forma que documentamos o mixed, talvez devêssemos mencionar que formatação (itálico e negrito) e link só irão aparecer no site se marcados em mixed.

**Comment by gustavofonseca** [comment]
> On 26 de jan de 2016, at 14:12, Renata Postalli <notifications@github.com> wrote:
> 
> Mas pelo que entendi da Roberta que conversei hoje de manhã o site não faz isso
Ok, isso é um fato.

> e sempre usamos a identificação de dentro de mixed (inclusive o markup faz isso automático)
Esse é o ponto que considero errado e estou apresentando a justificativa da minha posição na mensagem anterior.

> o que é permitido pela JATS.
Ser permitido pela JATS é uma condição necessária mas não suficiente para definições da SciELO PS.

> Ou seja o mixed não serve só para "identificar a referência bibliográfica na sua forma literal”
O argumento que vc está usando para concluir isso é que “é permitido pela JATS”? Se sim, vale meu último comentário. A definição de que ``mixed-citation`` identifica a forma literal e ``element-citation`` os metadados foi feita pela nossa equipe.. inclusive é motivo de diversas críticas.

> até por que outros prestadores que não usam o markup estão inserindo o em mixed.
Esse fato não torna correta a prática.

**Comment by RPostalli** [comment]
Gustavo não estou entendendo bem seu ponto de vista. Vamos deixar para discutir a questão no grupo quando estivermos na rodada de análise de ticket.

**Comment by lpanebr** [comment]
Gostaria de sugerir que a SPS abandonasse o uso do `element-citation` em favor do `mixed-citation`.

Acredito que essa estratégia, embora represente um "custo" inicial para a implementação técnica (markup, xpm e stylechecker) e respectivas documentações, resolveria esse "embate" sobre usar o elemento do mixed ou do element... Criaria outras questões mas ainda assim, acredito que seria melhor para o futuro da SPS.

**Os principais motivos para minha sugestão são que:**
 1. `mixed-citation` não perde nenhuma informação em relação ao `element-citation`, muito pelo contrário.
 2. não existe motivo técnico para exigir o `element-citation`.
 3. tanto para humanos quanto para _softwares_ é mais fácil gerar `mixed-citation` pois é um "export" direto da referência editada.

**Comment by robertatakenaka** [comment]
@lpanebr : primeiramente, obrigada pelas suas colocações, mas seria melhor que fosse um post na lista de discussão ou um novo ticket, podendo ser relacionado com este, para que fique neste ticket somente discussões diretamente relacionadas ao ticket. 

Referente ao seu comentário, posso adiantar que já avaliamos esta sugestão anteriormente, mas não temos como atendê-la no momento. Sobre o seu motivo 2, historicamente, sim, há/havia um motivo técnico para o uso do element-citation + mixed-citation. Inicialmente começamos com periódicos vancouver que na nossa marcação havia a estrutura totalmente correspondente a mixed-citation e element-citation (sem pontuações), assim foi adotado como padrão para os demais. Mas, de novo, isso é outra discussão, que poderíamos retomar na lista ou em um ticket. Conto com sua compreensão.

**Comment by lpanebr** [comment]
Obrigado @robertatakenaka fiz uma sugestão menos intrusiva no ticket #219

**Comment by leticiaquino** [comment]
Essa questão será resolvida pela Web, não pelo XML. 
https://github.com/scieloorg/Web/issues/536
