### ISSUE TITLE
Inserir uso de ```<contrib-id contrib-id-type="orcid">```  

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/scielo_publishing_schema#218]
Documentar ocorrência e aplicabilidade de elemento contrib-id do tipo orcid no SPS.
![contrib-id](https://cloud.githubusercontent.com/assets/16937218/13151314/c8c96860-d650-11e5-9ed8-ca3dc8d15172.png)

**Comment by robertatakenaka** [comment]
@jenniferamato : Este ticket é duplicação de #174, que já está fechado e previsto para a versão 1.4

Outros tickets que estarão resolvidos para SPS 1.4:
https://github.com/scieloorg/scielo_publishing_schema/issues?q=is%3Aissue+milestone%3A%22vers%C3%A3o+1.4%22+is%3Aclosed

Versão 1.4 disponível por enquanto em:
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/master/

**Comment by gustavofonseca** [comment]
@jenniferamato, de qualquer maneira parabéns pela clareza na descrição do ticket. :+1:
