### ISSUE TITLE
Sugestão SPS aceitar referências com `mixed-citation` totalmente tageado.

### ISSUE THREAD

**Issue by lpanebr** [scieloorg/scielo_publishing_schema#219]
Hoje a SPS exige que as referências sejam codificadas em dois elementos:
- de forma completa no `<element-citation>`, e
- de forma parcial no `<mixed-citation>`.

Gostaria de sugerir que a SPS possa aceitar uma `<ref>` apenas a `<mixed-citation>`, quando esta estiver totalmente tageada.

*\* Exemplo de `<mixed-citation>` totalmente tageada:**
A referência além de manter todos os elementos obrigatórios (ou não da SPS) ainda preserva as pontuações necessárias para sua exibição no estilo editorial do periódico.

``` xml
<ref id="B026"><label>26</label>
<mixed-citation publication-type="journal">
<person-group person-group-type="author"><string-name><surname>Lemierre</surname> <given-names>A</given-names></string-name></person-group>. 
<article-title>On certain septicæmias due to anaerobic organisms</article-title>. <source>Lancet</source>. 
<year>1936</year>;<volume>227</volume>(<issue>5874</issue>):<fpage>701</fpage>-<lpage>3</lpage>. 
<ext-link ext-link-type="uri" xlink:href="http://dx.doi.org/10.1016/S0140-6736(00)57035-4">http://dx.doi.org/10.1016/S0140-6736(00)57035-4</ext-link>.
</mixed-citation>
</ref>
```

**Comment by RPostalli** [comment]
Grande impacto
versão 2.0

**Comment by lpanebr** [comment]
> Grande impacto
> versão 2.0

UAL, LEGAL! :+1: :-)

**Comment by robertatakenaka** [comment]
Relacionados: #781 e #559

**Comment by gustavofonseca** [comment]
O ticket https://github.com/scieloorg/scielo_publishing_schema/issues/559 está relacionado com este.

**Comment by RPostalli** [comment]
Ticket duplicado.
