### ISSUE TITLE
Acrescentar tipos em related-article [Retratação]

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#232]
Acrescentar em related-article <http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-related-article.html>

Os tipos retracted-article e partial-retraction <http://jats.nlm.nih.gov/publishing/tag-library/1.0/>

Envolve documentação (que ainda será atualizada) <http://www.scielo.org/php/level.php?lang=pt&component=56&item=53>

OBS: Inserir exemplo da tag***

**Comment by leticiaquino** [comment]
Relacionado ao #228
