### ISSUE TITLE
Ajustar exemplo de <ext-link> e <comment>

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#237]
Na tag de ```<comment>``` está descrito que: 
(http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-comment.html#comment)

"Tag pode servir para marcar alguma informações juntamente com uma URL (ver tag <ext-link>)"

Quando vamos a tag de ```<ext-link>```, não existe exemplo de uso de link com comment:
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-ext-link.html#elemento-ext-link

Inserir um novo exemplo:

```<element-citation>...<comment>Disponível em: <ext-link ext-link-type="uri" xlink:href="http://www.scielo.org">www.scielo.org</ext-link> </comment>```

**Comment by leticiaquino** [comment]
Resolvido 1.5 (Revisão do guia)
