### ISSUE TITLE
Mudar local de Clinical Trial

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#238]
A documentação de Ensaio Clínico está atualmente em "Perguntas Frequentes", mas a informação fica perdida neste local. 

(http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/faq.html#perguntas-frequentes)

Deve ficar inserido como Documentação Narrativa tal qual está por exemplo Errata e AOP:

Outra ponto da documentação de Ensaio Clínico, existe a seguinte frase:

"Para saber mais sobre Ensaio Clínico, clique no link abaixo: O que é Ensaio Clínico?"

Não encontrei este link. Qual link seria?!?!

**Comment by leticiaquino** [comment]
Relacionado ao #305
