### ISSUE TITLE
Mudar local de subseções

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#239]
A documentação de subseções está atualmente em "Perguntas Frequentes", mas a informação fica perdida neste local. 

(http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/faq.html#perguntas-frequentes)

Documentar em ```<subj-group>```

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-subj-group.html#subj-group

**Comment by gustavofonseca** [comment]
Você pode explicar melhor?

-Gustavo

**Comment by RPostalli** [comment]
Explicado pessoalmente. ;)

**Comment by gustavofonseca** [comment]
Acho que é importante deixar registrado.

A @RPostalli me explicou que o tópico “Perguntas frequentes” é fonte recorrente de confusão pois, além de não representarem as perguntas que de fato são frequentemente recebidas, ainda tem como efeito colateral a supressão dos seus sub-tópicos na lista de links rápidos, do lado esquerdo da tela.

Eu sugeri que esse tema seja levantado no contexto da revisão editorial que está em curso.

-Gustavo

**Comment by leticiaquino** [comment]
Duplicado em #305
