### ISSUE TITLE
Reavaliar regra de AOP em @article-type

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#240]
Em AOP está descrito que: "Todos os arquivos Ahead Of Print (AOP) devem apresentar o valor “research-article” em @article-type"

Os artigos já poderiam vir com o article-type ao qual pertencem. No processo de migração destes documentos pela equipe de marcação, podem ocorrer muitos erros de interpretação do tipo de documento que não compete a equipe e sim ao editor e/ou prestador de serviço.

AOPs são indexados em PubMed (enviados por nós) e já entram nos fatores de impacto da base, ou seja, documentos como editorial, cartas e etc estão sendo contatos como research-article incorretamente o que pode causar erros em contagens bibliométricos.

Em minha opinião esta regra deve ser retirada.

**Comment by gustavofonseca** [comment]
Thread relacionada na lista scielo-xml-sig(privada): https://groups.google.com/d/topic/scielo-xml-sig/1NCvqYEHpMU/discussion

-Gustavo

**Comment by leticiaquino** [comment]
Avaliar também a obrigatoriedade de ```<subject>```.
