### ISSUE TITLE
Inserir exemplos nas tags

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#241]
Um dos intuitos da documentação é a descrição da tag e principalmente como é feito seu uso. Quando mudamos o formato da documentação para ordem alfabética alguns exemplos foram suprimidos e outras já não tinham mesmo exemplo.

TAGS SEM EXEMPLO:
```<addr-line>
<article-categories>
<article-meta>
<award-group>
<collab>
<contrib-group>
<day>
<edition>
<funding-group>
<history>
<isbn>
<journal-meta>
<mixed-citation>
<p>
<publisher-loc>
<publisher-name>
<size>
<source>
<table-wrap>
<title-group>
<trans-title-group>
<year>```

**Comment by leticiaquino** [comment]
Resolvido.
