### ISSUE TITLE
Acrescentar em <ext-link> o atributo com valor ext-link-type="ClinicalTrial"

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#242]
Acrescentar na tag `<ext-link>` a possibilidade do atributo com valor ext-link-type="ClinicalTrial"
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-ext-link.html#ext-link

**Hoje está**

Atributos obrigatórios
ext-link-type=”uri”
xlink:href

**Deveria ser**

Atributos obrigatórios
ext-link-type=”uri” ou ext-link-type="ClinicalTrial"
xlink:href

**Comment by gustavofonseca** [comment]
Pode adicionar um exemplo do elemento devidamente preenchido?

-Gustavo

**Comment by RPostalli** [comment]
```<p>Trial registration number:<ext-link ext-link-type="ClinicalTrial"
                xlink:href="https://clinicaltrials.gov/ct2/show/NCT01995279?term=NCT01995279"
                >NCT01995279</ext-link></p>```

**Comment by leticiaquino** [comment]
Acrescentar no guia que os valores possíveis para o ``@ext-link-type``  são:

* uri
* ClinicalTrial

**Comment by gustavofonseca** [comment]
@leticiaquino, sabe dizer se há algum motivo para termos escolhido a forma ``ClinicalTrial`` ao invés de ``clinical-trial``?

**Comment by leticiaquino** [comment]
@gustavofonseca não estou lembrada se houve um motivo para essa decisão.

**Comment by gustavofonseca** [comment]
@leticiaquino acha que podemos rever? Termos apenas esse valor com o formato *upper camel case* me parece muita pegadinha para o usuário.

**Comment by leticiaquino** [comment]
@gustavofonseca acredito que tudo bem colocar esse valor em caixa baixa.

**Comment by gustavofonseca** [comment]
@robertatakenaka, qual sua opinião sobre isso?

**Comment by gustavofonseca** [comment]
Reabri o ticket para termos certeza da forma correta que o valor deve ser grafado.

**Comment by gustavofonseca** [comment]
@leticiaquino, @robertatakenaka 🔔 🔔

**Comment by leticiaquino** [comment]
@gustavofonseca Você vê algum impedimento para usar em caixa baixa?
Acredito que eu teria apenas que abrir um ticket no Markup para a @robertatakenaka considerar o valor em caixa baixa.

**Comment by gustavofonseca** [comment]
Eu não vejo impedimentos inclusive por que, em teoria, esse valor de
atributo está entrando agora na especificação. 

-Gustavo

Em Qua 21 set. 2016, às 11:08, Letícia Aquino escreveu:

**Comment by leticiaquino** [comment]
Ticket resolvido.
Foi ajustado na documentação o valor ``ClinicalTrial`` para  ``clinical-trial`` e adicionado o valor ``uri``.
