### ISSUE TITLE
Acrescentar em Regras de Nomeação de Arquivos - RPass

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#243]
Acrescentar no link de "regras de nomeação" que a nomeação de RPass é a mesma regra de AOP.

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/narr/regra-nomeacao.html

(aparece uma vez no texto)
Para Ahead Of Print **e Rolling Pass** considerar:

(aparece 3 vezes no texto)
Para Ahead-Of-Print **e Rolling Pass**:

**Comment by leticiaquino** [comment]
Ticket relacionado ao #317 .
