### ISSUE TITLE
Possibilidade de incluir atributo para "publicado online"

### ISSUE THREAD

**Issue by lucasssantos** [scieloorg/scielo_publishing_schema#244]
No SPS não há atributo para casos onde consta informação datando a publicação do artigo conforme o exemplo abaixo.
![sem titulo](https://cloud.githubusercontent.com/assets/19777809/16056866/d04b8754-324d-11e6-8566-6d2ca55a5de4.png)

Consultando a JATS observamos que eles possuem um atributo para esse tipo de caso. Colocamos atributo "pub" e em homolog só aparece o dado.
Abaixo atributos da JATS para date-type.
![sem titulo](https://cloud.githubusercontent.com/assets/19777809/16056991/3cd1924c-324e-11e6-9286-33d06f2a2c1c.png)

**Comment by carolinatanigushi** [comment]
Relacionado ao #527.
