### ISSUE TITLE
Erro na documentação de <article-id>

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#249]
article-id do tipo DOI só pode aparecer uma única vez no documento. Na documentação falamos que pode aparecer Uma ou mais vezes. De fato article-id pode aparecer mais vez, mas não o com tipo DOI e neste caso dizemos que o pub-id-type=’doi’ é obrigatório, logo a documentação fica conflitante.

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-article-id.html

article-id
Aparece em
article-meta
Atributos obrigatórios
pub-id-type=’doi’
Ocorre
**Uma ou mais vezes**

OBS: O uso de outros tipos de article-id são usados apenas internamente. Exemplo: do article-id do tipo other para AOPs e RPass.

**Comment by leticiaquino** [comment]
Ticket relacionado ao #273
