### ISSUE TITLE
Reduzimos o elemento *<named-content>* a um reles identificador de cidade e estado.

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#250]
Penso que não podemos resignificar o elemento `<named-content>` da maneira que está sendo feita atualmente no guia SciELO PS, ao dizer que "... representa as informações de endereço que aparecem em afiliação"[1].

Uma coisa é, na documentação do elemento `<addr-line>` dizermos que o elemento `<named-content>` deve ser usado para representar _blá_, e outra é dizer que ele só serve para isso.

Veja aqui como o elemento `<named-content>` é útil/rico/cheio de semântica/pimpão [2].

[1] http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-named-content.html 
[2] http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-fz40.html

**Comment by leticiaquino** [comment]
@gustavofonseca nesse caso a possibilidade que eu vejo, no momento, é alterarmos a escrita.
Pelo o que eu pude ver na JATS1.0 não tem nenhum elemento que possa identificar esses dados melhor.

Já na JATS 1.1, eu vi que existe tag própria para isso. Veja:

http://jats.nlm.nih.gov/publishing/tag-library/1.1/element/state.html
http://jats.nlm.nih.gov/publishing/tag-library/1.1/element/city.html
 :disappointed:

**Comment by gustavofonseca** [comment]
Não tem problema de utilizarmos o ``<named-content>`` também para isso. O problema é reduzirmos ele a só isso.

-Gustavo

**Comment by javani** [comment]
Relacionado à #487

**Comment by carolinatanigushi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resolver](https://trello.com/c/fNUMQaUV/114-resolver)

**Comment by RPostalli** [comment]
Aparentemente este ticket está resolvido.

**Comment by RPostalli** [comment]
Retirado documentação de named-content. Com a DTD 1.1 a documentação de dados como city e state possuem tags próprias.

Corrigido exemplo em <adr-line>

named-content ainda pode ser usado por ser JATS.
https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/named-content.html

Errado:
NAMED-CONTENT
![image](https://user-images.githubusercontent.com/6084959/53263661-da8bfb00-36b8-11e9-8ddc-a78c516e6c32.png)

ADDR-LINE
![image](https://user-images.githubusercontent.com/6084959/53263742-0ad39980-36b9-11e9-8293-5f8dea66c0a6.png)

Correto:
CITY
![image](https://user-images.githubusercontent.com/6084959/53263766-16bf5b80-36b9-11e9-8db2-31b500df7f0f.png)

POSTAL-CODE
![image](https://user-images.githubusercontent.com/6084959/53263790-22ab1d80-36b9-11e9-9b5c-6e541d2a5264.png)

STATE
![image](https://user-images.githubusercontent.com/6084959/53263800-2c348580-36b9-11e9-846e-0c48d62bc0d9.png)
