### ISSUE TITLE
Erro na documentação de Errata (Não é permitido pela JATS)

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#251]
https://github.com/scieloorg/scielo_publishing_schema/issues/146

Não é permitido ```<title>``` em ```<fn>``` somente em ```<fn-group>```. Realizamos a documentação incorreta.

No entanto a nota de Errata deve ser diferenciada das notas comuns. (solicitação Abel, ele quer o título Errata em negrito)

@robertatakenaka temos que pensar em como corrigir este problema.

Uma das opções seria usar:

```<fn-group>
<fn fn-type="other">
<p><bold>Errata</bold></p>
<p>jdjfladjfladjfdajfd</p>
<p>jdjajfaljfaljflad</p> 
</fn-group>
</fn>```

Mas temos também a regra que não se pode usar formatação em todo o conteúdo de uma tag o que invalidaria ```<p><bold>Errata</bold></p>```.

**Comment by RPostalli** [comment]
@robertatakenaka a @javani comentou uma ideia melhor para corrigirmos o problema.

Para errata criar um novo fn-group, já que title pode aparecer em fn-group e fn-group é permitido zero ou mais vezes no XML.

Exemplo:

```<back>
			<fn-group>
				<title>Nota</title>
				<fn fn-type="other">
					<label>xxxxxxxx</label>
					<p>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</p>
				</fn>
			</fn-group>
			<fn-group>
				<title>Errata</title>
				<fn fn-type="other">
					<p>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</p>
				</fn>
			</fn-group>
</back>```

**Comment by gustavofonseca** [comment]
@RPostalli, desculpa mas eu não consegui entender absolutamente nada que está escrito nesse ticket. O que não é permitido em ``<fn>``, mas apenas em ``<fn-group>``, e nós documentamos de forma errada?

**Comment by RPostalli** [comment]
Era só a configuração, veja se entende agora.

**Comment by javani** [comment]
@gustavofonseca Documentamos <title> em <fn> na documentação de errata. A @RPostalli e eu estamos sugerindo ter um <fn-group> específico para errata já que <title> é permitido para esse elemento e ele pode ocorrer zero ou mais vezes tendo títulos diferentes, assim como ocorre em ref-list. Como há casos nos artigos que corrigimos que já tem notas com seu título e para a errata ter um destaque pensamos nessa maneira, uma vez que incluir o conteúdo da errata num grupo de notas já existente com <label> deixa a visualização prejudicada.

**Comment by leticiaquino** [comment]
Relacionado ao #316.
