### ISSUE TITLE
Tornar obrigatório o uso do *elocation-id* para artigos ahead-of-print.

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#253]
O guia diz que o artigo _ahead-of-print_ "[...] não apresenta volume, número e paginação, portanto os elementos <volume> e <issue> não devem ser utilizados. Considerar “00” somente para páginação [...]"[1]. A afirmação está correta, mas a recomendação é bem ruim pois fomenta a identificação de _dados placebo_, que só servem para silenciar os validadores. 

A recomendação que sugiro é de atribuirmos um identificador único, por meio do elemento _elocation-id_, para cada artigo _ahead-of-print_. Esse identificador pode ser uma sequência pseudo-aleatória gerada automaticamente via programa de computador. 

[1]http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/narr/aheadofprint.html

**Comment by asael-silva** [comment]
Gustavodevo fazer o que então com o texto?

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 7 Jul 2016 10:56:54 -0700

**Comment by gustavofonseca** [comment]
@asael-silva, não precisa fazer nada. Nós ainda temos que discutir internamente essa mudança e, caso aprovada, só passará a valer depois de setembro.

**Comment by francine-curivil** [comment]
Para registro, em 08/06/2017 durante a "Reunião semanal - SciELO PS" decidimos (Aline, Carolina, Francine, Gustavo, Javani e Solange) não seguir a sugestão e fechar este ticket.
