### ISSUE TITLE
Reavaliar a regra para a identificação de "Artigo Comentado".

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#254]
Essa questão foi levantada inicialmente na lista _scielo-xml-sig_(privada), na thread intitulada "[Sobre a regra para a identificação de "Artigo Comentado](https://groups.google.com/d/msg/scielo-xml-sig/K0ioZNiMAlw/-gBTeoAELAAJ)".

> De acordo com a regra definida na documentação narrativa do guia da SciELO PS[1], a representação em XML dos artigos que apresentam comentários do editor embutido (exemplo aqui[2]) devem ter o valor do atributo _/article/@article-type_ igual a _article-commentary_, mesmo que seja de fato um artigo original. O fato de o editor ter incluído um comentário em determinado artigo deveria interferir no seu tipo? 

[1]http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.4-branch/narr/artigo-comentado.html
[2]http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1677-55382015000200288

**Comment by javani** [comment]
@gustavofonseca @RPostalli A JATS define artigo comentado como um artigo que possui como tema outro artigo ou artigos  e enfatiza ainda que o artigo é feito por outros autores com opinião contrária ao artigo que originou a discussão, publicando ambos juntos posteriormente. Quando o editor comenta um artigo o valor do artigo não muda, mas ele estará relacionado ao artigo principal e seu tipo seria "commentary-article". O valor em article-type em sub-article seria "editorial" no caso citado acima.
Talvez seja melhor usarmos para "Artigo Comentado" a mesma definição dada pela JATS - artigo cujo o tema ou foco é outro artigo ou artigos. Apenas nesse caso usaríamos "article-commentary" em "article-type".

**Comment by RPostalli** [comment]
Concordo.

**Comment by javani** [comment]
@gustavofonseca @RPostalli @robertatakenaka @carolinatanigushi Olhando a Tagging Guidelines do PMC há a indicação de uso de related-article para artigos do tipo article-commentary.
Commentaries

Use @article-type="article-commentary" on ```<article>```.
Capture the commented-on article information in <related-article> @related-article-type="commentary-article".
https://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/dobs.html#dob-arttype-comment

Não há indicação de uso de response para esse tipo de documento - https://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/dobs.html#dob-response

Sugiro como nova redação do item:

Artigos que apresentam o valor "_article-commentary_" no atributo _@article-type_ em ```<article>``` devem apresentar, obrigatoriamente, um elemento ```<related-article>``` com o valor _"commentary-article"_ no atributo _@related-article-type_.

```
...
<article xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" specific-use="sps-1.2" dtd-version="1.0" article-type="article-commentary" xml:lang="en">
<front>
...
<article-meta>
      ...
</permissions>
      <related-article related-article-type="commentary-article" id="r01" vol="109" page="87-92"/>
   ...
 </article-meta>
</front>
...
</article>
```

**Comment by gustavofonseca** [comment]
@javani, só gostaria de pontuar algo em relação ao seu último comentário. Onde você diz:

> Talvez seja melhor usarmos para "Artigo Comentado" a mesma definição dada pela JATS - artigo cujo o tema ou foco é outro artigo ou artigos. Apenas nesse caso usaríamos "article-commentary" em "article-type".

Eu concordo com a sua proposta de definição. O único problema que vejo está no uso do termo _Artigo Comentado_, que ao meu ver deveria ser chamado de _Comentário de Artigo_ -- que inclusive é a tradução correta de _article commentary_. Artigo comentado é aquele que recebeu o comentário, não quem o teceu.

**Comment by carolinatanigushi** [comment]
@javani @gustavofonseca hmmmm, concordo com o Gustavo... **Artigo comentado** seria traduzido como **commented article**.

**Comment by javani** [comment]
@gustavofonseca você está certo. Vou alterar o conteúdo.
