### ISSUE TITLE
Reavaliar a restrição de valores em @related-article-type do elemento <related-article>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#255]
Precisamos reavaliar os valores que restringimos em @related-article-type. Atualmente aceitamos os valores "corrected-article" e "commentary-article". Porém há a possibilidade também de termos uma carta e uma resposta separada da carta. Nesse caso, para relacionar a resposta à carta, é necessário inserir um `<related-article>` com o valor "letter".

Devemos avaliar também a possibilidade de ter a tradução de um documento separada do original. Nesse caso a tradução também ganharia um `<related-article>` para relacionar a tradução ao artigo original.

Verifiquei alguns valores possíveis na JATS para considerarmos no SciELO PS:
- letter (def.:Names a letter to the publication or a reply to such a letter)
- retracted-article (def.: Used in a retraction to name the article being retracted)

Ver em: http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-yjj0.html

Caso tenham mais alguma sugestão, por gentileza insiram como comentário.

**Comment by leticiaquino** [comment]
Em reunião o @gustavofonseca sugeriu o valor "translated-article" para traduções, caso a gente decida separar as traduções.

**Comment by gustavofonseca** [comment]
O pull-request https://github.com/leticiaquino/scielo_publishing_schema/commit/c90884bbe114d9186249d9b4d5eba75748ac3e3d adiciona o valor ``translated-article``, para o relacionamento entre traduções e sua versão original, que ainda não será possível de ser realizado. Portanto esse valor deve ser removido da lista.

**Comment by leticiaquino** [comment]
@gustavofonseca o valor "translated-article" foi removido da lista, porém vamos manter o ticket aberto para, futuramente, incluir o valor novamente na documentação.

Verificar valores aceitos na verão 1.5: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/tagset/elemento-related-article.html

**Comment by gustavofonseca** [comment]
blz @leticiaquino!

**Comment by javani** [comment]
Não há previsão de publicação em separado de tradução. Por agora vou fechar o ticket.
