### ISSUE TITLE
Documentar <p> em <caption>

### ISSUE THREAD

**Issue by javani** [scieloorg/scielo_publishing_schema#259]
Documentar ```<p>``` em ```<caption>``` para os casos em que há dado explicativo que não faz parte de notas e nem do título.
![image](https://cloud.githubusercontent.com/assets/912953/17024534/abe753ae-4f2e-11e6-83ff-4353c11ec21c.png)

**Comment by asael-silva** [comment]
Javani
não entendi para quem é essa informação, nem a respeito de que tag. Outrossim, não tenho conhecimento para editar/criar texto. Eu reviso, mas creio que o combinado era vocês terem o texto a ser revisado.

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 21 Jul 2016 06:34:38 -0700

**Comment by javani** [comment]
@asael-silva Olá Asael, isso tem a ver com processos relacionados à próxima versão do SciELO PS. Não se preocupe pois não tem vínculo com a sua atividade atual.
Grata,
