### ISSUE TITLE
article-title em product

### ISSUE THREAD

**Issue by natalieakemi** [scieloorg/scielo_publishing_schema#260]
A estrutura dentro da tag `<product>` tem que ter `<article-title>` também já que `<product>` permite a resenha de artigo.

**Comment by asael-silva** [comment]
Oi Natalia
poderia ser menos técnica? Para vocês é um discurso lógico, mas para um leigo (meu caso), há dúvidas de onde deve ser incluído <article-title> (exemplos, texto, seções [Aparece em] etc). Prefiro que vocês me digam o que deve ser feito e onde. 

Asael C Silvagandhalf_thewhite@live.com



Date: Fri, 22 Jul 2016 05:08:52 -0700

**Comment by natalieakemi** [comment]
Asael, olá,
Abri o ticket no local errado. Por favor desconsiderar.
