### ISSUE TITLE
Formatar a lista de ferramentas de apoio

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#261]
Relacionado ao item http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/index.html#ferramentas-de-apoio
Informo que lista de ferramentas de apoio está em formato de lista desordenada e lista de definição.
Por favor, formatar como lista de definição. Segue abaixo um link para formatação:

http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#definition-lists

A forma como está no site fica um pouco confuso, pois a descrição de um item está muito próxima do termo do item posterior.

**Comment by asael-silva** [comment]
Alterado para Lista de definição.

Asael C Silvagandhalf_thewhite@live.com



Date: Wed, 27 Jul 2016 11:59:59 -0700

**Comment by leticiaquino** [comment]
@asael-silva desculpe, faltou dizer que:

Em ferramentas de apoio, deve ser inserido link na palavra "open source" direcionando para o glossário.
Assim como foi feito com outros termos.
A palavra está no seguinte contexto:
"... disponibilizadas e mantidas pela SciELO seguindo o modelo **open source**

**Comment by asael-silva** [comment]
Alterado.
