### ISSUE TITLE
Correção no tópico Ahead Of Print

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#262]
No item http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/narr/aheadofprint.html

Alterar:
...e em //subj-group[@subj-group-type="heading"]/subject conter o **valor** Articles.

Para:
...e em //subj-group subj-group-type="heading">/subject inserir o **texto** Articles. 

Inserir link na palavra Ahead Of Print em:
“Para artigos publicados no formato Ahead of Print..."

Trocar também o exemplo de XML para:

```xml
<article article-type="research-article" dtd-version="1.0" specific-use="sps-1.0" xml:lang="es" xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xlink="http://www.w3.org/1999/xlink">
   …
<article-categories>
   <subj-group subj-group-type="heading">
      <subject>Articles</subject>
   </subj-group>
</article-categories>
...
   <pub-date pub-type="epub">
      <day>12</day>
      <month>08</month>
      <year>2016</year>
   </pub-date>
   <fpage>00</fpage>
   <lpage>00</lpage>
   ...
</article>
```

E alterar a informação:
“Para estes arquivos...” 
Para: 
“Para estes artigos...

**Comment by asael-silva** [comment]
Realizadas as alterações, exceto por:
Inserir link na palavra Ahead Of Print em:
“Para artigos publicados no formato Ahead of Print..."


cujo texto não consta do arquivo aheadofprint.rst.


Asael C Silvagandhalf_thewhite@live.com



Date: Wed, 27 Jul 2016 12:21:49 -0700

**Comment by leticiaquino** [comment]
@asael-silva não entendi.

O link na palavra Ahead Of Print é para direcionar para o termo no glossário, assim como foi feito por exemplo com o termo "Pacotes SciELO PS" em [Ferramentas de apoio](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/index.html#ferramentas-de-apoio).

**Comment by asael-silva** [comment]
@leticiaquino - eu entendi o que é para fazer. O problema é que o texto que você citou:

“Para artigos publicados no formato Ahead of Print..."

não existe no arquivo aheadofprint.rst.

Então não tenho como fazer.

**Comment by asael-silva** [comment]
@leticiaquino ficou clara minha dúvida? Será que o texto a ser alterado não está em outro arquivo?

**Comment by leticiaquino** [comment]
@gustavofonseca será que houve algum conflito nessa parte do documento?

**Comment by gustavofonseca** [comment]
Pode ter ocorrido, sim. Mas para termos certeza devemos olhar os
branches "pack-[1,2,3]".

-Gustavo


Em Qua 3 ago. 2016, às 15:24, Letícia Aquino escreveu:

**Comment by gustavofonseca** [comment]
O texto "Para artigos publicados no formato Ahead.." foi modificado no commit 6f9638b751 como é possível ver no diff: https://github.com/scieloorg/scielo_publishing_schema/commit/6f9638b751ce9dc83ff64909083a6c35c5128d36#diff-014a4e1ec2eb548f2534ff957597759eL27

Mais um mistério resolvido  :mag_right:

**Comment by asael-silva** [comment]
Sem alterações a realizar.
