### ISSUE TITLE
Correção no tópico Artigo Comentado

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#263]
Em http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/narr/artigo-comentado.html

Inserir a informação de posição do ```<related-article>```, assim como foi feito para Ahead Of Print:
"```<related-article>``` deve ser inserido abaixo das informações de ```<permissions>``` ou acima de ```<counts>```."

Alterar a palavra “relacionada” para “relacionado” em:
“Artigos que apresentam um comentário diretamente relacionado ao artigo principal devem…”

**Comment by asael-silva** [comment]
Letícia
o trecho abaixo não está claro para mim. Não encontrei trecho semelhante em aheadofprint.rst e não sei exatamente em que parte do texto de artigo-comentado.rst devo incluir a informação. Não poderíamos manter o modo como vocês faziam revisão diretamente no git e eu recebia uma cópia dos comentáros? Pelo menos lá eu tinha indicação exatamente de onde era para ser realizada a operação.

Inserir a informação de posição do , assim como foi feito para Ahead Of Print:"<related-article> deve ser inserido abaixo das informações de <permissions> ou acima de <counts>."

Asael C Silvagandhalf_thewhite@live.com



Date: Wed, 27 Jul 2016 12:26:14 -0700

**Comment by leticiaquino** [comment]
@asael-silva desculpe, inseri o elemento de exemplo errado. Seria : Inserir posição do ```<related-article>```assim como foi feito para **Errata**.
Ou seja, incluir uma nota informativa indicando em que posição inserir o elemento ```<related-article>```.

A nota é:
```<related-article>``` deve ser inserido abaixo das informações de ```<permissions>``` ou acima de ```<counts>```.

**Comment by asael-silva** [comment]
Alterado.
