### ISSUE TITLE
Correção no tópico "Caracteres Especiais"

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#264]
No tópico http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/narr/caracteres.html

Sobre o trecho "Caracteres especiais, quando utilizados, devem ser inseridos diretamente no documento ou por meio de referências numéricas em notação hexadecimal. Por exemplo, o caractere sigma maiúsculo deve ser representado por Σ ou ``&#x03A3;``."

Acho que seria interessante apresentarmos nossa preferência para a inserção dos caracteres em vez de referências numéricas em notação hexadecimal.
Pode ser em uma nota informativa: 
SciELO PS recomenda o uso de caracteres inseridos diretamente no XML em vez de notação hexadecimal.

Alterar também a frase: 
“Maiores informações encontram-se disponívels...”
Trocar para:
Para mais informações acesse a tabela Unicode.

**Comment by asael-silva** [comment]
Nota colocada.
O trecho abaixo se for modificado entrará em conflito com o estilo do manual pois indica no tempo verbal 'acesse' é diferente da linguagem impessoal utilizada, onde não se usa imperativo.
Em: 
“Maiores informações encontram-se disponívels...”
Trocar para:
Para mais informações acesse a tabela Unicode.
Poderia ser "Para maiores informações ver a ..." ?

Asael C Silvagandhalf_thewhite@live.com



Date: Wed, 27 Jul 2016 12:35:20 -0700

**Comment by leticiaquino** [comment]
@asael-silva ok, concordamos com sua sugestão: "Para maiores informações ver a ..."

**Comment by asael-silva** [comment]
Alterado.
