### ISSUE TITLE
Correção no tópico Errata

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#265]
No tópico http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/narr/errata.html

Na frase:
“...O padrão do documento em si deve seguir as instruções de Ahead Of Print.”
Inserir link na palavra “Ahead Of Print” direcionando para o elemento correspondente no glossário

Alterar a frase:
“... deve refletir o sumário do número, e no elemento…”
Para:
“...deve conter a seção apresentada no sumário do número e, no elemento…”

Na frase: “... e o título do artigo que possui a informação incorreta.”
Mudar para:
“e o título do artigo a ser corrigido.

**Comment by asael-silva** [comment]
Alterações realizadas.
NOTA: a entrada no glossário para 'Ahead of Print' é 'ahead-of-print'. O link foi então inserido como ':term:`ahead-of-print`'. Desconheço outro modo de apontar um item de glossário. Lembro inclusive de ter comentado em algum texto ou troca de mensagens que havia uma confusão entre a terminologia que aparece no glossário e a referência ao tópico 'ahead-of-print', mas não me recordo se houve um consenso em alterar estas definições.

Asael C Silvagandhalf_thewhite@live.com



Date: Wed, 27 Jul 2016 12:44:24 -0700

**Comment by leticiaquino** [comment]
@asael-silva Sim, seria para direcionar para o termo no glossário como :term:`ahead-of-print`.

@gustavofonseca você sabe de algo sobre essa discussão que o Asael apresenta a respeito da "terminologia que aparece no glossário e a referência ao tópico 'ahead-of-print'"?

**Comment by gustavofonseca** [comment]
@leticiaquino, minha memória não está lá essas coisas.. mas sugiro a gente normalizar o uso com "ahead of print" (sem hífens). Podemos fazer uma busca-e-troca geral nos arquivos.

**Comment by leticiaquino** [comment]
@gustavofonseca Ok.

**Comment by asael-silva** [comment]
Então apenas para deixar claro. No glossário 'ahead-of-print' passa a ser 'ahead of print'. O arquivo aheadofprint.rst continua com o termo ``.. _ahead-of-print:`` para manter diferenciado da entrada do glossário e todas as referências para 'ahead-of-print' serão feitas por processo automatizado pelo Gustavo. E o que vai ser dos termos ``*Ahead of Print*`` que se encontram nos textos, inclusive na definição do próprio termo (glossary.rst)? Mantém como está?

**Comment by asael-silva** [comment]
Meu comentário anterior foi lido? Creio que há uma dúvida importante para se revisar.

**Comment by gustavofonseca** [comment]
As referências ao termo _Ahead of Print_, do glossário, deverão ser ajustadas. Não entendi a dúvida.

**Comment by asael-silva** [comment]
@gustavofonseca , quando está escrito Ahead of Print, só sabemos para qual entrada deve ser linkado (glossário ou arquivo aheadofprint.rst) a partir do contexto, certo? É aí que reside minha dúvida. Porque 'Ahead of Print' como entrada de glossário deixou de existir quando definimos que ficaria como 'ahead of print'. Entendeu agora?

**Comment by leticiaquino** [comment]
Ticket resolvido. O termo "ahead of print" foi utilizado para referenciar o termo no glossário; já a palavra "Ahead Of Print" foi utilizada para referenciar o tipo de documento "AOP". em: Tipos Especiais de Documentos.
