### ISSUE TITLE
Sobre o tópico "Regras de Nomeação"

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#266]
Em http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/narr/regra-nomeacao.html

Inserir a seguinte nota:
Nunca usar underline na nomeação de pacotes ou arquivos (XML, PDFs, ativos digitais)

**Na frase:**
“Todos os arquivos, incluindo XML, PDF e imagens referentes ao número em questão devem estar na mesma pasta nomeada conforme o padrão abaixo:”
**Alterar para:**
Todos os arquivos de um pacote, incluindo XML, PDF, imagens, mídias e materiais suplementares, caso existam, devem estar na mesma….

**Comment by asael-silva** [comment]
Letícia
A nota deve ser incluída em que parte do texto, preciso de um texto âncora. Lembre-se que você conhece o assunto, eu não.
A outra alteração foi realizada.


Asael C Silvagandhalf_thewhite@live.com



Date: Wed, 27 Jul 2016 12:50:35 -0700

**Comment by leticiaquino** [comment]
@asael-silva inserir a nota ao final de: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/narr/regra-nomeacao.html#nomeacao-de-pasta-para-envio

**Comment by asael-silva** [comment]
Alterado.
