### ISSUE TITLE
Sobre o tópico "Addr-line"

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#267]
No item http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-addr-line.html

**Na frase:**
“Identifica os dados referente ao endereço da instituição vinculada ao autor. Eventualmente pode conter somente informações de estado e cidade.”
**Mudar para:**
Identifica a cidade e o estado da instituição vinculada ao autor, caso exista.

**Comment by asael-silva** [comment]
Alterado

Asael C Silvagandhalf_thewhite@live.com



Date: Wed, 27 Jul 2016 12:59:57 -0700
