### ISSUE TITLE
Sobre o tópico "Abstract"

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#268]
Em http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-abstract.html

Sugiro ou retirar a informação entre parênteses : "... (Introdução, Objetivos, Métodos e Resultados).", ou inserir a seguinte informação:
(Por exemplo: Introdução, Objetivos, Métodos e Resultados).

Isso porque é possível que um documento não apresente as seções tradicionais "introdução, objetivos etc..." e as seções do resumo podem refletir as seções do documento.

**Comment by asael-silva** [comment]
Alterado.

Asael C Silvagandhalf_thewhite@live.com



Date: Wed, 27 Jul 2016 13:04:12 -0700
