### ISSUE TITLE
Sobre o tópico "Ack"

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#269]
Em http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-ack.html

**No segundo parágrafo alterar:**
“...com o elemento ```<title>``` (JATS versão 1.0). Também é possível utilizar o elemento ```<p>```” 
**Para:**
“...com o elemento ```<title>```. Utilizar o elemento ```<p>```...”

**Comment by asael-silva** [comment]
Letícia/Gustavo
meu arquivo elemento-ack.rst está diferente:
No caso de ter um título (ex. "Agradecimentos" ou "Acknowledgment") identifica-se com o elemento ``<title>`` (`JATS versão 1.0 <http://jats.nlm.nih.gov/publishing/1.0/>`_). O elemento :ref:`elemento-p` é utilizado para identificar parágrafos do texto.
Retiro somente o link para JATS?

Asael C Silvagandhalf_thewhite@live.com



Date: Wed, 27 Jul 2016 13:09:33 -0700

**Comment by leticiaquino** [comment]
@asael-silva talvez essa tenha sido uma das modificações que não foram incorporadas..

Pode utilizar o seu exemplo, mas exclua a informação JATS 1.0.. Veja:

No caso de ter um título (ex. "Agradecimentos" ou "Acknowledgment") identifica-se com o elemento ```<title>``` . O elemento :ref:`elemento-p` é utilizado para identificar parágrafos do texto.

**Comment by asael-silva** [comment]
Alterado.
