### ISSUE TITLE
Adicionar definições no glossário

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#27]
[x] JATS Publishing
[x] ISBN
[x] seções de primeiro nível
[x] w3c
[x] mathml
[ ] NISO JATS table model
[x] ABNT
[x] vancouver
[x] apa
[x] ISO
[x] ISO 639-1

---- 
Atualização
[ ] Número

**Comment by leticiaquino** [comment]
@gustavofonseca add também "número"

Relacionado ao ticket: #130

**Comment by gustavofonseca** [comment]
:+1:

**Comment by leticiaquino** [comment]
Relacionado ao #313
