### ISSUE TITLE
Sobre o tópico "Aff" (Afiliação)

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#270]
Em http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-aff.html

Na parte "Considera-se como afiliação o título em processo de outorga, ou seja..." 
informar que não apenas afiliações em processo de outorga (mestrando, doutorando etc), mas também pessoas que estão vinculadas diretamente à instituição como:
Professor na Universidade x, Médico na instituição x... , Enfermeira no hospital x etc...

Obs.: Não será considerado como afiliação informações como: Médico **pela** Universidade..., Professor **pela** Universidade...

Retirar a frase “Outras formas possíveis, mas não recomendadas, são: USP (sigla), University of São Paulo, Saint Paul University etc.”

**Comment by leticiaquino** [comment]
@asael-silva caso haja alguma dúvida com relação a esse ticket, por favor nos informe.

**Comment by asael-silva** [comment]
Se não me engano, isso já havia sido feito anteriormente, mas estava em outro lote. O arquivo de 28/07 contém o seguinte texto:

"Considera-se como afiliação o vínculo institucional dos contribuintes do artigo naquele momento, seja pelo título em processo de outorga, por exemplo, *Mestrando(a)*, *Doutorando(a)*, *Pós-Graduando(a)* etc, como também pessoas vinculadas diretamente à instituição, como por exemplo, *Professor na Universidade X*, *Médico na instituição Y, Enfermeira no Hospital Z etc."

**Comment by asael-silva** [comment]
O arquivo foi reeditado nesta data pois havia problema de formatação.

**Comment by leticiaquino** [comment]
@gustavofonseca vamos precisar verificar se houve conflitos aqui também.

**Comment by gustavofonseca** [comment]
Não entendi. Qual o problema?

**Comment by javani** [comment]
@leticiaquino documentação conforme ticket.

**Comment by leticiaquino** [comment]
Ticket Resolvido
