### ISSUE TITLE
Sobre o tópico "App" (Apêndice)

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#271]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-app.html

Em apêndice com vídeo alterar o título inserido no ```<label>``` do exemplo para:
Apêndice 1

**Em:**
 “mesmo que houver somente uma ocorrência…”
**Mudar para:**
mesmo se houver somente uma ocorrência...

**Comment by asael-silva** [comment]
Alterado

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 06:15:33 -0700
