### ISSUE TITLE
Sobre o tópico <article>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#272]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-article.html

No exemplo, alterar o valor "sps-1.3" e manter o valor "1.0", o qual foi informado acima que "...é apenas uma referência genérica à versão da SciELO PS."

**Em:**
O atributo tipo de documento não deve ser confundido com a seção em que o documento aparece no sumário (```<subj-group>```). 

**Retirar:**
 (```<subj-group>```)

**Comment by asael-silva** [comment]
Alterado.

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 06:18:04 -0700
