### ISSUE TITLE
Sobre o tópico <article-id>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#273]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-article-id.html

**Alterar:**
"Identificador único para cada artigo, sendo no caso da SciELO Brasil definido obrigatoriamente com o valor DOI."

**Para:**
Identificador único do documento em uma base de dados.
O elemento <article-id> deve, obrigatoriamente, apresentar o atributo @pub-id-type, o qual é utilizado para nomear o tipo de identificador.

O atributo @pub-id-type permite os seguintes valores:

Valor         | Descrição
--------------|-----------------------------------------------------------------------------------
doi           | Digital Object Identifier
publisher-id  | Pode ser utilizado como identificador designado pela Coleção SciELO 
other         | Utilizado para ordenar documentos Rolling Pass e Ahead Of Print. (Para uso durante o período de migração de tecnologia)
 

Para SciELO Brasil é obrigatório o uso de @pub-id-type=”doi” como identificador único do documento.

**Comment by asael-silva** [comment]
Alterado. Resta apenas uma dúvida minha. O identificador único não seria de um artigo (article-id) invés de documento?

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 06:31:27 -0700

**Comment by gustavofonseca** [comment]
Sim, identificador do artigo.

-Gustavo

**Comment by asael-silva** [comment]
@gustavofonseca e @leticiaquino, apenas para confirmar, o termo 'documento' é citado mais de uma vez no arquivo elemento-article-id.rst. Todas as ocorrências serão padronizadas para 'artigo' invés de 'documento'? Desculpem-me ser tão chato, mas é melhor perguntar para evitar retrabalho.

**Comment by gustavofonseca** [comment]
@asael-silva estou olhando o arquivo em http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-article-id.html e não encontrei nenhuma ocorrência da palavra _documento_. Você está com olhando para a versão mais recente[1]?

[1]https://raw.githubusercontent.com/scieloorg/scielo_publishing_schema/editorial-rev/docs/source/tagset/elemento-article-id.rst

**Comment by gustavofonseca** [comment]
@asael-silva ah, agora vi que a solicitação da @leticiaquino usa o termo _documento_... o termo correto deveria ser _artigo_ mesmo.

**Comment by asael-silva** [comment]
@gustavofonseca, minha dúvida refere-se às várias ocorrências conforme imagem anexa. Nota: a tabela ainda não foi atualizada com o conteúdo solicitado que também contém a palavra 'documento'.
![elemento-article-id](https://cloud.githubusercontent.com/assets/3975885/17296702/e321295a-57d8-11e6-8c09-f29942d3c279.jpg)

**Comment by asael-silva** [comment]
Alterado para 'artigo'.
