### ISSUE TITLE
Sobre o tópico <article-meta>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#274]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-article-meta.html

Inserir o asterisco em palavras-chave e em counts

**Comment by asael-silva** [comment]
Alterado.

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 06:35:27 -0700

**Comment by asael-silva** [comment]
Este arquivo não tem exemplo mesmo?

**Comment by leticiaquino** [comment]
@asael-silva conforme já disse em outro momento, nós decidimos não inserir um exemplo de ```<article-meta>``` porque pode ficar confuso para muitos prestadores e editores, uma vez que os elementos de ```<article-meta>``` podem ser diferentes dependendo da modalidade do documento.
Esse tópico ficará sem exemplo.
