### ISSUE TITLE
Sobre o tópico <article-title>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#275]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-article-title.html

Em "Utilizado para identificar o título do artigo em ```<article-meta>```..." 
alterar para: "Utilizado para identificar o título do artigo em ```<title-group>```...".

Os exemplos 1 e 2 são exemplos de article-title em title-group.
Alterar o exemplo 2 para:

```xml
<element-citation publication-type="journal">
     ...
     <article-title>Framing processes and social movements: an overview and assessment</article-title>
     ...
</element-citation>
```

Alterar a última nota para:
Caso haja coincidência entre os títulos da seção e do artigo, a informação será marcada tanto em ```<article-categories>``` como em ```<article-title>```.

**Comment by asael-silva** [comment]
Alterado.

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 06:39:41 -0700
