### ISSUE TITLE
Sobre o tópico <attrib>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#276]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-attrib.html

**Substituir:**
"Descreve dados da fonte, autoria, agradecimentos, material de direitos autorais e outras informações. Geralmente se utiliza para especificar a fonte de origem de figuras e para identificar o autor de uma poesia ou verso."

**Para:**
Utilizado para creditar o autor ou o licenciador de ativos ou conteúdos que requerem tal atribuição

**Comment by asael-silva** [comment]
Alterado.

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 06:46:26 -0700
