### ISSUE TITLE
Sobre o tópico <author-notes>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#277]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-author-notes.html

**Alterar:**
“Identifica informações como: correspondência, contribuição igualitária, conflitos de interesse etc, ou seja, notas sobre o autor.”

**Para: **
Identifica notas relacionadas ao autor, tais como: correspondência, contribuição igualitária etc.

**Comment by asael-silva** [comment]
Alterado.

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 06:49:04 -0700
