### ISSUE TITLE
Sobre o tópico <award-group>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#278]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-award-group.html

Adicionar a seguinte nota:

O grupo de dados deve, obrigatoriamente, possuir o número de contrato e a instituição financiadora.

**Comment by asael-silva** [comment]
Adicionado.

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 06:54:13 -0700
