### ISSUE TITLE
Sobre o tópico <award-id>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#279]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-award-id.html

A informação "O nome da instituição é declarado no elemento ```<funding-source>```" não é interessante nesse tópico que fala a respeito do número de contrato.
Retirar.

**Comment by asael-silva** [comment]
Retirado.

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 06:56:28 -0700
