### ISSUE TITLE
Sobre o tópico <caption>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#280]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-caption.html

Alterar a informação: "```<caption>``` encerra ..." 
Para: "```<caption>``` envolve..."

A palavra "encerra" pode gerar confusão na leitura do texto.

**Comment by asael-silva** [comment]
Alterado.

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 07:10:06 -0700
