### ISSUE TITLE
Sobre o tópico <contrib-id>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#281]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-contrib-id.html

**Alterar:**
“O atributo @contrib-id-type é o tipo de identificador e possui os valores:”

**Para:**
“O atributo @contrib-id-type possui os seguintes valores:”

**Comment by asael-silva** [comment]
Alterado.

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 07:19:20 -0700
