### ISSUE TITLE
Sobre o tópico <contrib>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#282]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-contrib.html

@asael-silva Por favor, verificar a possibilidade de escrever melhor a frase abaixo, pois as pessoas tem entendido de forma errada.

"Identifica dados individuais, de grupo ou institucionais, de contribuintes do artigo, podendo ser inclusive anônimos."

**Em Nota, Alterar:**
"Em contrib o elemento <name> pode ou não ocorrer."
**Para:**
Em caso de autorias institucionais ou de grupos o elemento <name> não é requerido.

**Comment by asael-silva** [comment]
Letícia
como as pessoas tem entendido a frase mencionada? O que eu entendo seria algo como:
Identifica dados de contribuintes do artigo, quer sejam indivíduos, grupos de pesquisa ou instituições, podendo inclusive ser anônimos.
Você acha que fica mais claro?
Nota alterada.

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 07:23:48 -0700

**Comment by leticiaquino** [comment]
@asael-silva as pessoas estranharam o "institucionais" após grupo, pois dá a entender que seria grupo de "instituições".
Talvez se alterar a ordem fique melhor. Veja:

Identifica dados individuais, institucionais ou de grupo, de contribuintes do artigo, podendo ser inclusive anônimos.

**Comment by asael-silva** [comment]
Alterado para sua sugestão.
