### ISSUE TITLE
Excluir 2º parágrafo do tópico <copyright-statement>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#283]
Em http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-copyright-statement.html

Retirar o parágrafo:
`<copyright-statement>` e `<license-p>` são geralmente utilizados para exibição dessa informação.

**Comment by asael-silva** [comment]
Retirado.

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 07:27:20 -0700

**Comment by javani** [comment]
@leticiaquino já está correto no guia.

**Comment by leticiaquino** [comment]
Ticket Resolvido
