### ISSUE TITLE
Sobre o tópico <corresp>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#284]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-corresp.html

Na informação de Nota: "Para este elemento não é necessário utilizar parágrafo (```<p>```)."
Dizer que "não é necessário" dá a impressão de que é possível a inserção de ```<p>```. Por gentileza, alterar para:
Para este elemento não utilizar parágrafo (```<p>```).

**Alterar:**
“Elemento que concentra informação de correspondência de um autor do artigo”
**Para:**
Elemento que engloba dados de correspondência de um ou mais autore do artigo

**Comment by asael-silva** [comment]
Alterado.

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 07:35:59 -0700
