### ISSUE TITLE
Sobre o tópico <counts>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#285]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-counts.html

**Em nota alterar a frase:**
"No caso de haver ```<article>``` e ```<sub-article>```, deve-se contabilizar o total de elementos em ambos."

**Para:**
“No caso de haver ```<sub-article>``` e/ou ```<response>```, deve-se contabilizar o total de elementos em ambos.”

**Comment by asael-silva** [comment]
Alterado.

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 07:37:57 -0700
