### ISSUE TITLE
Sobre o tópico <date-in-citation>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#286]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-date-in-citation.html

Acrescentar a seguinte informação:

Os valores possíveis para o atributo ``@content-type`` são:
* update
* access-date

**Comment by asael-silva** [comment]
Alterado com adaptação.

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 07:40:40 -0700
