### ISSUE TITLE
Tópico <day>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#287]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-day.html

**Alterar a informação:**
 "Zero ou uma vez em ```<front>```" 
**para:** 
Zero ou uma vez nos elementos de ```<front>```

**e alterar:**
"Zero ou mais vezes em ```<back>```" 
**para:**
Zero ou mais vezes nos elementos de ```<back>```

**Comment by asael-silva** [comment]
Alterado.

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 07:42:12 -0700
