### ISSUE TITLE
Tópico <defi-list>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#288]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-def-list.html

Em "@id": inserir a informação "Ver sugestão de atribuição de ID"..
Retirar a informação "em" de "2. em sublista de definições:"

**Alterar:**
“```<def>```: Descrição, explicação da palavra ou frase em ```<term>```”
**Para:**
```<def>```: descreve, explica a palavra ou frase em ```<term>```.

**Comment by asael-silva** [comment]
Alterações realizadas.

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 07:47:15 -0700
