### ISSUE TITLE
Tópico <edition>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#289]
Relacionado ao: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-edition.html

**Alterar:**
“Identifica o número da edição de um documento em uma referência...”
**Para:**
Identifica a edição de um documento em uma referência...

**Comment by asael-silva** [comment]
Alterado.

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 07:52:09 -0700
