### ISSUE TITLE
Tópico <etal>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#290]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-etal.html

**Em nota alterar**
“Quando a informação aparecer no texto da referência…”:
**Para:**
Quando a informação aparecer em referência bibliográfica...

**Comment by asael-silva** [comment]
Alterado.

Asael C Silvagandhalf_thewhite@live.com



Date: Thu, 28 Jul 2016 07:59:27 -0700
