### ISSUE TITLE
Tópico <fn-group>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#291]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-fn-group.html

Alterar:"...que não representam notas de autor, as quais devem ser identificadas com ```<author-notes>```. "
Para:  que estão relacionadas com o documento como um todo, não confundir com notas de rodapé relacionadas ao autor.

**Alterar:**
"Este elemento pode possuir..."
**Para:**
Este elemento pode apresentar...

**Comment by asael-silva** [comment]
Alterado.
