### ISSUE TITLE
Tópico <fpage>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#293]
Relacionado ao docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-fpage.html

**Alterar a informação:**
"Este elemento também pode ser utilizad**a**..."
**Para:**
Este elemento também pode ser utilizad**o**...

**Comment by asael-silva** [comment]
Alterado.
