### ISSUE TITLE
Tópico <front-stub>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#294]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-front-stub.html

@asael-silva pensamos em incluir uma nota mais ou menos assim:

“Em caso de tradução de afiliação e notas de autor, os autores devem ser replicados para correta referência cruzada entre os elementos.”

Você pode verificar e escrever essa ideia de maneira que fique mais claro?

**Comment by asael-silva** [comment]
Se eu entendi bem, a nota diz que:

Caso ocorram *tradução de afiliação* e/ou *notas de autor*, os dados destes autores devem ser duplicados para permitir uma referência cruzada entre os elementos do artigo original e do artigo traduzido.

É isso?

**Comment by javani** [comment]
@asael-silva @leticiaquino @gustavofonseca 

Na verdade é para permitir a referência cruzada entre autor(es) e afiliação e notas apenas no artigo traduzido. 
Acredito que fique melhor:

Caso ocorram tradução de afiliação e/ou notas de autor, os dados destes autores devem ser duplicados em <front-stub> para permitir uma referência cruzada entre os elementos no artigo traduzido.

**Comment by asael-silva** [comment]
Alterado.
