### ISSUE TITLE
Tópico <institution>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#295]
Relacionado ao  http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-institution.html

**Alterar:** 
"Identificar a afiliação completa..."
**Para:** 
Identifica a afiliação completa

Sugestão: ao invés de “instituição do autor”, “instituição de afiliação do autor”

**Comment by asael-silva** [comment]
Alterado.
