### ISSUE TITLE
Tópico <isbn>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#296]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-isbn.html

**Alterar a frase:**
“Contém o ISBN de um livro e é identificado em uma referência ou produto.”
**Para:**
“Identifica o ISBN em uma referência bibliográfica ou produto.”

**Comment by asael-silva** [comment]
Alterado.
