### ISSUE TITLE
Tópico <journal-id>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#297]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-journal-id.html

@asael-silva Precisamos acrescentar a informação de que o valor "publisher-id" é obrigatório e pensamos na frase que segue abaixo. Entretanto não parece muito clara. Você consegue melhorar isso?

**Em:**
"Contém o identificador único do periódico indexado em uma base de dados ou instituição publicadora."

**Acrescentar a seguinte informação:**
"... instituição publicadora. Minimamente o acrônimo do periódico deve ser identificado por meio do valor "publisher-id" ."

**Comment by asael-silva** [comment]
@leticiaquino , não sei se reflete o que desejam. Acrescentei ao final do parágrafo de descrição o texto abaixo:

É obrigatório ter ao menos uma ocorrência de ``<journal-id>`` com o valor cravado ``publisher-id`` no atributo ``@journal-id-type``. Nesta ocorrência deve ser identificado o acrônimo do periódico.

**Comment by javani** [comment]
@asael-silva está muito bom. Apenas tiraria o cravado.
@leticiaquino

**Comment by asael-silva** [comment]
Alterado.
