### ISSUE TITLE
Tópico <permissions>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#298]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-permissions.html

**Alterar:** 
"...que elementos apresentam ```<permissions>```..."
**Para:** 
quais elementos podem apresentar ```<permissions>```

Inserir link na lista de exemplos.

**Comment by asael-silva** [comment]
Texto alterado. @gustavofonseca você poderia olhar o arquivo na parte de link para os exemplos. Segui o que fizemos anteriormente, mas aparentemente não funcionou.

**Comment by gustavofonseca** [comment]
@asael-silva posso sim.

**Comment by asael-silva** [comment]
@gustavofonseca, funcionou? qual era o problema?

**Comment by gustavofonseca** [comment]
Resolvido no commit 1fe3a7b.

O problema é que os pontos de ancoragem não eram seções do texto.

**Comment by asael-silva** [comment]
Como assim? Eu comparei com o elemento-app e parecia ter sido feito igual. Ainda não consegui entender.

**Comment by gustavofonseca** [comment]
Veja o diff: https://github.com/scieloorg/scielo_publishing_schema/commit/1fe3a7b33745523e98d8bbaa8adff7a4690c572e#diff-9a41211ca9b382889f92fa31b26a94ff

-Gustavo

**Comment by asael-silva** [comment]
Gustavo, por favor, você pode ser menos técnico comigo e dizer claramente qual o problema? Já disse que não consigo ver onde é. Pode me explicar textualmente?

**Comment by gustavofonseca** [comment]
Claro. O problema é que apenas títulos de seção podem se tornar âncoras. A solução foi adicionar sequências de hífens nas linhas imediatamente abaixo dos textos que deveriam ser títulos.  

![screen shot 2016-08-19 at 18 47 20](https://cloud.githubusercontent.com/assets/161335/17825254/6fe7cb38-663d-11e6-905d-aa1ef92e26f9.png)
