### ISSUE TITLE
Tópico <person-group>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#299]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-person-group.html

**Alterar:**
"somente devem ser identificad**a**s"
**Para:**
"somente devem ser identificad**o**s"

**Comment by javani** [comment]
@leticiaquino já está correto na documentação. Há algo mais a ser feito?

**Comment by leticiaquino** [comment]
Ticket Resolvido
