### ISSUE TITLE
Tópico <pub-date>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#300]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-pub-date.html

Inserir um exemplo de publicação de epub-ppub com informação de ```<month>```
Acrescentar na documentação que o formato em ```<pub-date>``` de "epub" deve ser utilizado em 3 situações:

1- Quando o periódico publica apenas online;
2- Quando trata-se de um documento Rolling Pass; e
3- Quando trata-se da modalidade Ahead Of Print;

```xml
<pub-date pub-type="epub">
     <day>21</day>
     <month>07</month>
     <year>2016</year>
</pub-date>
```

**Comment by asael-silva** [comment]
Informação incluída com adaptação e exemplo adicional inserido.
