### ISSUE TITLE
Tópico <publisher-name>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#301]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-publisher-name.html

**Alterar:** 
"Representa o nome da casa publicadora ou editora numa referência."
**Para:** 
"Representa o nome da casa publicadora ou editora."

Isso porque o elemento ```<publisher-name>``` não ocorre apenas em referências, mas também em ```<publisher>``` de ```<journal-meta>```.

**Comment by asael-silva** [comment]
Alterado.
