### ISSUE TITLE
Tópico <related-article>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#303]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-related-article.html

Retirar toda a informação a partir de "Para Errata o elemento ```<related-article>``` deve..." até "Exemplo:".

**Comment by asael-silva** [comment]
Excluído texto. Não há exemplo.

**Comment by leticiaquino** [comment]
@asael-silva concordamos que esse tópico não apresentará exemplo, pois em ```<related-article>``` não há atributos "fixos",  as possíveis maneiras de utilizar o ```<related-article>``` podem ser vistas em Errata e Artigo comentado.

**Comment by asael-silva** [comment]
OK. Então vou retirar o título de seção 'Exemplo' do texto.

**Comment by leticiaquino** [comment]
@asael-silva ok.
