### ISSUE TITLE
Tópico <season>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#304]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-season.html

**Em:**
"Este elemento pode ser encontrado em ```<front>``` (ver ```<pub-date>``` e ```<product>```) para identificação de intervalo de meses do ano ou em ```<back>```, representando informações das estações do ano em um referência."

**Alterar para:**
Este elemento pode ser encontrado em ```<pub-date>``` para identificação de intervalo de meses do ano (Ver nota informativa) e em ```<element-citation>``` e ```<product>``` para identificação de estação do ano em uma referência;

**Comment by asael-silva** [comment]
Alterado.
