### ISSUE TITLE
Rever a estrutura da Documentação Narrativa

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#305]
Relacionado a http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/index.html#documentacao-narrativa

@asael-silva rever a estrutura de documentação narrativa.

e após isso, inserir um link no elemento `<subj-group>` que remete à documentação narrativa.

**Comment by asael-silva** [comment]
@leticiaquino , não entendi que tipo de revisão você deseja. Esta seção é composta de cinco arquivos que explicam características que não puderam ser incluídas individualmente em tagset (até onde entendi). Não saberia reestruturar algo cujo conteúdo não domino. Por favor, seja um pouco mais explícita em relação a esta questão.

**Comment by gustavofonseca** [comment]
A documentação está dividida basicamente em 2 partes: 1) referencial, onde são descritos os elementos, seus usos e restrições e, 2) narrativa, onde descrevemos alguns casos de uso. Então se, por exemplo, você deseja produzir um documento que é composto por um artigo original seguido por outro artigo representando um comentário do editor, a documentação narrativa deveria te dizer qual estrutura é previsa para esse caso de uso e ainda apontar para a referência dos elementos envolvidos. 

O problema é que nós nos perdemos um pouco na maneira de organizar essa seção narrativa. Algumas coisas foram dispostas como perguntas frequentes, outras não...

Gostaríamos que você sugerisse uma estrutura mais coesa.

**Comment by asael-silva** [comment]
Entendi agora. Vou perguntar a vocês algo que não ficou claro pra mim, mesmo que pareça simplório.
Se há um schema que define os elementos, atributos e hierarquias, deveria ser possível descrever em cada elemento além de sua definição, requisitos, hierarquia e exemplos, os casos específicos de uso e as interações com outros elementos, algo tipo: casos especiais (que eu acredito seja o conteúdo de narrativos).
Dessa forma, sempre que algum elemento fosse alterado, através do próprio texto do elemento já seria possível identificar que outros elementos relacionados deveriam sofrer também revisão.
Obviamente, seria necessário reescrever algum conteúdo para que ficasse adequado a cada entrada referencial (por elemento), mas a documentação ficaria clara.
Outra possibilidade é indicar (através de link) nos elementos a localização da informação adicional e mante-la segmentada como vocês fizeram (exige menor esforço).
O caso do apontamento ocorreria facilmente com os arquivos aheadofprint, artigo-comentado e errata. Os arquivos caracteres e regra-nomeacao são mais genéricos e poderiam ser alocados a partir do index para outra posição no texto (por exemplo, na introdução dos elementos) evidenciando assim que é primordial saber as regras de nomenclatura para arquivos, diretórios, bem como tabelas de codificação, caracteres especiais, etc.
Não sei se fui claro na colocação.

**Comment by leticiaquino** [comment]
@asael-silva não entendi muito bem o que você quis dizer nessa parte:  "Dessa forma, sempre que algum elemento fosse alterado..." 
Você pode explicar melhor sua sugestão?

**Comment by gustavofonseca** [comment]
@asael-silva você sugere relacionar de alguma maneira, tipo por hiperlink ou embutimento de textos, o conteúdo referencial (tagset) e a descrição dos casos de uso (narrativa) daquele elemento. Se sim, eu penso que o modelo que estamos utilizando -- separação entre referencial e narrativa --  seja mais escalável pois trata-se de uma relação M para N (1 elemento pode se relacionar com N casos de uso, e 1 caso de uso pode se relacionar com M elementos).

**Comment by asael-silva** [comment]
@gustavofonseca a idéia do link é apenas para conectar o que já está como documentação narrativa aos elementos aos quais ela se refere. O outro caso seria uma reescritura, tomando por base a perpectiva de determinado elemento, ou seja, somente iriam ser reportados em 'casos especiais' informações relativas aquele elemento. Aumentaria a necessidade de revisão, mas tornaria a documentação sobre um elemento mais clara.
Se vocês querem manter a documentação como narrativa, não posso ajudar em reestruturá-la porque depende de conceitos técnicos da SciELO PS que desconheço. Não sei, por exemplo, como ela é utilizada pelo usuário.
Porque vocês não lançam um Survey para perguntar aos usuários do sistema se eles acham que a informação está clara e que mudanças eles sugeririam? Pode ser interessante ver o ponto de vista extern, uma vez que vocês conhecem a parte técnica profundamente.

**Comment by leticiaquino** [comment]
Ticket Resolvido.
