### ISSUE TITLE
Tópico <title-group>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#307]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-title-group.html

Inserir uma nota informando que fica abaixo de ```<article-categories>``` ou antes de ```<contrib-group>```

**Comment by asael-silva** [comment]
Nota incluida. Não possui exemplo.

**Comment by leticiaquino** [comment]
@asael-silva sim, está certo. 
Considerar apenas o solicitado no ticket.
