### ISSUE TITLE
Tópico <trans-abstract>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#308]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-trans-abstract.html

A concordância deveria ser inserido e não inserida, porque se refere ao resumo:
“....Se existente, deve ser inserido imediatamente após ```<abstract>``` e, obrigatoriamente, conter o atributo @xml:lang.”

Adicionar a seguinte nota:

Caso o artigo tenha versão(ões) traduzida(s), ```<trans-abstract>``` não deve ser inserido, exceto nos casos em que haja resumos traduzidos diferentes da(s) tradução(ões) disponíveis em ```<sub-article>```

**Comment by asael-silva** [comment]
Alterado e adicionado.
