### ISSUE TITLE
Tópico <trans-title-group>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#309]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-trans-title-group.html

Inserir a seguinte nota:

Caso o artigo tenha versão(ões) traduzida(s), ```<trans-title-group>``` não deve ser inserido, exceto nos casos em que haja títulos traduzidos diferentes da(s) tradução(ões) disponíveis em ```<sub-article>```

**Comment by asael-silva** [comment]
Inserida. Não possui exemplo.

**Comment by leticiaquino** [comment]
@asael-silva está ok. Considerar apenas o solicitado no ticket.
