### ISSUE TITLE
Tópico <volume>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#310]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-volume.html

 “Caso haja suplemento de volume em ```<front>```, este deve ser identificado em ```<issue>```.”
Acho que pode confundir “Caso haja suplemento de volume em ```<front>```”, porque o suplemento é do fascículo, não do front. 
Mudar a vírgula de lugar pode evitar uma má interpretação. Considerar então:
“Caso haja suplemento de volume,  este deve ser identificado em ```<issue>``` em ```<front>``` .”

Inserir uma nota informando que ```<volume>``` depois de ```<pub-date>``` ou antes de ```<issue>```.

**Comment by asael-silva** [comment]
Alterado texto e inserida nota.
