### ISSUE TITLE
Tópico <xref>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#311]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-xref.html

Está confuso o “contém o identificador do artigo referenciado”. Aqui não está faltando a palavra “elemento”?. Ficaria:
@rid: contém o identificador do elemento do artigo referenciado, perfazendo assim o link entre a origem (``@rid``) e o destino (``@id``) no texto.
O valor e descrição estão na mesma célula, a tabela está mal formatada:
boxed-text | caixa de texto

**Comment by asael-silva** [comment]
Alterado.
