### ISSUE TITLE
Tópico Sobre Sugestão de Atribuição de @ID

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#312]
Relacionado ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/sugestao-atribuicao-id.html

No elemento “supplementary-material” a descrição está “Suplemento”, no link da tag <xref>, a descrição para o mesmo elemento é “material suplementar”. Sugiro manter a mesma descrição nas duas tags, preferencialmente material suplementar.

Acho que na descrição do elemento “author-notes/fn | fn-group/fn” poderia ser adicionada a descrição “notas de autor”, ficando assim: “notas de autor|Nota de rodapé do artigo”

Na descrição do elemento  “disp-formula” está “Equação”, no link da tag <xref>, a descrição para o mesmo elemento é “fórmula”. Sugiro manter a mesma descrição nas duas tags, podendo ser misturada as duas “Equação|fórmula” 

Incluir os seguintes elementos na tabela: inline-graphic e inline-supplementary-material

Elemento XML                            | Descrição                                  | Prefixo | Exemplo
-----------------------------------|-----------------------------------|---------|-----------------------
inline-graphic                             | Imagens em linha                     | i           | i1, i2,...
inline-supplementary-material  | Material Suplementar em linha | suppl   |      suppl1, suppl2,...

**Comment by asael-silva** [comment]
@leticiaquino, o primeiro parágrafo eu consegui localizar onde alterar. Do segundo pra frente está confuso para mim que arquivos e que alterações realizar. Você está indicando mais de um arquivo? Combinamos que iria ser individualizado, não?

**Comment by leticiaquino** [comment]
@asael-silva me refiro a descrição da tabela de sugestão de atribuição de Ids. Veja os exemplos "circulados" na imagem abaixo:

![img-guia-revisao](https://cloud.githubusercontent.com/assets/4397365/17298602/00d811f4-57e1-11e6-8bc4-e1fe381c158a.jpg)

Na coluna "Descrição" em vez de "Nota de rodapé do artigo"
inserir: Notas de autor|Nota de rodapé do artigo

Na coluna "Descrição" em vez de "Equação"
inserir: Equação|fórmula

Ainda na tabela de sugestão de atribuição de ids, inserir os exemplos de inline-graphic e inline-supplementary-material, conforme descritos na tabela apresentada.

**Comment by asael-silva** [comment]
Dados alterados e itens incluídos.
