### ISSUE TITLE
Tópico Glossário

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#313]
Relacionao ao http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/glossary.html
- **PubMed Central** - "PubMed Central (PMC) é um repositório digital de uso livre em que se armazenam artigos eruditos completos de acesso público que foram publicados em revistas científicas das ciências da vida e biomédicas. É uma das maiores bases de dados de pesquisa no conjunto de recursos que foram desenvolvidos pelo National Center for Biotechnology Information (NCBI) de Estados Unidos, mas é muito mais que um simples repositório de documentos." https://pt.wikipedia.org/wiki/PubMed_Central
- **PubMed** - "PubMed é um motor de busca de livre acesso à base de dados MEDLINE de citações e resumos de artigos de investigação em biomedicina. Oferecido pela Biblioteca Nacional de Medicina dos Estados Unidos como parte de Entrez." https://pt.wikipedia.org/wiki/PubMed
- **RST** - "reStructuredText é uma linguagem de marcação para leitura de formatos de código fonte. O reStructuredText é um componente do framework Docutils para processamento de texto, implementado em linguagem de programação Python." https://pt.wikipedia.org/wiki/ReStructuredText
- **StyleChecker** - Ferramenta baseada na web que apresenta relatório detalhado sobre a conformidade de um dado XML em relação à especificação SciELO PS.
- **Unicode** - "Unicode é um padrão que permite aos computadores representar e manipular, de forma consistente, texto de qualquer sistema de escrita existente." https://pt.wikipedia.org/wiki/Unicode
- **SciELO Manager** - SciELO Manager (http://manager.scielo.org) é o software responsável pela gestão dos catálogos de periódicos da rede SciELO.
- **Declaração do XML** - é a instrução que identifica o documento como sendo um XML.

No termo ISSN, no destaque a seguir, seria uma vírgula e não ponto final:
“International Standard Serial Number - é um código numérico que constitui um identificador unívoco para cada título de publicação em série.cujos componentes não têm um…”

No termo Pacotes SciELO PS, achei meio confuso a parte em destaque (a seguir), da a entender que o pacote deve conter apenas 1 arquivo, quando pode conter mais. 
Portanto, alterar:
“Pacote no formato .zip que representa um artigo e todos os seus ativos estáticos. Deve conter apenas 1 arquivo XML, conforme a especificação SciELO Publishing Schema…”

Para: Pacote no formato .zip deve conter arquivos XML e os respectivos ativos digitais.

**Comment by asael-silva** [comment]
@leticiaquino, conforme havia informado @gustavofonseca, há um texto 'PAREI AQUI' indicando que dali para baixo ainda não havia revisado.
Também recordo que foi combinado que não iriamos utilizar wikipedia em português pelo fato da mesma não possuir a relevância e seriedade dos revisores como ocorre com a versão em inglês, sendo entretanto preferível a descrição dos termos a partir de instituições e/ou empresas detentoras da tecnologia/metodologia sendo descrita. Eu particularmente não confio em toda informação da wikipedia em português e as instituições de ensino sugerem utilizá-la como referência primária para chegar às fontes corretas. Podemos manter nessa linha? 
Em relação ao item 'Pacotes SciELO' reproduzo a definição abaixo constante do arquivo enviado e diferente da que você citou:
"Arquivos de computador no formato *.zip*, cada um representando um único artigo e todos os seus ativos estáticos. Deve conter apenas um arquivo :term:`XML`, de acordo com a especificação :term:`SciELO Publishing Schema`, referente ao texto completo."
Primeiramente, li o texto original de onde partiu minha a revisão.
O que eu entendo pelo texto acima é que os pacotes SciELO PS são arquivos em formato ZIP, sendo que cada 'arquivo zip' representa um único artigo e todos seus ativos estáticos (figuras, fotos, multimidia etc), porém contém apenas um arquivo XML (texto completo de um artigo) por arquivo ZIP de acordo com a tal especificação. O que você está me dizendo é que pode haver mais de um XML por arquivo ZIP?

**Comment by asael-silva** [comment]
@leticiaquino gostaria de uma resposta às minhas dúvidas.

**Comment by leticiaquino** [comment]
> leticiaquino, conforme havia informado gustavofonseca, há um texto 'PAREI AQUI' indicando que dali para baixo ainda não havia revisado.

Asael, conforme comentamos com você a equipe revisou o guia completo, inclusive o glossátio. Ainda que você não tenha revisado, há algumas sugestões de texto para os termos que estavam sem descrição e também para os que estavam já com alguma descrição.

> Também recordo que foi combinado que não iriamos utilizar wikipedia em português pelo fato da mesma não possuir a relevância e seriedade dos revisores como ocorre com a versão em inglês, sendo entretanto preferível a descrição dos termos a partir de instituições e/ou empresas detentoras da tecnologia/metodologia sendo descrita. Eu particularmente não confio em toda informação da wikipedia em português e as instituições de ensino sugerem utilizá-la como referência primária para chegar às fontes corretas. Podemos manter nessa linha?

Asael, vamos discutir internamente e em breve darei uma resposta

> Em relação ao item 'Pacotes SciELO' reproduzo a definição abaixo constante do arquivo enviado e diferente da que você citou:
"Arquivos de computador no formato .zip, cada um representando um único artigo e todos os seus ativos estáticos. Deve conter apenas um arquivo :term:XML, de acordo com a especificação :term:SciELO Publishing Schema, referente ao texto completo."
Primeiramente, li o texto original de onde partiu minha a revisão.
O que eu entendo pelo texto acima é que os pacotes SciELO PS são arquivos em formato ZIP, sendo que cada 'arquivo zip' representa um único artigo e todos seus ativos estáticos (figuras, fotos, multimidia etc), porém contém apenas um arquivo XML (texto completo de um artigo) por arquivo ZIP de acordo com a tal especificação. O que você está me dizendo é que pode haver mais de um XML por arquivo ZIP? 

Sim, se no guia sem sua revisão estava informando que em cada ZIP deve haver somente 1 arquivo XML, então no guia estava incorreto.
A regra é que no ZIP deve estar todos os arquivos XML do número com seus respectivos PDF e ativos digitais.
ou seja, é possível ter 1 ou mais XML com seus respectivos PDFs e ativos digitais.

E @asael-silva , geralmente há mais que 1.

**Comment by asael-silva** [comment]
Definição alterada.

**Comment by asael-silva** [comment]
@leticiaquino @gustavofonseca aguardando suas considerações sobre a questão de não usar a wikipedia  em português, prefererindo as instituições e/ou empresas detentoras do copyright de tecnologia envolvido.

**Comment by gustavofonseca** [comment]
Nós realmente haviamos combinado de não usar a wikipedia em português, mas aparentemente eu falhei em fazer com que todos soubessem ou respeitassem o combinado. Como a @leticiaquino está mais familiarizada com esses termos, acho que ela está em uma posição melhor do que a minha para dizer o que fazer.

**Comment by leticiaquino** [comment]
Ticket Resolvido.
