### ISSUE TITLE
Continuação tópico Glossário

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#314]
Relacionado ao

Faltou incluir a seguinte definição do termo Metodologia SciELO:

* **Metodologia SciELO** - A Metodologia SciELO permite a publicação eletrônica de edições completas de periódicos científicos, a organização de bases de dados bibliográficas e de textos completos, a recuperação de textos por seu conteúdo, a preservação de arquivos eletrônicos e a produção de indicadores estatísticos de uso e impacto da literatura científica. A Metodologia também inclui critérios de avaliação de revistas, baseado nos padrões internacionais de comunicação científica. Os textos completos são enriquecidos dinamicamente com links de hipertexto com bases de dados nacionais e internacionais, como por exemplo, LILACS e MEDLINE. <www.scielo.org/php/level.php?lang=pt&component=56&item=1>

**Comment by asael-silva** [comment]
Este trecho eu preferi não incluir para não ter de abrir dois novos termos de glossário para LILACS e MEDLINE, que seria o correto, mas estou incluíndo conforme solicitado.
