### ISSUE TITLE
Inserir link: aheadofprint.rst

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#315]
Em: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/narr/aheadofprint.html

Inserir link na palavra **Ahead Of Print** em:
“Para artigos publicados no formato **Ahead of Print**(aqui inserir o link para glossário) (AOP), para @article-type incluir o tipo de documento “research-article” e em "//subj-group[@subj-group-type="heading"]/subject, Articles.“

**Comment by asael-silva** [comment]
Texto alterado, porém no meu arquivo consta como abaixo:

"Todos os arquivos :term:`ahead of print` (AOP) devem apresentar o valor ``research-article`` em ``@article-type`` e em ``//subj-group[@subj-group-type="heading"]/subject`` inserir o texto ``Articles``."

**Comment by leticiaquino** [comment]
:warning: esse ticket não apresenta label "Revisão editorial do guia"

**Comment by leticiaquino** [comment]
Resolvido.
