### ISSUE TITLE
Correção em exemplo de errata

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#316]
Em http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/narr/errata.html

Corrigir exemplo de `<fn-group>`.
Alterar:
`<title>` Erratum `</title>`
Para:
`<label>` Erratum `</label>`

**Comment by asael-silva** [comment]
Alterado.

**Comment by leticiaquino** [comment]
:warning: esse ticket não apresenta label "Revisão editorial do guia"

**Comment by leticiaquino** [comment]
Estamos avaliando a possibilidade de aceitar em ```<fn-group>``` o ```<label>```e ```<title>```.

**Comment by RPostalli** [comment]
A alteração só para label corrige o problema de documentar errado o title em fn, mas não resolve o problema de diferenciar o título "Errata" solicitada pelo Abel. #251
