### ISSUE TITLE
Em Regra de nomeação incluir exemplo de outras modalidades

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#317]
Em "[Nomeação de Pasta para Envio](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/narr/regra-nomeacao.html)" Inserir o modelo de nomeção para: Rolling Pass, Fascículo de número, de Suplemento e de Número Especial. Talvez reorganizar isso tudo em uma tabela fique, visivelmente, melhor.
Relacionado ao #210

Tenho aqui uma sugestão da Isa (equipe de conversão) complementando a sugestão de exemplo de Rolling Pass:
       
> Temos um problema com os arquivos que são enviados em forma de LOTES (Ahead Of Print e Rolling-Pass).
Na documentação está informando que para Ahead of print considerar:
  ISSN-acronimo-lote

>Com isso teríamos problemas com os lotes de Rolling Pass:
  ISSN-acronimo-lote (Também)

>Pensando não só no FTP automático, mas também na organização das nossas tarefas, as pastas enviadas pelo prestador e editor poderiam ser nomeadas da seguinte maneira:

>Ahead of print:

> ISSN-acronimo-nahead-lote

>Ex.: 1807-2577-rounesp-nahead-0916

>Rolling Pass:
Periódico que publica em um único volume ao ano:
  ISSN-acronimo-rpass-lote

>Ex.: 1678-4766-isz-rpass-0116

> Periódico que publica vários volumes ao ano:
  ISSN-acronimo-rpass-lote-volume-número

> Ex.: 1414-431X-bjmbr-rpass-02-49-7

> Obs.: O lote, tanto para Ahead Of Print quanto para Rolling Pass, é composto pelo número do pacote (01, 02...12,13 etc) + os 2 (dois) dígitos finais do ano corrente.

> Esse tipo de nomeação é na verdade utilizada já no serial e para o cadastramento dos arquivos na PTS ( no caso da PTS sem o ISSN e o separadores " iszrpass0116 "), porém a equipe da conversão que tem que criar essa pastinha, pois as prestadoras e editores não seguem a regra da documentação. 

Exemplos de publicação de Número, Suplemento e Número Especial:
**Fascículo de número**
     issn-acronimo-numero
     ex.: 2316-9141-rh-174

**Número especial**
     issn-acronimo-volume-spe + nº de ordem
     ex.: 2175-7968-ct-36-spe1

**Suplemento**
     issn-acronimo-volume-s + Nº de ordem
     ex.: 1678-2690-aabc-88-s1

Em **Arquivo XML:**
Inserir um exemplo de Rolling Pass, de Fascículo de número, número especial e suplemento
Abaixo segue os exemplos:

Tipo                            | Exemplo prático:                                              | Modo de composição
-----------------------------|----------------------------------------------------------------|-----------------------------------------------------------
Rolling Pass               |  1414-431X-bjmbr-1414-431X20165281.xml|(issn-acronimo-nº de DOI sem prefixo.xml)
Fascículo de número|1517-7599-pm-34-0001.xml                             |(issn-acronimo-numero-1ªpagina.xml)
Número especial       |2175-7968-ct-36-spe1-0009.xml                      |(issn-acronimo-volume-spe +nº de ordem-1ªpagina.xml)
Suplemento               |1678-2690-aabc-88-s1-00437.xml                   |(issn-acronimo-volume-s+nº de ordem-1ªpagina.xml)

**Comment by asael-silva** [comment]
@leticiaquino, não entendi exatamente o que vocês querem que eu inclua. Há discussão misturada com texto e exemplos. Seriam só os exemplos a partir de "Exemplos de publicação de Número, Suplemento e Número Especial". Outra coisa, onde exatamente deve ser colocado o texto.

**Comment by leticiaquino** [comment]
@asael-silva note que esse ticket não apresenta o label "Revisão editorial do guia".

Por favor, revisar apenas os tickets que apresentam esse label. Caso não tenha mais o link, envio abaixo o link filtrado pelo label "Revisão editorial do guia":

https://github.com/scieloorg/scielo_publishing_schema/labels/Revis%C3%A3o%20editorial%20do%20guia

**Comment by RPostalli** [comment]
Lembrete: Segundo o Abel a forma correta de mencionar modalidade Rolling Pass é: ***Publicação Contínua***, não incluir o termo RPass no Guia.
