### ISSUE TITLE
Inserir elementos em "Aparece em" do tópico <back>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#318]
Em: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-back.html

Completar o dado em “aparece em”:

Aparece em:
* ```<article>``` 
* ```<sub-article>``` 
* ```<response>```

**Comment by asael-silva** [comment]
Alterado.

**Comment by leticiaquino** [comment]
:warning: esse ticket não apresenta label "Revisão editorial do guia"
