### ISSUE TITLE
Alterar informação em parágrafo de <body>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#319]
Em http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-body.html

A meu ver a nota "Tabelas, figuras e equações que não estejam identificadas sob ```<app-group>``` devem ser inseridas obrigatoriamente após a primeira chamada no texto. Para material suplementar, analisar e identificar caso a caso." deve ser inserida nos tópicos: figura, tabela, equação etc, em vez de ```<body>```.

No parágrafo "Compreende todo o conteúdo formal de desenvolvimento do artigo científico, ou seja texto, imagens, tabelas, figuras, gráficos, equações, fórmulas etc." 
Alterar a seguinte informação “...texto, imagens, tabelas, figuras, gráficos, equações, fórmulas etc.”
Para:
... texto, seções, subseções, imagens, tabelas etc.

**Comment by asael-silva** [comment]
@leticiaquino , o primeiro parágrafo sobre a nota, significa excluí-la do elemento ``<body>`` e incluí-la em quais elementos? Por favor, liste e identifique se é após a descrição ou ao final dos exemplos em cada caso.
O segundo parágrafo foi alterado.

**Comment by leticiaquino** [comment]
@asael-silva esse ticket não foi marcado com o label "Revisão editorial do guia". 
Por favor, verificar apenas os tickets do link enviado.

**Comment by leticiaquino** [comment]
Discutimos em grupo e decidimos manter a nota em ```<body>```, mas também em cada elemento.
