### ISSUE TITLE
Incluir elemento em "Aparece em" de <caption>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#320]
Em: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-caption.html

Em “aparece em” incluir boxed-text

**Comment by asael-silva** [comment]
Alterado.

**Comment by leticiaquino** [comment]
:warning: esse ticket não apresenta label "Revisão editorial do guia"
