### ISSUE TITLE
Incluir elemento em "aparece em" de <comment>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#321]
Em: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-comment.html

Incluir em “Aparece em” o elemento ```<product>```.

**Comment by asael-silva** [comment]
Incluído.

**Comment by leticiaquino** [comment]
:warning: esse ticket não apresenta label "Revisão editorial do guia"

**Comment by leticiaquino** [comment]
Ticket inválido. Para a versão 1.5 o elemento ```<product>```não será detalhado.
