### ISSUE TITLE
Incluir elemento em "Aparece em" de <contrib-group>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#325]
Em "Aparece em" incluir o elemento: ```<front-stub>```.

Retirar o elemento ```<collab>```, pois foi definido que ```<collab>``` ocorre obrigatoriamente dentro de ```<contrib>```.

**Comment by asael-silva** [comment]
Alterado.

**Comment by leticiaquino** [comment]
:warning: esse ticket não apresenta label "Revisão editorial do guia"
