### ISSUE TITLE
Incluir elemento em "Aparece em:" de <chapter-title> e alterar regra de ocorrência

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#329]
Em: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-chapter-title.html

Em “Aparece em” incluir ```<product>```.

Se estamos falando no contexto de uma referência, ela ocorre zero ou uma vez. Por regra se cita apenas um capítulo de livro por referência.

**Comment by asael-silva** [comment]
Alterado.
