### ISSUE TITLE
Alterar informação de "Aparece em" do elemento <etal>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#332]
Em: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-etal.html

Alterar:
    Aparece em: ```<person-group>```, ```<product>```
    Para : ```<person-group>```

Isso porque tanto em ```<element-citation>``` quanto em ```<product>``` é obrigatório identificar autores em ```<person-group>```.

**Comment by asael-silva** [comment]
Alterado.

**Comment by leticiaquino** [comment]
Não alterar. Foi decidido manter detalhamento em ```<product>```quando for book-review
