### ISSUE TITLE
Alteração e inclusão de elementos em <fig>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#334]
Em: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-fig.html

* Organizar os elementos de ```<fig>``` em lista, conforme foi feito para o elemento ```<app>```.

* Verificar problema na formatação do texto:
![img-tk-docs](https://cloud.githubusercontent.com/assets/4397365/17293770/be28780c-57c8-11e6-882b-a07074127fbe.jpg)

* Em: "Dentro de```<fig>``` serão identificados o rótulo da figura (```<label>```) e a legenda (```<caption>```) com o título da figura em ```<p>```."
O correto seria:  **com o título da figura em ```<title>```**

* Incluir em "Aparece em" o elemento ```<boxed-text>```

* Em “Aparece em” alterar: ```<fig>```
Para: ```<fig-group>```

**Comment by asael-silva** [comment]
Alterações realizadas.
