### ISSUE TITLE
Incluir exemplo em <funding-group>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#336]
Em: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/editorial-rev/tagset/elemento-funding-group.html

Exemplo:

```xml
<funding-group>
     <award-group>
          <funding-source>CNPQ</funding-source>
          <award-id>12345</award-id>
     </award-group>
</funding-group>
```
Em nota acrescentar: … ou depois de ```<kwd-group>``` (já que counts pode não existir).

**Comment by asael-silva** [comment]
Alterado.
