### ISSUE TITLE
Reavaliar a restrição de tags de formatação nos elementos filhos de *//ref/element-citation*

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#36]
O elemento `<element-citation>`[1], apresenta a seguinte restrição:

```
Nunca manter uma informação toda com formatação <italic>, <bold>, etc, dentro de alguma tag;
```

I.e., os elementos filhos de `//ref/element-citation` devem possuir no mínimo 1 caractere em seu _text()_. 
Entretanto, uma mensagem na lista _scielo-xml_[2] sugere um caso de uso onde essa restrição se torna um problema quando partindo do XML Publishing (SciELO PS) deseja-se produzir um PDF (ou outro formato final), mantendo as características originais de formatação.

[1]http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.1-branch/tagset.html#element-citation
[2]https://groups.google.com/forum/#!topic/scielo-xml/naaeqi64KoQ

**Comment by javani** [comment]
Relacionado #219
