### ISSUE TITLE
Aceitar <title> e <label> ao mesmo tempo dentro de <ref-list>

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/scielo_publishing_schema#372]
Avaliar a possibilidade de ter `<title>` e `<label>` ao mesmo tempo dentro de `<ref-list>`.
Como hoje não é previsto `<title>` e `<label>` juntas em `<ref-list>`, a única forma que consegui fazer com que a apresentação fique correta foi a seguinte: 

Ex:

``` xml
<ref-list>
            <title>Referências bibliográficas</title><break/>
            <title>Fontes primárias</title>
            <ref id="B1">
                         ...
                    </ref>
</ref-list>
```

**Comment by robertatakenaka** [comment]
Por que não pode ficar assim:

```xml
                <ref-list>
                        <title>Referências bibliográficas</title>
                                <title>Fontes primárias</title>
                        <ref id="B1">
                                <mixed-citation>BEVILACQUA, Clóvis. <italic>Código Civil dos Estados Unidos do Brasil comentado</italic>. Rio de Janeiro: Editora Rio, 1975.</mixed-citation>
                                <element-citation publication-type="book">
```

Vi que no XML está incorreto. O texto Fontes primárias está como label da referência 1. Inclusive o colocaram dentro de mixed-citation. Este texto não faz parte da referência 1. 
Está assim:
```xml

                <ref-list>
                        <title>Referências bibliográficas</title>
                        <ref id="B1">
<label>Fontes primárias</label>
                                <mixed-citation>Fontes primárias BEVILACQUA, Clóvis. <italic>Código Civil dos Estados Unidos do Brasil comentado</italic>. Rio de Janeiro: Editora Rio, 1975.</mixed-citation>
                                <element-citation publication-type="book">
```

**Comment by RPostalli** [comment]
Por que pela JATS title só pode ZERO OU UMA VEZ em ref-list

**Comment by RPostalli** [comment]
Description
The following, in order:
```<label>``` Label (of an Equation, Figure, Reference, etc.), zero or one
```<title>``` Title, zero or one
http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-yf70.html

**Comment by RPostalli** [comment]
Nos fizemos alguns testes, então sim no XML está errado pq não temos como marcar. a única forma que nossa interface aceitou foi a descrita pela Jennifer, mas não é correta.

**Comment by robertatakenaka** [comment]
@RPostalli: Entendi, no entanto, acho que se algo tem que mudar é aceitar
mais de um title.

Neste caso faz sentido ter mais de 1. Melhor que aceitar title e label.

Mesmo que o SPS não aceite... Melhor deixar com mais de 1 title. Veja que
há Fontes Secundárias. Testei o site deixando com mais de 1 title e ficou
bom.

Acho que no SPS não previa uma estrutura assim. Melhor citar este exemplo
no SPS, se isso ainda não foi feito.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by robertatakenaka** [comment]
@RPostalli : Eu achei que na JATS poderia. Vamos ter que decidir... Amanhã teremos uma reunião sobre uns tickets. Vamos discutir este.

**Comment by javani** [comment]
@RPostalli @jenniferamato @robertatakenaka Como ficaria a estrutura com <p>, seria possível?
Pela JATS é permitido.

**Comment by RPostalli** [comment]
Ok Roberta.
Não Java, não é permitido.
Aproveitando Roberta, se possível discutam o caso de ```<ref-lis>``` também (se for necessário abro outro ticket), pois se existe mais uma ref-list a JATS permite duas possibilidades.

```<ref-list>
<ref-list>
text text
</ref-list>
text text
</ref-list>```

ver exemplos em: X:\fbpe\periodicos\eh\v29n58\0103-2186-eh-29-58 
Arquivos:
0103-2186-eh-29-58-0339 
0103-2186-eh-29-58-0381
0103-2186-eh-29-58-0401

OU (AO MEU VER O CORRETO)
```<ref-list>
text text
</ref-list>
<ref-list>
text text
</ref-list>```

OBS: não temos nenhum dos casos documentados no SPS, XC e Style não acusam erro nos dois.

**Comment by RPostalli** [comment]
```<p>``` é possível sim, mas não funciona no site e homologs também. a única forma que funcionou foi a errada: 2 title com break.

**Comment by gustavofonseca** [comment]
Estou reabrindo esse ticket pois a solução proposta (adicionar o elemento ``<label>`` logo após o elemento ``<title>``) não produz um XML válido. A JATS prevê a ocorrência do elemento ``<label>`` anteriormente ao elemento ``<title>``.

**Comment by leticiaquino** [comment]
Relacionado ao #486

**Comment by javani** [comment]
Já solucionado ver #486
