### ISSUE TITLE
Criar seção SciELO Brasil destacando as restrições da coleção

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#373]
Destacar as restrições da coleção SciELO Brasil.

Ticket relacionado #198

**Comment by javani** [comment]
@gustavofonseca @robertatakenaka @carolinatanigushi @RPostalli Sugiro a inclusão do texto abaixo nas regras de SciELO Brasil. Aguardo comentários:
**Tabelas e equações codificadas**
A codificação de dados de tabelas e equações nos elementos :ref:`elemento-disp-formula`, :ref:`elemento-inline-formula` e :ref:`elemento-table`, é obrigatória. 

Nota:  o elemento :ref:`elemento-alternatives` pode ser usado para armazenar a versão em imagem desses elementos em formato .svg.

**Comment by javani** [comment]
@RPostalli Temos que documentar nessa porque já foi documentado via comunicado.

**Comment by RPostalli** [comment]
Mas o comunicado <http://Informamos também que a partir de setembro de 2017
a nova versão 1.7 do SciELO Publishing Schema permitirá que as fórmulas
codificadas em XML, MathML ou LaTeX poderão vir acompanhadas de sua versão
alternativa em imagem SVG> diz versão 1.7, Java.

"Informamos também que a partir de setembro de 2017 a nova versão 1.7
do *SciELO
Publishing Schema* permitirá que as fórmulas codificadas em XML, MathML ou
LaTeX poderão vir acompanhadas de sua versão alternativa em imagem SVG"

Atenciosamente,

Renata Postalli
Bibliotecária Júnior

---------------
[Atenção: A versão 1.3 do SciELO PS, foi descontinuada em 5 de outubro de
2016. Por gentileza, passem a utilizar a versão 1.4 ou 1.5 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>.]

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FAP UNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

2017-02-23 15:33 GMT-03:00 javani <notifications@github.com>:
