### ISSUE TITLE
Definição das relações entre tipos de entidade *Document*, *Article*, *Sub-article*.

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#374]
Entidades do tipo _Document_ são compostas por 1 entidade tipo _Article_, que por sua vez é composta por 0 ou várias entidades tipo _Sub-Article_. Até agora nenhuma novidade. O diagrama da UML que representa as relações é:

![doc-article-subarticle](https://cloud.githubusercontent.com/assets/161335/17416841/7e136074-5a66-11e6-83b9-0c20d09b822e.png)

Indo um pouco além, uma entidade do tipo _Document_ pode se associar com várias entidades do tipo _Rendition_ -- cada uma representando uma manifestação do documento, seja HTML, PDF, ePub etc --, cada uma acessível por meio da sua própria URL (_Web Resource_):

![doc-resource-relation](https://cloud.githubusercontent.com/assets/161335/17416870/a1ed9b68-5a66-11e6-9b15-dad295f5c039.png)

_Rendition_ e _Web Resource_ não são tipos de entidade descritos na norma _JATS Publishing 1.0_, e não são representados nos documentos XML. Sua presença aqui serve para ilustrar a relação entre documentos XML e as entidades envolvidas na publicação dos conteúdos nos seus diversos formatos.

**Comment by leticiaquino** [comment]
:smile: muito boa a definição!!!

**Comment by gustavofonseca** [comment]
:bowtie:

É importante ter em mente que essa definição implica em deixarmos de representar as traduções como `sub-article[@article-type = 'translation']`, como é possível concluir olhando para o segundo diagrama.

**Comment by RPostalli** [comment]
@gustavofonseca quando possível reescrever este ticket. (sub-article em outro xml)

**Comment by RPostalli** [comment]
Envolve grandes mudanças no fluxo de trabalho. 
- Exportação de dados (CrossRef e etc)
- Validadores
- etc

Deixar 2.0
