### ISSUE TITLE
Alertas levantados durante a construção automática dos HTMLs (branch editorial-rev).

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#375]
```
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.3.1
making output directory...
loading pickled environment... not yet created
WARNING: 'default' html theme has been renamed to 'classic'. Please change your html_theme setting either to the new 'alabaster' default theme, or to 'classic' to keep using the old default.
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 138 source files that are out of date
updating environment: 138 added, 0 changed, 0 removed
reading sources... [100%] whatsnew-1.4
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-aff.rst:20: WARNING: Inline emphasis start-string without end-string.
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-article-meta.rst:4: WARNING: duplicate label elemento-article-meta, other instance in /Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/elemento-article-meta.rst
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/glossary.rst:4: WARNING: duplicate label glossary, other instance in /Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/glossary.rst
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/copyright.rst:: WARNING: document isn't included in any toctree
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/elemento-article-meta.rst:: WARNING: document isn't included in any toctree
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/reference.rst:: WARNING: document isn't included in any toctree
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/glossary.rst:: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] whatsnew-1.4
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/glossary.rst:115: WARNING: term not in glossary: projeto scielo
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/narr/errata.rst:84: WARNING: term not in glossary: ahead-of-print
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/narr/regra-nomeacao.rst:53: WARNING: term not in glossary: ahead-of-print
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-fpage.rst:16: WARNING: term not in glossary: ahead-of-print
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-lpage.rst:15: WARNING: term not in glossary: ahead-of-print
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-permissions.rst:55: WARNING: undefined label: elemento-permissions-exemplo-1 (if the link has no caption the label must precede a section header)
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-permissions.rst:56: WARNING: undefined label: elemento-permissions-exemplo-2 (if the link has no caption the label must precede a section header)
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-permissions.rst:57: WARNING: undefined label: elemento-permissions-exemplo-3 (if the link has no caption the label must precede a section header)
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-permissions.rst:58: WARNING: undefined label: elemento-permissions-exemplo-4 (if the link has no caption the label must precede a section header)
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-pub-date.rst:21: WARNING: term not in glossary: ahead-of-print
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-subj-group.rst:19: WARNING: term not in glossary: ahead-of-print
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/glossary.rst:115: WARNING: term not in glossary: projeto scielo
generating indices... genindex
writing additional pages... search
copying static files... WARNING: html_static_path entry u'/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 21 warnings.

Build finished. The HTML pages are in build/html.
```

**Comment by asael-silva** [comment]
Gustavo, seguem meus comentários:
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-aff.rst:20: WARNING: Inline emphasis start-string without end-string.- arquivo foi corrigido em 03/08
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-article-meta.rst:4: WARNING: duplicate label elemento-article-meta, other instance in /Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/elemento-article-meta.rst- erro deve ter sido aí, pois não tenho este arquivo em source, somente em tagset
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/glossary.rst:4: WARNING: duplicate label glossary, other instance in /Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/glossary.rst- erro deve ter sido aí, pois não tenho este arquivo em tagset, somente em source
looking for now-outdated files... none foundpickling environment... donechecking consistency... /Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/copyright.rst:: WARNING: document isn't included in any toctree- já havia este warning
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/elemento-article-meta.rst:: WARNING: document isn't included in any toctree- arquivo colocado em local errado
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/reference.rst:: WARNING: document isn't included in any toctree- arquivo ainda não foi revisado e não foi incluído em index.rst
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/glossary.rst:: WARNING: document isn't included in any toctree- arquivo colocado em local errado
donepreparing documents... donewriting output... [100%] whatsnew-1.4/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/glossary.rst:115: WARNING: term not in glossary: projeto scielo- termo será incluído no glossário
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/narr/errata.rst:84: WARNING: term not in glossary: ahead-of-print- estranhamente está marcado como :ref:`ahead-of-print` que é o cabeçalho no arquivo aheadofprint.rst e não como termo de glossário (:term:).
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/narr/regra-nomeacao.rst:53: WARNING: term not in glossary: ahead-of-print- esta seria a alteração global que você disse que iria fazer? (:term:`ahead-of-print` para :term:`ahead of print`)
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-fpage.rst:16: WARNING: term not in glossary: ahead-of-print- esta seria a alteração global que você disse que iria fazer? (:term:`ahead-of-print` para :term:`ahead of print`)
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-lpage.rst:15: WARNING: term not in glossary: ahead-of-print- esta seria a alteração global que você disse que iria fazer? (:term:`ahead-of-print` para :term:`ahead of print`)
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-permissions.rst:55: WARNING: undefined label: elemento-permissions-exemplo-1 (if the link has no caption the label must precede a section header)/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-permissions.rst:56: WARNING: undefined label: elemento-permissions-exemplo-2 (if the link has no caption the label must precede a section header)/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-permissions.rst:57: WARNING: undefined label: elemento-permissions-exemplo-3 (if the link has no caption the label must precede a section header)/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-permissions.rst:58: WARNING: undefined label: elemento-permissions-exemplo-4 (if the link has no caption the label must precede a section header)- este é o arquivo que está com problema e que já havia sido citado anteriormente. Não consigo detectar o erro, se é que existe.
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-pub-date.rst:21: WARNING: term not in glossary: ahead-of-print- esta seria a alteração global que você disse que iria fazer? (:term:`ahead-of-print` para :term:`ahead of print`)
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/elemento-subj-group.rst:19: WARNING: term not in glossary: ahead-of-print- esta seria a alteração global que você disse que iria fazer? (:term:`ahead-of-print` para :term:`ahead of print`)
/Users/gustavofonseca/prj/github/scielo_publishing_schema/docs/source/tagset/glossary.rst:115: WARNING: term not in glossary: projeto scielo- arquivo colocado em local errado - problema já foi comentado no local correto


Asael C Silvagandhalf_thewhite@live.com



Date: Tue, 9 Aug 2016 06:33:20 -0700

**Comment by leticiaquino** [comment]
Acredito que o ticket está resolvido.
