### ISSUE TITLE
Reavaliar estrutura de <trans-title-group>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#478]
Eu estava verificando algumas de nossas regras para XML e tem uma que não me parece muito boa.

Nós dizemos que para identificação de idioma em título traduzido, o atributo `@xml:lang` deve ser inserido no elemento `<trans-title-group>` em vez de `<trans-title>`.

Essa é uma regra do PubMed Central, veja: https://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/tags.html#el-transtitle

A meu ver não faz tanto sentido identificar o idioma numa tag de grupo, pois dessa forma a gente acaba tagueando mais e fica um pouco confuso também.
Veja como seria a identificação de título em 6 idiomas em nossa realidade de hoje:

``` xml
<title-group>
    <article-title>Effect of a mobile phone-based intervention on post-abortion contraception: a randomized controlled trial in Cambodia</article-title>
    <trans-title-group xml:lang="fr">
        <trans-title>Effet d'une intervention par téléphone portable sur la contraception après avortement: essai contrôlé randomisé au Cambodge</trans-title>
                </trans-title-group>
    <trans-title-group xml:lang="es">
        <trans-title>El efecto de una intervención basada en la telefonía móvil en los métodos anticonceptivos postaborto: un ensayo controlado aleatorizado en Camboya</trans-title>
                </trans-title-group>
    <trans-title-group xml:lang="ar">
        <trans-title>تأثير التدخل القائم على الهاتف الجوّال على موانع الحمل بعد الإجهاض:  تجربة معشاة مضبطة بالشواهد في كمبوديا</trans-title>
                </trans-title-group>
    <trans-title-group xml:lang="zh">
        <trans-title>基于手机的干预对流产后避孕的效果：柬埔寨的一项随机对照试验</trans-title>
                </trans-title-group>
    <trans-title-group xml:lang="ru">
        <trans-title>Рандомизированное контролируемое исследование влияния медицинского обслуживания, проводимого с помощью мобильной связи, на постабортную контрацепцию, проведенное в Камбодже</trans-title>
                </trans-title-group>
</title-group>
```

(exemplo extraído de uma das publicações da BWHO)

Minha proposta é identificar esses títulos traduzidos em um único elemento `<trans-title-group>` identificando o idioma no elemento `<trans-title>`:

``` xml
<title-group>
    <article-title>Effect of a mobile phone-based intervention on post-abortion contraception: a randomized controlled trial in Cambodia</article-title>
    <trans-title-group>
        <trans-title xml:lang="fr">Effet d'une intervention par téléphone portable sur la contraception après avortement: essai contrôlé randomisé au Cambodge</trans-title>
        <trans-title xml:lang="es">El efecto de una intervención basada en la telefonía móvil en los métodos anticonceptivos postaborto: un ensayo controlado aleatorizado en Camboya</trans-title>
        <trans-title xml:lang="ar">تأثير التدخل القائم على الهاتف الجوّال على موانع الحمل بعد الإجهاض:  تجربة معشاة مضبطة بالشواهد في كمبوديا</trans-title>
        <trans-title xml:lang="zh">基于手机的干预对流产后避孕的效果：柬埔寨的一项随机对照试验</trans-title>
        <trans-title xml:lang="ru">Рандомизированное контролируемое исследование влияния медицинского обслуживания, проводимого с помощью мобильной связи, на постабортную контрацепцию, проведенное в Камбодже</trans-title>
    </trans-title-group>
</title-group>
```

Caso estejam todos de acordo com minha proposta de identificação de títulos traduzidos, eu gostaria de verificar a possibilidade de gerar um XML com o detalhamento que o PMC exige sem precisarmos intervir diretamente no documento XML.

**Comment by carolinatanigushi** [comment]
@javani como ninguém se manifestou sobre resolver esse ticket, posso fazê-lo?

**Comment by javani** [comment]
@carolinatanigushi pode sim.

**Comment by robertatakenaka** [comment]
@carolinatanigushi , @javani : analisando este ticket, considero que ele deve ser fechado, não ser aceito. Os motivos são:

1) impacto em todo o fluxo: markup, xpm, xc, web

2) impacto no XML do PMC
![captura de tela 2017-05-19 as 10 51 56](https://cloud.githubusercontent.com/assets/505143/26250891/e6a659f4-3c81-11e7-9bcb-d61dfe18c18d.png)

3) recomendação do próprio JATS:
![captura de tela 2017-05-19 as 10 58 51](https://cloud.githubusercontent.com/assets/505143/26250999/36a39494-3c82-11e7-996f-98e35ec0e0d8.png)

**Comment by javani** [comment]
Ok @robertatakenaka, concordo.
