### ISSUE TITLE
Aceitar o elemento <attrib> em <table-wrap-foot>

### ISSUE THREAD

**Issue by natalieakemi** [scieloorg/scielo_publishing_schema#480]
Em <atrib> Aparece em inserir `table-wrap-foot` ao invés de`table-wrap`

**Comment by gustavofonseca** [comment]
Poderia justificar essa solicitação de mudança? 'table-wrap/attrib'
passaria a ser considerado inválido?

-Gustavo


Em Seg 17 out. 2016, às 11:34, natalieakemi escreveu:

**Comment by leticiaquino** [comment]
@gustavofonseca Já consideramos ```<attrib>```em ```<table-wrap>```. Veja:
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/tagset/elemento-attrib.html

Só não consideramos dentro de ```<table-wrap-foot>```.

**Comment by natalieakemi** [comment]
Quando coloca em `table-wrap` não fica visível no site. Veja o exemplo abaixo:

![image](https://cloud.githubusercontent.com/assets/19558447/19442930/d4d5bf96-9469-11e6-813b-e1753871457c.png)
 
![image](https://cloud.githubusercontent.com/assets/19558447/19442945/e2a0acc6-9469-11e6-83a2-e9d77f5712da.png)

**Comment by natalieakemi** [comment]
`attrib` em `table-wrap-foot ` é permitido pela http://jats.nlm.nih.gov/publishing/tag-library/1.0/, porém não consta na documentação do SPS.

**Comment by gustavofonseca** [comment]
@natalieakemi, entendi. 

Um comentário: esse ticket poderia ser melhor descrito com o título "Texto do elemento ``table-wrap/attrib`` não é exibido no formato HTML", e acompanhado pela descrição do teste que fez utilizando o elemento ``table-wrap-foot``. Prefira sempre descrever o problema ao invés da solução =]

**Comment by leticiaquino** [comment]
Relacionado ao ticket: https://github.com/scieloorg/Web/issues/559

**Comment by leticiaquino** [comment]
Acredito que esse ticket seja uma solicitação para que o SciELO PS aceite também o ```<attrib>```em ```<table-wrap-foot>```.
Informo que eu alterei o titulo inserido inicialmente "Em ```<attrib>``` inserir ```<table-wrap-foot>``` " 
por:  "Aceitar o elemento ```<attrib>``` em ```<table-wrap-foot>``` "
