### ISSUE TITLE
Retirar atributos de contrib (manter author apenas)

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#482]
Conforme discussão no ticket <https://github.com/scieloorg/Web/issues/515#issuecomment-262033546>, devemos retirar o uso de atributos na tag contrib, mantendo apenas "author", uma vez que, não faz sentido a autoria não aparecer no sumário eletrônico, quando possuir outros atributos diferentes de author.  Se nossa interface não consegue identificar, e não existe nenhuma diferenciação na aparição do conteúdo na página do artigo é melhor não usar vários tipos.

Tag contrib.
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-contrib.html#contrib

**Comment by javani** [comment]
@RPostalli há casos na rede de publicações com estes tipos de contribuições como traduções, por exemplo. Acredito que a correção deva ocorrer apenas na web.
