### ISSUE TITLE
*CDATA* como filho do elemento *name* invalida o doc em relação a JATS.

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#484]
A [documentação referencial](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/tagset/elemento-product.html) do elemento ``<product>`` define que a identificação dos metadados do produto seja realizada preservando pontuação. Essa definição se justifica na necessidade de referenciar, no texto da resenha, o produto resenhado preservando a formatação correta.

Entretanto, [exemplo apresentado na documentação citada](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/tagset/elemento-product.html#exemplo-de-marcacao-de-product-de-livro) contém pontuação também abaixo do elemento ``<name>``, o que é proibido segundo a norma JATS Publishing 1.0. 

Sugiro que, além de corrigir o exemplo, também deixemos claro que os caracteres de pontuação não são permitidos dentro da estrutura do elemento ``<name>``.

**Comment by cleberneves** [comment]
A preservação da formatação da descrição de um livro, por exemplo, já não está de saída inviabilizada pelas restrições das normas? Me refiro não só aos sinais e espaços que precisarão ser eliminados, mas também à própria ordem dos elementos. Uma resenha descrita com autoria ou tradução no formato "Nome Sobrenome" não precisará ser recomposta como "SobrenomeNome", tanto para eliminar o espaço não permitido quanto para manter a tag <surname> antes de <given-names>?

**Comment by gustavofonseca** [comment]
Você está certo @cleberneves. As restrições da JATS quanto ao uso do elemento ``<name>`` inviabilizam a representação da referência ao produto em sua forma literal, mas não podemos desprezar as vantagens dessa nova maneira de uso do elemento ``<product>``.  A mais relevante, na minha opinião, é que um ``<product>`` representado como no [exemplo citado](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/tagset/elemento-product.html#exemplo-de-marcacao-de-product-de-livro) reduz a quantidade de decisões tomadas pelo SciELO quanto a forma da referência. As decisões agora concentram-se apenas na forma em que vamos dispor os nomes dos autores.

**Comment by javani** [comment]
@gustavofonseca @robertatakenaka @RPostalli no guia dizemos que o elemento product será usado apenas quando o tipo de artigo for book-review. Pela lógica, o atributo product-type é dispensável. Além disso, incluímos dois tipos de product-type (book e other) o que não faz sentido. Retiramos essa informação?

**Comment by RPostalli** [comment]
A roberta corrigiu os problemas com pontuação (ver ticket https://github.com/scieloorg/Web/issues/532). Eu acho que se existe uma tag para um elemento, disponíveis em artigos no SciELO, a tag deve sim ser documentada e usada. Se não for marcado nesta tag será identificado em <p> dentro de body desnecessariamente já que existe tag para o dado. (vai parecer uma marcação na "gambiarra").
Talvez seja o caso de aumentar os atributos permitidos em product-type.

**Comment by gustavofonseca** [comment]
@javani e @RPostalli, essa discussão está fora do escopo do ticket #484. Sugiro que seja registrado um novo ticket para tratarmos desse assunto.
