### ISSUE TITLE
documentar inline-graphic como filho de inline-formula

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scielo_publishing_schema#485]
inline-formula é um elemento para indicar que é uma fórmula em linha e não contém o atributo href. Para representar a fórmula em formato gráfico (SVG) é necessário usar algum elemento que tenha o atributo href, no caso, seria o inline-graphic. 

Complementar com uso de inline-graphic.
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/tagset/elemento-inline-formula.html

**Comment by javani** [comment]
@robertatakenaka acho que nesse caso entra na mesma regra de disp-formula, receberemos somente codificada. Dessa forma, não registraríamos o inline-graphic como filho de inline-formula. Para a próxima versão 1.6 já registraremos que não será aceito em imagem. O que você acha?

**Comment by robertatakenaka** [comment]
@javani: dissemos que adotaríamos o .svg que é um arquivo, para referenciar arquivo é necessário algum elemento que contenha o @href, no caso de inline-formula, o elemento é o inline-graphic.

**Comment by javani** [comment]
@robertatakenaka entendi. é que na próxima versão da documentação será registrado os elementos apenas em sua versão codificada. Talvez seja melhor colocar uma nota na versão atual (1.5.1).

**Comment by javani** [comment]
@robertatakenaka você tem razão, não havia pensado na questão do alternatives que deverá suportar o formato. Então teremos que deixar claro na documentação que para o alternatives desses elementos o tipo de imagem aceita será o .svg. Obrigada

**Comment by javani** [comment]
@robertatakenaka conforme conversamos na última reunião, inline-graphic é elemento permitido em alternatives. Dessa forma, não será registrado em inline-formula.
