### ISSUE TITLE
Documentar o uso de <ref-list> dentro do elemento <ref-list>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#486]
Em "Aparece em" de ```<ref-list>``` no [SciELO PS](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/tagset/elemento-ref-list.html), incluir o elemento ```<ref-list>```.
De acordo com a JATS é possível incluir um elemento ```<ref-list>``` dentro de outro (JATS: [ref-list](http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-yf70.html)).
Isso resolve casos em que um artigo apresenta mais que uma lista de referência bibliográfica.

Exemplo:

```xml
<ref-list>
   <title>References</title>
     <ref-list>
       <title>Printed resources</title>
         <ref>[...]</ref>
         <ref>[...]</ref>
         <ref>[...]</ref>
     </ref-list>
     <ref-list>
       <title>Online resources</title>
         <ref>[...]</ref>
         <ref>[...]</ref>
    </ref-list>
</ref-list>
```

Além disso relacionado ao ticket #372 a solução pode ser:

``` xml
<ref-list>
    <title>Referências bibliográficas</title>
    <ref-list>
        <title>Fontes primárias</title>
            <ref id="B1">
                      ...
            </ref>
    </ref-list>
</ref-list>
```

**Comment by javani** [comment]
Apenas como registro, isso já vem sendo feito pelas revistas e já foi
orientado em lista como fazê-lo com o markup.
De qualquer forma, vale o registro em aparece em.



 Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=javani.araujo@scielo.org&idSignature=22>

Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

[Atenção: A versão 1.3 do SciELO PS, foi descontinuada em 5 de outubro de
2016. Por gentileza, passem a utilizar a versão 1.4 ou 1.5 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>.]

2016-12-21 9:29 GMT-02:00 Letícia Aquino <notifications@github.com>:

**Comment by leticiaquino** [comment]
Olá @javani muito obrigada!
Estamos cientes disso, porém não foi publicado no github nenhuma solução para o ticket #372.
Esse ticket foi aberto com o objetivo de registrar a solução e também como lembrete para add à documentação o elemento ```<ref-list>```dentro de ```<ref-list>```.
