### ISSUE TITLE
JATS 1.1 city, state, postal-code

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scielo_publishing_schema#487]
Comment 328

As part of the addition of ``<city>``, ``<state>,`` and ``<postal-code>``, the address-related elements should be regularized to use all of the address class elements, which will change several models including ``<conf-loc>`` and ``<publisher-loc>``.

**Comment by javani** [comment]
@carolinatanigushi por favor, crie esses elementos em rst.

**Comment by carolinatanigushi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resolver](https://trello.com/c/fNUMQaUV/114-resolver)

**Comment by carolinatanigushi** [comment]
@javani não chegamos a discutir o ticket #250 e `<named-content>` está documentado apenas para informações de city e state; eu devo alterar alguma coisa na documentação quando criar esses dois elementos?

**Comment by javani** [comment]
@carolinatanigushi sim, ainda não foi discutido. Não será preciso alterá-los porque na versão 1.0 estes elementos não existiam e eles continuarão válidos até março. Crie apenas os elementos e um exemplo de afiliação na versão 1.1.

**Comment by carolinatanigushi** [comment]
@javani revendo isso agora, eu reparei que só criei os elementos `<city>` e `<state>`, vou criar também `<postal-code>`.
