### ISSUE TITLE
Comment 00534: Add Two New Elements for Citing Data

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scielo_publishing_schema#488]
version para identificar versão de software. Na JATS 1.0, era usado edition

**Comment by javani** [comment]
@carolinatanigushi por favor, incluir na documentação. Para exemplo, usar o que já temos na documentação alterando edition, para [version](https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/version.html).
Incluir [data-title](https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/data-title.html) que será usado para referências do tipo base de dados.

**Comment by carolinatanigushi** [comment]
@javani Em "aparece em" considero todos os elementos que aparecerem na jats e que temos na nossa documentação (`<element-citation>`, `<mixed-citation>`, `<product>`, `<related-article>`) ou apenas  `<product>` e `<element-citation>` que são os elementos que a `<edition>` aceita de acordo com o que está atualmente no SPS? (isso vale para ambos `<version>` e `<data-title>`)

**Comment by javani** [comment]
@carolinatanigushi apenas para `<element-citation>` e `<product>`. Incluiremos em `<mixed-citation>` caso passemos a identificar todos os elementos dentro da tag, quando reveremos a cardinalidade dos demais elementos que compõem uma referência. Em `<related-article>` não é necessário registrar.
