### ISSUE TITLE
Seção sobre acessibilidade

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#49]
Descrever a importância e documentar as recomendações para tornar acessíveis as imagens, tabelas e equações.
- alt-text: http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-uw20.html
- alt-title: http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-px20.html
- textual-form: http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-kn60.html
- alternatives: http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-ve20.html

**Comment by leticiaquino** [comment]
Avaliar para a versão 1.5. Relacionado ao #184

**Comment by RPostalli** [comment]
Até o lançamento definitivo das novas interfaces não é possível trabalhar com acessibilidade.
Será necessário criar um projeto para implantação deste tema, não só em SPS, mas em OPAC e outros repositórios.
Ticket será fechado
