### ISSUE TITLE
Acrescentar exemplo de número especial em <issue>

### ISSUE THREAD

**Issue by natalieakemi** [scieloorg/scielo_publishing_schema#490]
Inserir o exemplo para número especial com numeração. Atualmente só existe exemplo para número especial sem numeração. http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/tagset/elemento-issue.html#exemplo-de-fasciculo-especial-em-front

Exemplo: Número Especial 2.

`<`volume`>`59`<`/volume`>`
`<`issue`>`**spe2**`<`/issue`>`

**Comment by carolinatanigushi** [comment]
@javani o exemplo na documentação não tem número especial com numeração, como descrito pela Natalie, apenas de número especial (por exemplo, vol 59 num especial ao invés de vol 50 num especial 3).

**Comment by javani** [comment]
@carolinatanigushi pode corrigir o exemplo de spe para spe2. Agradeço

**Comment by carolinatanigushi** [comment]
@javani acho que seria bom manter os dois, não? Um só "spe" e outro "spe2".

**Comment by javani** [comment]
@carolinatanigushi sim, boa ideia.
