### ISSUE TITLE
Incluir arquivos para traduções do SciELO PS para espanhol e inglês

### ISSUE THREAD

**Issue by javani** [scieloorg/scielo_publishing_schema#504]
Link para versão em inglês - http://scielo.org/local/File/EN-scielo-publishing-schema-1.5.pdf e espanhol - http://scielo.org/local/File/ES-scielo-publishing-schema-1.5.pdf

**Comment by javani** [comment]
@gustavofonseca as traduções foram baseadas na versão 1.5. É possível fazer o link para os documentos nessa versão? Posso subir no scielo.org e te passar os links para inclusão.

**Comment by javani** [comment]
@gustavofonseca acho então melhor o próprio git, já que no drive o arquivo acaba ficando vinculado a conta de email.

**Comment by gustavofonseca** [comment]
Os arquivos estão disponíveis em:
* https://github.com/scieloorg/scielo_publishing_schema/raw/master/versions/EN-scielo-publishing-schema-1.5.pdf
* https://github.com/scieloorg/scielo_publishing_schema/raw/master/versions/ES-scielo-publishing-schema-1.5.pdf

**Comment by gustavofonseca** [comment]
O commit 649eb95e71c52ef3641cedf4035891aaf18c32ee resolve esse ticket.
