### ISSUE TITLE
Tornar dados de histórico obrigatórios para SciELO BR na versão 1.6

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/scielo_publishing_schema#510]
Conforme comunicado divulgado ano passado http://us4.campaign-archive2.com/?u=f26dcf71797dd37381acb4aa5&id=2a6634a845 os dados de histórico passaram a ser obrigatórios.

Na documentação do SPS http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/tagset/elemento-history.html#history diz que pode ocorrer zero ou mais vezes.

Será necessário rever se essa decisão vale pra todos os tipos de aticle-type ou incluir uma nota para os tipos que não será necessário.

**Comment by carolinatanigushi** [comment]
@javani 
Posso ver esse ticket, mas essa regra é válida apenas para SciELO BR, ou para a rede toda? Teria que ser editado em [Regras específicas para SciELO Brasili](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/narr/scielo-brasil.html?highlight=brasil#license) ou na tag [<license>](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/tagset/elemento-license.html?highlight=license) mesmo?

**Comment by alexxpsilva** [comment]
@carolinatanigushi 
esqueci de mencionar no ticket, essa regra á valida somente na Seção SciELO Brasil

**Comment by gustavofonseca** [comment]
O comunicado define como marco inicial das regras ``a partir de janeiro de 2017``, e não a versão 1.6 como está no título do ticket.

**Comment by gustavofonseca** [comment]
Inclusive é importante nos acostumarmos a dissociar o ciclo de lançamento da especificação SPS das regras de estilo próprias de SciELO Brasil.

**Comment by alexxpsilva** [comment]
@gustavofonseca  abri o ticket para ver a possibilidade de inserir na versão 1.6 já que a versão será lançada após o comunicado.

**Comment by gustavofonseca** [comment]
@alexxpsilva entendi, ok 👍

**Comment by carolinatanigushi** [comment]
@gustavofonseca @alexxpsilva 
Vou editar o título do ticket para "Tornar dados de histórico obrigatórios para SciELO BR na versão 1.6" então, ok?

**Comment by alexxpsilva** [comment]
@carolinatanigushi  ok

**Comment by javani** [comment]
@carolinatanigushi é vália apenas para SciELO Brasil.

**Comment by carolinatanigushi** [comment]
@javani @gustavofonseca 
Referente à observação do Alex sobre a avaliar para que tipos de artigo o histórico se torna obrigatório, dei uma olhada nas nossas revistas e acho que não deve ser obrigatório para:
- partial-retraction
- retraction
- correction
- editorial
- in-brief
- other

Variam de revista para revista (no sentido que algumas têm e outras não):
- book-review	
- article-commentary
- book-review
- letter
- reply

Sendo obrigatório para:
- research-article
- review article
- rapid-communication
- brief-report
- case-report

Talvez fosse bom discutirmos isso na reunião de segunda.

**Comment by javani** [comment]
@carolinatanigushi @gustavofonseca certo, deixemos em pauta para discussão assim como a questão do graphic em disp, inline-formula e table-wrap.

**Comment by gustavofonseca** [comment]
Estou reabrindo o ticket pois [a regra está descrita de forma imprecisa](https://github.com/scieloorg/scielo_publishing_schema/blob/2e5772297f130cef89b18ee1eb057629f4fb1e0e/docs/source/narr/scielo-brasil.rst#history) de forma que não possibilita a correta implementação da validação automática.

**Comment by gustavofonseca** [comment]
A regra de aplica para qualquer tipo de documento ou temos alguma deliberação a partir do [levantamento](https://github.com/scieloorg/scielo_publishing_schema/issues/510#issuecomment-288409301) feito pela @carolinatanigushi?

**Comment by carolinatanigushi** [comment]
Eu acabei não indo na reunião em que foi discutido isso, mas deu a entender que ficaria a cargo do técnico fazendo o controle de qualidade decidir se é necessário ou não dependendo da situação:

> decidido que a análise de datas de histórico será feita no processo de controle de qualidade e não pelas ferramentas de validação. Porém, no caso do Markup, XPM e XC, terá que apresentar erro quando ausente de qualquer dado de histórico (obrigatório data completa com dia, mês e ano)

Sobre se aplicar a qualquer tipo de documento, continuo achando que não. Não acho que poderíamos exigir que uma errata, por exemplo, tivesse histórico.

**Comment by javani** [comment]
Nem errata, retratação, retratação parcial, editorial e carta tem dados de
histórico obrigatórios. Nos demais tipos poderia ser tratado como
obrigatório e avaliamos internamente se publica ou não.



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=javani.araujo@scielo.org&idSignature=22>

Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

[Atenção: A versão 1.3 do SciELO PS, foi descontinuada em 5 de outubro de
2016. Por gentileza, passem a utilizar a versão 1.4 ou 1.5 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>.]

Em 4 de abril de 2017 15:00, Carolina Tanigushi <notifications@github.com>
escreveu:

**Comment by carolinatanigushi** [comment]
Então teríamos que documentar também que, para esses tipos de arquivo, o histórico não é obrigatório. Acho que se não documentarmos a exceção, poderíamos só fazer disso uma verificação do nosso controle de qualidade interno e não seria necessário inseri-la na documentação do SPS.

**Comment by javani** [comment]
Vamos deixar o tema para ser tratado na próxima reunião, uma vez que
envolve mais do que aparenta.
De qualquer forma não podemos atrasar mais o lançamento da versão. Sugiro
deixar sem a validação do style e fazemos a verificação no QA por enquanto,
assim como o graphic em disp, inline-forma e table-wrap.



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=javani.araujo@scielo.org&idSignature=22>

Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

[Atenção: A versão 1.3 do SciELO PS, foi descontinuada em 5 de outubro de
2016. Por gentileza, passem a utilizar a versão 1.4 ou 1.5 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>.]

Em 4 de abril de 2017 15:18, Carolina Tanigushi <notifications@github.com>
escreveu:

**Comment by gustavofonseca** [comment]
Então, à partir do momento em que é definida uma restrição de integridade estrutural não há espaço para avaliar internamente os casos particulares. Ou o documento está em conformidade ou não está.

**Comment by carolinatanigushi** [comment]
Nesse caso, acho que deveríamos retirar o elemento da documentação para essa versão, e deixar para a próxima. Acho que isso é uma coisa que já está sendo verificada no controle de qualidade.

**Comment by gustavofonseca** [comment]
@javani, na minha visão não há como lançar essa versão sem que seja tomada alguma providência, nem que seja remover os parágrafos da documentação. 

Sim, @carolinatanigushi, estou de acordo.

**Comment by javani** [comment]
Deixemos então as regras SciELO Brasil destacadas na documentação assim
como está, referenciando-a nos próprios elementos para consulta, o style
permanece sem alteração.
Faltou apenas incluir nota na tag <history> para consultar regras SciELO
Brasil.


  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=javani.araujo@scielo.org&idSignature=22>

Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

[Atenção: A versão 1.3 do SciELO PS, foi descontinuada em 5 de outubro de
2016. Por gentileza, passem a utilizar a versão 1.4 ou 1.5 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>.]

Em 4 de abril de 2017 15:32, Gustavo Fonseca <notifications@github.com>
escreveu:

**Comment by gustavofonseca** [comment]
Com uma regra mal especificada e um validador que não a suporta o produto perde qualidade e damos alguns passos para trás em relação ao que temos feito nos últimos anos. Na minha opinião as opções que temos são:

1. Atrasar um pouco mais o lançamento até especificarmos corretamente essa regra (que não demora mais do que algumas horas);
2. Remover completamente a regra até que seja especificada em uma versão futura.

**Comment by javani** [comment]
@gustavofonseca @carolinatanigushi antecipei a reunião da próxima semana para quinta, para discussão da questão.

**Comment by javani** [comment]
Relacionado a #514
