### ISSUE TITLE
Documentar <chem-struct-wrap> e <chem-struct>

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#520]
Devido as novas documentações referente a formulas e equações de física e matemática, faz-se necessário documentar também a tag específica para os casos de formulas químicas.

Exemplo:

![qui](https://cloud.githubusercontent.com/assets/6084959/24801577/33712ca0-1b7b-11e7-82e6-d90532684d3e.jpg)

(OBS: Este foi um caso reportado pela GN1, título do email: Dúvida|Equações Codificadas)
(OBS2: Usualmente para estes casos, os prestadores utilizam a inserção da formula dentro de um parágrafo no corpo do texto, mas para o caso da imagem, perde-se a possibilidade de criar xref com o label da formula)

Links JATS 1.0:
1. https://jats.nlm.nih.gov/publishing/tag-library/1.0/n-tq30.html
2. https://jats.nlm.nih.gov/publishing/tag-library/1.0/n-jk50.html

**Comment by javani** [comment]
Será usada a estrutura descrita na JATS
