### ISSUE TITLE
JATS 1.1 - Aceitar <p> e <break> em <td>

### ISSUE THREAD

**Issue by javani** [scieloorg/scielo_publishing_schema#522]
Aceitar `<p>` e `<break>` em `<td>`, comment 255

**Comment by gustavofonseca** [comment]
Ok. Poderia argumentar justificando essa solicitação de mudança?

**Comment by javani** [comment]
Gustavo,

Discutimos isso em reunião e está registrado na planilha abaixo:
https://docs.google.com/spreadsheets/d/19O_E45jegTNQ6FQyK-imHe4z-Wij_rLA3h9PEJLGmGs/edit#gid=0

Justificativa:
Compatibilidade com a JATS 1.1

Grata,



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=javani.araujo@scielo.org&idSignature=22>
<#>

Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

[Atenção: A versão 1.4 do SciELO PS, foi descontinuada em 18 de abril de
2017. Por gentileza, passem a utilizar a versão 1.5 ou 1.6 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>. / A
versão XPM com datas de relatórios 21/11/2016 e 16/12/2016, serão
descontinuadas em *18 de maio de 2017*. Por gentileza, passem a utilizar a
versão *17/04/2017*.]

2017-04-20 9:57 GMT-03:00 Gustavo Fonseca <notifications@github.com>:

**Comment by javani** [comment]
@robertatakenaka @gustavofonseca não vamos documentar as tags, só indicar que a versão 1.7 passa a ser compatível com JATS 1.1  Precisamos apenas que as ferramentas validem a estrutura. O XC e XPM já estão validando.

**Comment by gustavofonseca** [comment]
@javani, então você quer dizer que esse ticket deve ser fechado sem que seja realizado?

**Comment by javani** [comment]
@gustavofonseca quero dizer que ele tem impacto nas ferramentas de validação e não na documentação. Quando declararmos que a versão 1.7 é compatível com a versão 1.1 da JATS essa informação já está implícita. Lembro-me que você tinha dito que o Style já era compatível com a JATS 1.1, mas não consigo testar. Teria como confirmar?

**Comment by gustavofonseca** [comment]
A compatibilidade do stylechecker com a JATS1.1 foi atestada por meio de análise, mas ainda não há uma versão que de fato aceite a JATS 1.1.

**Comment by javani** [comment]
@gustavofonseca há como tê-la para a versão 1.7 que lançaremos até o final do mês?

**Comment by gustavofonseca** [comment]
sim 👍
