### ISSUE TITLE
Correção em exemplo de funding-statement

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#524]
No link: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-funding-statement.html#funding-statement

O exemplo contém duas instituições, mas a marcação só está descrevendo uma. Para corrigir ou retira-se a segunda instituição ou acrescenta-se a marcação dela.

**Comment by francine-curivil** [comment]
Incluir
<funding-source> Fundação de Amparo à Pesquisa do Estado de São Paulo</funding-source>
no exemplo abaixo de <funding-source>Coordenação de Aperfeiçoamento de Pessoal de Nível Superior</funding-source>.

**Comment by francine-curivil** [comment]
Como deve ficar:
  <funding-group>
            <award-group>
                <funding-source>Coordenação de Aperfeiçoamento de Pessoal de Nível Superior</funding-source>
                <funding-source> Fundação de Amparo à Pesquisa do Estado de São Paulo</funding-source>
                <award-id>04/08142-0</award-id>
            </award-group>
            <funding-statement>This study was supported in part by Coordenação
            de Aperfeiçoamento de Pessoal de Nível Superior (Capes — Brasília,
            Brazil), Fundação de Amparo à Pesquisa do Estado de São Paulo (FAPESP —
            Grant no. 04/08142-0; São Paulo, Brazil)</funding-statement>
        </funding-group>

**Comment by francine-curivil** [comment]
Como deve ficar:
`  <funding-group>
            <award-group>
                <funding-source>Coordenação de Aperfeiçoamento de Pessoal de Nível Superior</funding-source>
                <funding-source> Fundação de Amparo à Pesquisa do Estado de São Paulo</funding-source>
                <award-id>04/08142-0</award-id>
            </award-group>
            <funding-statement>This study was supported in part by Coordenação
            de Aperfeiçoamento de Pessoal de Nível Superior (Capes — Brasília,
            Brazil), Fundação de Amparo à Pesquisa do Estado de São Paulo (FAPESP —
            Grant no. 04/08142-0; São Paulo, Brazil)</funding-statement>
        </funding-group>`
