### ISSUE TITLE
Considerar todos os atributos permitidos na JATS para datas de histórico

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#527]
relacionado com #244

Em relação a este ticket = https://github.com/scieloorg/Web/issues/511

Devemos permitir todos os tipos de date-type para datas de history, atualmente só permitimos 3 - Ver em documentação SPS: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-date.html.

Já em date-type JATS, temos 8 tipos: https://jats.nlm.nih.gov/publishing/tag-library/1.0/n-iki0.html

A inserção de datas de "primeira publicação online" vem ocorrendo bastante e estamos orientando atualmente a marcação desta informação em nota do tipo other, já que nossos validadores não permitem a inserção. Ver mais no email seguir:

Email enviado 19/05/2017
RBP -- Dúvida sobre tag epub 
Denise Arend
08:31 (Há 19 minutos)
para Conversão, Scielo 

Olá,
Estamos preparando os arquivos da próxima edição. A partir deste número, passaremos a incluir a informação "epub" após as datas de recebido e aceito, para marcar no PDF oficial/final a data original de publicação em ahead of print. No entanto, recebi hoje a mensagem abaixo + arquivos em anexo da CWG, informando sobre erro/dificuldade em como codificar esse item no XML. 

We were having a small trouble with the xml tagging of the ePub date as it is highlighted in the attached screenshot. This epub date was not there in our previous issues, they only had the Submitted date and accepted date. And SciELO upload DTD allows only Submission date and Accepted date. We tried various other tags like ‘ppub’ ‘publish’ date for all of these SeiELO Style checker was giving us error message. I have attached all the screenshots of the error messages for your reference. Since the validator was not allowing us to create the package we decided to remove that content from xml and create the package as we have been doing for all RBP Issues uploaded so far.
I request you to please advise us on how to resolve this issue.      

Podem ajudar?

Obrigada,

Denise Arend

**Comment by gustavofonseca** [comment]
Esse é um tema bastante relevante para a especificação e penso que demanda um esforço especial da nossa parte. Sugiro que qualquer que seja a nossa decisão, ela leve em conta a [recomendação que está sendo elaborada pela JATS4R que leva o título "Article publication and history dates"](http://jats4r.org/article-publication-and-history-dates) e encontra-se atualmente em rascunho.

**Comment by robertatakenaka** [comment]
@gustavofonseca:

Para SciELO o mais importante é **received** e **accepted**. O que tem acontecido é que às vezes há outras datas e para não deixar de identificar precisaríamos definir alguns outros tipos, mas somente para não ficar de fora.

Não podemos levar totalmente em conta JATS4R.

JATS4R adota **accepted-manuscript** no lugar de **received**, que usamos há anos desde o início de SciELO.

De acordo com JATS são apenas valores sugeridos, logo quem adota JATS poderia definir os valores que melhor lhe convém.

Aparentemente JATS4R tem o objetivo de registrar datas desde o início quando o artigo está sendo produzido e, por isso, há valores que não necessariamente vão ser aplicáveis para SciELO. Faria sentido a partir do momento em que houver um serviço de produção de artigos desde o zero dentro da plataforma SciELO.

**Comment by gustavofonseca** [comment]
Não sugeri que adotassemos a recomendação da JATS4R de maneira dogmática, mas apenas que não fosse ignorada.. que fosse _levada em conta_.

Eu entendo quando você diz que as datas **received** e **accepted** são as que importam para o SciELO, mas a especificação vai além das necessidades objetivas operacionais de uma coleção.. ela precisa de expressividade para acomodar e representar dados e metadados que estão no artigo, como o caso descrito pela @RPostalli.

**Comment by carolinatanigushi** [comment]
@javani 
Nesse caso me parece que o ticket ainda não foi discutido, então vou deixá-lo aberto, ok?

OBS: Editei o post original da Renata para retirar as informações da Denise.

**Comment by RPostalli** [comment]
Bom dia.

Hoje (18/10) tivemos uma nova solicitação referente as datas vinda da Caboverde para a RSP. A motivação é que a revista passou a publicar os artigos primeiro no site deles então existe ai uma primeira data de publicação online que não é a de SciELO.
----------------------------------------

Atendimento | Atendimento | 18:23 (Há 14 horas) 
Atendimento
para mim, conversao, rsppublicacao, rspedicao, comercial | 

Boa tarde Renata,
 
Solicitamos manter a data de publicação (PUB date) enviada no XML dos artigos da RSP com DOI novo (USP).
 
Obrigada,
Atenciosamente,
----------------------------------------
Minha resposta:
----------------------------------------
Bom dia Tatiane.

A data pub-date é a data de publicação do artigo em SciELO. Caso a rsp queira, ela pode inserir no PDF a data de "first publication" e deverá ser marcada no XML como uma nota.

Fico à disposição.

**Comment by gustavofonseca** [comment]
@RPostalli, sobre `pub-date` ser a de publicação do artigo na SciELO é uma novidade para mim. Inclusive não encontrei na documentação da SciELO PS. Pode me indicar o link?

**Comment by RPostalli** [comment]
Não existe documentação disso @gustavofonseca uma vez que trata-se de procedimento interno inserido manualmente e só nós sabemos qual será a data de publicação exata já que nos baseamos na data de processamento dos pacotes. (lembra da discussão que o site deveria inserir a data de atualização e não nós, mas não temos como fazer isso?). Pois bem, quando temos publicações da modalidade PC e AOP que necessitam da data completa (dia, mês, ano) isso é feito manualmente.

Mas contudo, a questão aqui deste ticket não é relacionado a pub-date e sim a date (datas de histórico).

**Comment by gustavofonseca** [comment]
Eu entendo que procedimentos internos não fazem parte da especificação e do seu guia, e estou de acordo com isso. Minha pergunta foi mais no sentido do uso do elemento ser exclusivo para representar a data de publicação na SciELO, e não no formato digital independentemente do portal ou mídia conforme é o uso sugerido pela JATS e que o estilo SciELO não resignifica ou restringe. Acho que esse é um ponto sensível que merece entrar na pauta de discussões futuras =]

**Comment by robertatakenaka** [comment]
@gustavofonseca e @RPostalli : vou tentar desfazer a confusão

**pub-date** foi e é usada apenas para datas de publicação: epub, ppub, ppub-epub, collection, etc (a mesma regra JATS ou PMC, até por isso acho que não tem destaque em SPS...)

este ticket não é sobre pub-date, mas sim sobre os tipos de datas de histórico (recebido, aceito, revisado, etc), que é outro conceito mesmo. Inclusive houve esta confusão com o pessoal da texture.

Preencher pub-date (epub) é um procedimento interno porque indica quando o artigo foi publicado online no SciELO, inclui o dia, no caso de aop ou rolling pass. Na verdade, quando isso foi pensando se considerava que era a primeira vez que o artigo era publicado. Sendo assim, é passível de discussão futura, sim. Já pub-date (ppub ou epub-ppub) vem com o dado fornecido pelo "editor", já que acompanha a data (ano/mes)  do fascículo.

**Comment by RPostalli** [comment]
Ok @gustavofonseca abrimos outro ticket para discutir esta questão (de pub-date). Mas porque não podemos aceitar todas os tipo de datas de histórico possíveis se a JATS permite? Não vai interferir em nenhuma regra de SciELO.

**Comment by RPostalli** [comment]
Só para esclarecer, o ticket é sobre datas de histórico e a Caboverde quis usar uma data de histórico (que não aceitamos mas existe na JATS) na tag de pub-date.

**Comment by RPostalli** [comment]
Após discussão decidimos que vamos documentar todas as datas mencionadas pela JATS na versão SPS 1.8. 
Atividades relacionadas:
- Criar textos padrão (3 idiomas)
- Abrir ticket no OPAC 
- Abrir ticket na Web(??).

**Comment by RPostalli** [comment]
Criado tickets: 
Título: Novos tipos de datas de histórico: considerar na interface

OPAC
https://github.com/scieloorg/opac/issues/903

WEB: 
https://github.com/scieloorg/Web/issues/648
