### ISSUE TITLE
Resultados inconsistentes na busca da documentação

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/scielo_publishing_schema#528]
Prezados,

Os links que são retornados ao se utilizar a busca da documentação do SPS sempre direcionam para uma página não existente (Maze), mesmo quando a documentação existe no Guia.

Um exemplo:

Ao fazer uma busca com o elemento "funding", os resultados retornados são os seguintes:
[(resultados da busca)](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.6-branch/search.html?q=funding&check_keywords=yes&area=default)

Entretanto ao clicar em qualquer link dessa lista de resultados, somos direcionados para a seguinte página
![capturar](https://user-images.githubusercontent.com/27728729/28020699-ac0a0ef0-655b-11e7-9ee4-db7b04947285.PNG)
(página encaminhada quando cliquei no link [< award-group >](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.6-branch/tagset/elemento-award-group.rst.html?highlight=funding))

Isso acontece com todas as buscas na documentação, seja de páginas de elementos ou de palavras-chave que auxilie a encontrar informações. Não tenho ideia de qual seja o erro, mas alguns prestadores já reportaram que encontraram a página vazia com os links quebrados.

Atenciosamente,
Cinthia.

**Comment by carolinatanigushi** [comment]
Eu já havia visto esse problema um tempo atrás... pelo que falei com o @gustavofonseca é com o readthedocs, não com a nossa documentação em si, então acredito que não temos como resolvê-lo. Você pode alterar o link da busca, retirando o **.rst** que irá funcionar:

![sem titulo](https://user-images.githubusercontent.com/12699183/28021362-f3b3a084-655d-11e7-98ba-d6847fcc1c88.png)
