### ISSUE TITLE
Exemplos de tabelas/equações em SVG na documentação de SciELO PS

### ISSUE THREAD

**Issue by aline-cristina** [scieloorg/scielo_publishing_schema#529]
Na documentação da SciELO PS (mesmo a 1.6) não existe menção da obrigatoriedade do SVG no caso de entrega de tabelas e equações não codificados (ver elementos `<inline-formula>`, `<disp-formula>` e `<table>`). Além disso, os exemplos de `<disp-formula>` e `<table>` utilizam imagens TIFF e não SVG. 

Apesar de existir o comunicado sobre o SVG, caso alguém consulte diretamente a documentação e não veja o comunicado, a informação passada estaria incorreta - pois não aceitamos nem equações nem tabelas em TIFF (apesar da JATS aceitar).

![image](https://user-images.githubusercontent.com/26901197/28133259-c840d53e-6715-11e7-9035-f859d21ae8b4.png)

![image](https://user-images.githubusercontent.com/26901197/28133292-e1f0e424-6715-11e7-9155-8cfc9131bd90.png)

Não temos o elemento `<graphic>`, temos o `<fig>`, que também não faz menção a essa informação.

**Comment by javani** [comment]
@aline-cristina decidimos que a orientação sobre o SVG ficaria apenas em "regras SciELO Brasil" uma vez que a documentação deve orientar a rede como um todo. Veja que nos elementos há um link para regras SciELO Brasil, caso haja correções ela deve ser feita na documentação narrativa e não no elemento. O elemento <graphic> não será documentado e em <fig> não há restrição de formato, sendo que esta tag não é usada nos elementos citados no ticket.
