### ISSUE TITLE
Documentar o elemento *boxed-text*

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#53]
Documentar o uso segundo a JATS

**Comment by gustavofonseca** [comment]
Thread relacionada na lista scielo-xml: https://groups.google.com/d/msg/scielo-xml/y6ISzaXebPE/ri2_xDD1dboJ

**Comment by lpanebr** [comment]
Oi gente,

Sei que vocês já tem bastante trabalho e tenho notado que a equipe aumentou e a participação também. Parabéns pelo excelente trabalho que estão desenvolvendo tanto no WEB quanto no Style Checker!

Alguma previsão de quando poderemos passar a xportar quadros e afins usando o boxed-text?? É um hack muito manual, trabalhoso e propenso a erro para nós ter que transformar os boxed-text em tabelas...  :-(

**Comment by gustavofonseca** [comment]
Fala Luciano, valeu =]

Você pode explicar melhor o que quer dizer com “poder passar a exportar quadros e afins usando o boxed-text”? Não entendemos os detalhes do hack manual que você menciona.

Abraço,
-Gustavo
