### ISSUE TITLE
Correções em "Ocorre"

### ISSUE THREAD

**Issue by aline-cristina** [scieloorg/scielo_publishing_schema#532]
É necessário discutir sobre como tentar diminuir a confusão/ambiguidade criada entre SciELO PS e JATS na hora de analisar as ocorrências. Abaixo casos encontrados em que ficam visíveis essas confusões (pontos a serem discutidos).

**`<award-id>` `<funding-source>`** a ocorrência em SciELO PS é determinada pela presença do elemento `<award-group>`, e a ocorrência de **`<award-group>`**  em SciELO PS é determinada pela presença do elemento `<funding-group>`.

A ocorrência de **`<table>`**  em SciELO PS é determinada pela presença do elemento `<table-wrap>`.

**`<chapter-title>` `<conf-date>` `<conf-loc>` `<conf-name>`** ocorrem 0 ou 1 vez em `<element-citation>`, na SPS 1.6 a ocorrência é de 0 ou mais vezes. O mesmo caso para **`<edition>`**, pois ocorreria apenas 0 ou 1 vez dentro do elemento. 

**`<corresp>`** na documentação hierárquica da JATS o elemento pode ocorrer 1 ou mais vezes em `<author-notes>`, enquanto **`<author-notes>`** pode ocorrer 0 ou 1 vez. Em SPS 1.6 está documentado como ocorrência 0 ou mais vezes.

**`<label>`** aparece como obrigatório, por exemplo, em `<app>` na JATS e com ocorrência de 0 ou 1 vez em outros elementos. Em SciELO PS 1.6 está como 0 ou várias vezes vendo no todo - pois pode ocorrer em vários elementos, porém não mais de 1 vez em cada elemento. 

**`<name>`** aparece como obrigatório na JATS, mas em SciELO PS 1.6 está documentado que pode ocorrer 0 ou mais vezes. Atrelado ainda a este elemento, **`<prefix>`** também está com ocorrência definida como 0 ou mais vezes, porém só pode ocorrer 1 vez por elemento `<name>`.

**`<article-title>`** é obrigatório na JATS, mas em SciELO PS a ocorrência está documentada como 0 ou 1 vez.

**`<year>`** é obrigatório na JATS, mas em SciELO PS a ocorrência em `<element-citation>` e `<product>` é de 0 ou mais vezes - só é obrigatório em `<pub-date>`.

**Comment by carolinatanigushi** [comment]
@javani eu não sei se entendi exatamente o que deve ser corrigido aqui. Seria apenas uma questão de alterar a redação da ocorrência para elementos obrigatórios dentro de outros elementos? Por exemplo, em <table>, ao invés de "Ocorre: uma vez", colocar "Ocorre: uma vez dentro de <table-wrap>" ou algo do gênero?

**Comment by RPostalli** [comment]
Sugestão Roberta: Criar uma tabela com duas colunas uma de Aparece e outra de Ocorre.
@robertatakenaka Tentará realizar automático.
