### ISSUE TITLE
Inclusão/Correção de atributos

### ISSUE THREAD

**Issue by aline-cristina** [scieloorg/scielo_publishing_schema#533]
Em **`<article>`** incluir atributo `@xmlns:mml`.

Na documentação do elemento **`<table-wrap-foot>`**  fala do atributo `@id`, porém este apenas se aplica a `<fn>` (a documentação está se referindo ao próprio elemento `<fn>`, o que é redundante).

**Comment by carolinatanigushi** [comment]
Vou deixar esse ticket parado até conseguimos resolver o problema do #534 pois uma das alterações lá resolve parcialmente esse ticket.
