### ISSUE TITLE
Atualização de info. relacionada ao tipo de artigo em ahead of print

### ISSUE THREAD

**Issue by aline-cristina** [scieloorg/scielo_publishing_schema#535]
Conforme conversado com a @RPostalli :

A sugestão a ser discutida é tirar a restrição de todo **ahead of print** ser **artigo original**, pois é algo que sempre é pedido correção e posteriormente, quando o artigo sai de ahead of print, tem de ser alterado novamente.

Isso demandaria correções na documentação de [Ahead of print](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.6-branch/narr/aheadofprint.html) e de [`<subj-group>`](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.6-branch/tagset/elemento-subj-group.html).

**Comment by carolinatanigushi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resolver #535](https://trello.com/c/k7KAdWEy/109-resolver-535)

**Comment by carolinatanigushi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resolver #536](https://trello.com/c/oJ7OX6WP/108-resolver-536)
