### ISSUE TITLE
Corrigir exemplo em <media>

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#536]
Segundo informações do ticket https://github.com/scieloorg/Web/issues/618#issuecomment-317502748

Só podemos aceitar formato mp4 para vídeos, no exemplo: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-media.html#exemplo-de-media-em-elemento-fig o formato esta como avi.

Além desta correção acrescentar na tag media http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-media.html#media uma NOTA: Para vídeos o formato obrigatório é o mp4

**Comment by carolinatanigushi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resolver tiq](https://trello.com/c/oJ7OX6WP/108-resolver-tiq)
