### ISSUE TITLE
Atualização da documentação referente a @fn-type="financial-disclosure"

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/scielo_publishing_schema#537]
O texto utilizado na documentação para o valor de "financial-disclosure" em @fn-type, no elemento `<fn>` causa ambiguidade em seu uso. Também retirar o texto correspondente a declaração de financiamento com "sim" ou "não", pois o uso não é previsto pela JATS, tanto 1.0 quanto 1.1.

> Declaração de financiamento ou **negação e aceitação** de recursos recebidos em apoio à pesquisa na qual um artigo é baseado

_Mudar o texto em negrito para "recusa", talvez?_

Há também de se verificar o Style Checker para que, em caso de declaração de recusa de financiamento, a ferramenta não acuse erro; atualmente, qualquer informação marcada com "financial-disclosure" exige o preenchimento da tag `<funding>` em `<article-meta>`.

**Comment by javani** [comment]
@gustavofonseca existe como validar essa informação? Houve um caso recente em que os autores declaração terem recusado financiamento. Nesse caso não há número de contrato ou projeto, mas o tipo, segundo a definição documentação, está correto. Contudo, como não há dados de financiamento, o Style Checker aponta erro de estilo.

**Comment by gustavofonseca** [comment]
Pode me enviar o XML para análise?

**Comment by gustavofonseca** [comment]
@cinthia-vieira, pode me enviar o XML?

**Comment by cinthia-vieira** [comment]
@gustavofonseca infelizmente não temos exemplos desse uso em SciELO, entretanto, como o uso é previsto pela JATS, seria interessante discutirmos a possibilidade de validação.

Também poderíamos mudar a documentação do SPS e limitar o uso de `financial-disclosure` somente para financiamentos com contrato, tornando essa uma especificação exclusiva de SciELO, que é o caso de uso mais recorrente para os artigos publicados.

**Comment by gustavofonseca** [comment]
@cinthia-vieira, não entendi. A @javani falou no comentário https://github.com/scieloorg/scielo_publishing_schema/issues/537#issuecomment-327006728 que houve um caso recente, logo, nós deveríamos ter esse XML. Estou certo?

**Comment by javani** [comment]
@gustavofonseca encontrei o XML, mas acredito que não se enquadra nesse caso uma vez que eles estão indicando que não receberam financiamento e não que recusaram um financiamento. O tipo de nota deve ser other. 
```xml
	<fn-group>
			<fn fn-type="financial-disclosure">
				<p><bold>Sources of Funding</bold></p>
				<p>There were no external funding sources for this study.</p>
			</fn>
```
