### ISSUE TITLE
Corrigir exemplo da documentação em <list>

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/scielo_publishing_schema#538]
O exemplo para criação de listas com sublistas está incorreto na documentação. O código sugerido é:

```
<list list-type="order">
    <title>Lista Númerica</title>
    <list-item>
        <p>Nullam gravida tellus eget condimentum egestas.</p>
    </list-item>
    <list-item>
        <list list-type="order">
            <list-item>
                <p>Curabitur luctus lorem ac feugiat pretium.</p>
            </list-item>
        </list>
    </list-item>
    <list-item>
        <p>Donec pulvinar odio ut enim lobortis, eu dignissim elit accumsan.</p>
    </list-item>
</list>
```

Entretanto, ele gera o seguinte resultado:
**Lista Numérica**
1. Nullam gravida tellus eget condimentum egestas.
2. --
2.1 Curabitur luctus lorem ac feugiat pretium.
3. Donec pulvinar odio ut enim lobortis, eu dignissim elit accumsan.

Quando deveria ser:
```
<list list-type="order">
    <title>Lista Númerica</title>
    <list-item>
        <p>Nullam gravida tellus eget condimentum egestas.</p>
           <list list-type="order">
            <list-item>
                <p>Curabitur luctus lorem ac feugiat pretium.</p>
            </list-item>
        </list>
    </list-item>
    <list-item>
        <p>Donec pulvinar odio ut enim lobortis, eu dignissim elit accumsan.</p>
    </list-item>
</list>
```

E gerar

**Lista Numérica**
1. Nullam gravida tellus eget condimentum egestas.
1.1 Curabitur luctus lorem ac feugiat pretium.
2. Donec pulvinar odio ut enim lobortis, eu dignissim elit accumsan.

**Comment by javani** [comment]
@carolinatanigushi poderia providenciar a correção do exemplo?
