### ISSUE TITLE
Documentação para o uso do atributo @seq

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/scielo_publishing_schema#543]
A fim de que o atributo `@seq` da tag `<fpage>` seja utilizado de maneira funcional na versão 4.0.094 do Markup/XPM (https://github.com/scieloorg/PC-Programs/issues/2610), realizar as seguintes atualizações na documentação para a versão 1.7:

- [ ] Acrescentar a informação da necessidade de uso da tag `<article-id pub-id-type="other">` quando do uso do atributo `@seq` em `<fpage>` para a criação de uma sequência válida de artigos dentro do fascículo.

- [ ] Alterar o texto de descrição do valor "other" na documentação referente à tag `<article-id>`, atributo `@pub-id-type`, para contemplar o uso referente ao elemento `@seq`.

**Comment by javani** [comment]
@jamilatta a sequência de página para os casos em que um artigo começa na mesma página de um outro artigo é considerada no site novo para a formação da url do artigo e sua sequência no sumário eletrônico?

**Comment by gustavofonseca** [comment]
@javani, acho que sua pergunta é bastante relevante e deveria ser registrada como um ticket no repositório do projeto OPAC: https://github.com/scieloorg/opac/issues.

**Comment by jamilatta** [comment]
@javani 

Sim @fabiobatalha e Eu já havíamos identificado esse requisito e adicionamos no URLLegendarium, ver: https://github.com/scieloorg/legendarium/commit/92f65b883e183cca24b9863be2ee2ef946215c4a

**Comment by javani** [comment]
@jamilatta @gustavofonseca legal!!! Mas não ficou claro se ele resolve também a questão da sequência dos artigos no sumário eletrônico. Resolve? Se sim, não precisaremos registrar o uso da tag article-id do tipo other para ordenar os artigos. No aguardo para poder fechar o ticket.

**Comment by javani** [comment]
@jamilatta @gustavofonseca verificando scieloorg/legendarium@92f65b8 concluí que a seq será usada para formar o PID do artigo.
