### ISSUE TITLE
Sugerencia para la identificación de "Clasificación JEL"

### ISSUE THREAD

**Issue by swarzesherz** [scieloorg/scielo_publishing_schema#548]
En el área de economía nos hemos encontrado con el elemento "Clasificación JEL", que hasta el momento para conservar la información, se ha optado por ponerla dentro del <body>; sin embargo en una nueva búsqueda para encontrar una forma correcta/adecuada de marcar esta información de acuerdo con la JATS, encontramos una guía de etiquetado de la casa editora "De Gruyter", donde muestra sus lineamientos para la identificación de clasificaciones (JEL, PACS, ACM CCS, MSC 2010) con JATS.

De acuerdo con lineamientos encontrados, se utiliza la etiqueta **<kwd-group>** en conjunto con el atributo **@kwd-group-type** para así identificar un grupo de palabras clave con un tipo de clasificación, quedando de la siguiente forma (http://www.wiki.degruyter.de/production/files/dg_xml_guidelines.xhtml#classification-codes):

![image](https://user-images.githubusercontent.com/197827/30379864-8490d504-985d-11e7-8e4d-985f9d719bfa.png)

Después realizo una verificación en la documentación oficial de la JATS para ver la descripción del atributo @kwd-group-type en donde encontramos dos usos comunes, el primero es el que más nos acerca a una correcta identificación para la identificación de clasificaciones, que dice: "The most common is the name of the thesaurus, ontology, or **organization that established a particular group of keywords**, for example, “MESH”, “ISO-463”, “IEEE”, “author-generated”, “ICD9-codes”, etc.", en este caso podemos identificar a las clasificaciones como un "grupo particular de palabras clave establecidas por una organización".

Por lo que consideramos que se debe evaluar esta opción de marcado para identificar esta información dentro de los XML y así enriquecer aún más los documentos publicados en SciELO.

![image](https://user-images.githubusercontent.com/197827/30379886-97533a24-985d-11e7-9508-471766fd36af.png)

Se realizaron pruebas para verificar que los elementos marcados de esta forma se visualizarán de forma correcta en las versiones full-text y plus, y tuvimos los siguientes resultados.

Versión full-text

![image](https://user-images.githubusercontent.com/197827/30379897-a19ccd06-985d-11e7-90d9-e9c1cdbdccb7.png)

Versión plus

![image](https://user-images.githubusercontent.com/197827/30379912-aa669304-985d-11e7-9933-d8b57577c29d.png)

XML
   
![image](https://user-images.githubusercontent.com/197827/30379938-b3fa8a6a-985d-11e7-8cd3-1b435a4dbca0.png)

Se adjunta archivo XML el cual fue validado en stylechecker y no encontramos problemas.

Quedamos atentos a sus comentarios.
Saludos equipo SciELO México.

**Comment by gustavofonseca** [comment]
Hola @swarzesherz,

La única exigencia que SciELO PS hace en relación al elemento `` kwd-group`` es que sea un conjunto homogénico en relación al idioma - el atributo `` @xml: lang`` es obligatorio. Para representar un subconjunto calificado, me parece que la estructura de datos presentada por usted es perfectamente aceptable. Incluso creo que SciELO PS no debería crear un vocabulario controlado para los valores del atributo `` @ kwd-group-type``.
