### ISSUE TITLE
Incluir exemplo de DOCTYPE para JATS 1.1

### ISSUE THREAD

**Issue by javani** [scieloorg/scielo_publishing_schema#549]
Incluir exemplo de DOCTYPE para JATS 1.1 no elemento.

Alterar texto do elemento no trecho:

O [SciELO Publishing Schema](http://docs.scielo.org/projects/scielo-publishing-schema/) utiliza como base, para a versão 1.7 e subsequentes, o padrão JATS versão 1.0 e 1.1.

Exemplo JATS versão 1.1:

```xml
<!DOCTYPE article
  PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.1 20151215//EN" "https://jats.nlm.nih.gov/publishing/1.1/JATS-journalpublishing1.dtd">
```

**Comment by carolinatanigushi** [comment]
@javani Você também quer que eu já adicione essa informação no índex, ou só nesse elemento?

**Comment by javani** [comment]
@carolinatanigushi no arquivo "O que há de novo" incluiremos essa informação.
