### ISSUE TITLE
Mudança no item Regra de Nomeação de Imagens

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#55]
Acredito que o título desta seção no guia deveria abranger todas as regras de nomeação, incluindo a nomeação da pasta principal e de arquivos traduzidos (já que esse nomeação interfere no processamento dos pacotes via FTP). 

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset.html#regra-de-nomeacao-de-imagens

- Alterar nome da seção para: Sugestões:
"Regras de Nomeação" ou "Regras de Nomeação de Arquivos" 

- Acrescentar textos como: Sugestões:

Para a SciELO a construção DA PASTA principal é baseada na seguinte forma: ISSN da revista, acrônimo minúsculo, volume e número, separados por hífen. Exemplo de nome da pasta do Pacote: 1983-3083-refuem-24-03. Com suplemento: 1415-4714-rlpf-17-03-s1

Arquivos com tradução: ISSN-Acrônimo-volume-número-páginafinal-sigladalínguatraduzida

Exemplos:
1983-3083-refuem-24-03-0316-gf01-pt
1983-3083-refuem-24-03-0316-gt01-pt
1983-3083-refuem-24-03-0316-suppl01-pt

OBS: As imagens só devem ter seu nome traduzido (-pt, -en, -es e etc.) como mostra o exemplo acima se algum item da imagem de fato for traduzido. Caso não seja, utilize o mesmo nome sem tradução, pois a imagem seria a mesma do PDF em inglês e do PDF em português. Não utilize ponto (.) e nem underline (_) para nomeação.

**Comment by leticiaquino** [comment]
Olá Renata, bom dia!


sobre a troca de nome de "Regra de nomeação.." para "Sugestão.." e também
"Regra de atribuiçao de ID" para "Sugestão de Atribuição de ID" já foram
feitos, mas ainda não estão disponíveis.

sobre sua sugestão de documentar a regra de nomeação da pasta e de arquivos
traduzidos, informo que podemos sim inserir na documentação.

Em 2 de fevereiro de 2015 14:46, Renata Postalli <notifications@github.com>
escreveu:

> Acredito que o título desta seção no guia deveria abranger todas as regras
> de nomeação, incluindo a nomeação da pasta principal e de arquivos
> traduzidos (já que esse nomeação interfere no processamento dos pacotes via
> FTP).
>
>
> http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset.html#regra-de-nomeacao-de-imagens
>
>    -
>
>    Alterar nome da seção para: Sugestões:
>    "Regras de Nomeação" ou "Regras de Nomeação de Arquivos"
>    -
>
>    Acrescentar textos como: Sugestões:
>
> Para a SciELO a construção DA PASTA principal é baseada na seguinte forma:
> ISSN da revista, acrônimo minúsculo, volume e número, separados por hífen.
> Exemplo de nome da pasta do Pacote: 1983-3083-refuem-24-03. Com suplemento:
> 1415-4714-rlpf-17-03-s1
>
> Arquivos com tradução:
> ISSN-Acrônimo-volume-número-páginafinal-sigladalínguatraduzida
>
> Exemplos:
> 1983-3083-refuem-24-03-0316-gf01-pt
> 1983-3083-refuem-24-03-0316-gt01-pt
> 1983-3083-refuem-24-03-0316-suppl01-pt
>
> OBS: As imagens só devem ter seu nome traduzido (-pt, -en, -es e etc.)
> como mostra o exemplo acima se algum item da imagem de fato for traduzido.
> Caso não seja, utilize o mesmo nome sem tradução, pois a imagem seria a
> mesma do PDF em inglês e do PDF em português. Não utilize ponto (.) e nem
> underline (_) para nomeação.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/scielo_publishing_schema/issues/55>.
>



-- 
Atenciosamente,
Letícia Aquino
Unidade SciELO
leticia.aquino@scielo.org
www.scielo.org
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639
www.scielo.org | www.scielo.br

**Comment by RPostalli** [comment]
Acrescentar também nomeação de arquivos como números especiais, gera muita confusão entre os prestadores, principalmente quando o número especial não possui volume.
