### ISSUE TITLE
Verificar qual a melhor forma de identificar editor que acompanhou um artigo/fascículo

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#557]
Hoje temos documentado a questão em [contrib](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-contrib.html), mas também poderia ser um tipo (novo ou existente) de nota [fn](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-fn.html).

Questões levantadas em reunião é que o em contrib, o editor entra com peso de autor e gera métricas erradas de autoria para o artigo. Em nota ele não gera nenhuma métrica atualmente e entra com tipo other.

Exemplo:(Dúvida na lista) https://groups.google.com/forum/#!searchin/scielo-xml/%5BSciELO$20XML%5D$20Erro$20de$20estrutura$20XML$20em$20nota$20de$20rodap%C3%A9%7Csort:date/scielo-xml/_ejWxrrnY84/pgYXDnZ-AQAJ

Exemplo: (GMB) http://www.scielo.br/pdf/gmb/v40n4/1415-4757-gmb-1678-4685-GMB-2014-0338.pdf

**Comment by javani** [comment]
Já é possível identificar em nota de rodapé do tipo editado por.
