### ISSUE TITLE
Voltar todos os tipos de documento em article-type no SPS

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#564]
Documentar em SPS todas os tipos possíveis de documentos ([article-type](https://jats.nlm.nih.gov/publishing/tag-library/1.1/attribute/article-type.html)). 
Hoje não comporta todas as seções por acompanhar regra de indexável ou não indexável em ScIELO

Relacionado ao ticket #561

Acrescentar na seção Regras Específicas para SciELO Brasil, apenas os tipos indexáveis em SciELO mais regra descrita no item 5.2.2 Tipos de documentos dos [Critérios SciELO Brasil](http://www.scielo.br/avaliacao/Criterios_SciELO_Brasil_versao_revisada_atualizada_outubro_20171206.pdf)

Trecho que diz:
"A partir de 2018, somente serão indexados, publicados e incluídos nas métricas de desempenho dos
periódicos da Coleção SciELO Brasil, documentos que apresentem conteúdo científico relevante, com
autoria e afiliação institucional dos autores, título próprio diferente do título da seção, citações e
referências bibliográficas".

Implica em 5 itens obrigatórios para os tipos indexáveis:
1. autoria
2. afiliação
3.título (diferente da seção)
4. citação
5. referência

Tipos indexáveis:
Pendente fazer relação dos tipos de documentos Critperios BR com os article-type do SPS (Renata)

**Comment by robertatakenaka** [comment]
Fiz um levantamento sobre as correspondências entre Critérios, JATS, SPS, Código em SciELO desde a versão 1.0, WoS.

Por enquanto está assim:
![captura de tela 2018-01-24 as 14 48 40](https://user-images.githubusercontent.com/505143/35345041-b62169fa-0115-11e8-81ab-94bd32c85b11.png)

O grupo do SPS tem permissão para editar: 
https://docs.google.com/spreadsheets/d/11QUiwFxbprdwO542pyfI0KN3AbhsStNUvmdriPhZNs4/edit?usp=sharing

**Comment by RPostalli** [comment]
@robertatakenaka a planilha foi preenchida com os tipos de documentos faltantes. E a tag já pode ser alterada no SPS.

Este ticket gerou os tickets #595 e #594

@gustavofonseca ficou pendente verificação dos tipos para WoS (relação com interoperabilidade WoS e SciELOCI), mas que neste momento não afeta documentação SPS.

**Comment by lpanebr** [comment]
Achei estranho indexar obituário.

**Comment by robertatakenaka** [comment]
@lpanebr Alguns pesquisadores se destacaram em vida e por isso há artigos referenciando-os.
Obituário em periódicos científicos não tem o mesmo formato daqueles textos vistos em jornais.

**Comment by lpanebr** [comment]
Sim, sim.. sei que são comuns. Meu pai tem um publicado ai na Brazilian
Journal of Physics. :-)  :-(
Acho que publica-los é importante.
Minha curiosidade foi especificamente quanto à indexação. Pelo que entendo,
se eu não estiver enganado, indexar implica em contar e conceder citações,
e nesse aspecto não sabia obituários tinham relevância.. Por exemplo, é
possível fazer um obituário citando todos os trabalhos mais citados de um
autor, mas essas citações não teriam que contar para os índices dos
autores.. Mas confesso eu não estudei o assunto e imagino que vocês tenham
um motivo para indexa-los. Ou talvez meu entendimento está enganado e
indexa-los não implica nas citações etc...

**Comment by RPostalli** [comment]
Bom dia @lpanebr. Qualquer material Indexável é passível de citação, as estratégias de casa base de dados é que vai dizer o que é contado nas métricas. Apesar que essa também não é minha seara.

**Comment by robertatakenaka** [comment]
@lpanebr : Não sou expert, mas é mais ou menos isso:

**Indexar** significa que estará registrado em alguma base de dados e, portanto, **pesquisável**.
**Contar citações recebidas e concedidas** é feito sobre os documentos que estão indexados, ou seja, estão na base.
**Contar citações recebidas e concedidas** conta para o **periódico** não para cada artigo ou autor, pelo menos no SciELO. RPostalli está correta: "as estratégias de cada base de dados é que vai dizer o que é contado nas métricas". Esta contagem também depende principalmente do conjunto de periódicos. Por exemplo, se pegamos somente a coleção SciELO Brasil, um periódico apresentará alguns números, em outra coleção, o mesmo periódico apresentará outros números. 

Os critérios visam "diminuir" na base de dados a quantidade de documentos irrelevantes que baixariam a pontuação dos periódicos.

Em teoria, por exemplo, os documentos **relevantes** contém **referências bibliográficas**. Obviamente, só porque tem referência não significa ser relevante, mas pode ser um indicador de que é relevante. Estar publicado, indexado, é passível de citação, mas é a sua relevância que fará com que ele seja citado, dando pontos para o periódico.

Suponha que um documento é indexado porque está de acordo com os critérios (tem citações, tem referências, etc), mas ele nunca será citado porque não é relevante. Ele baixará os pontos do periódico.

Se pensarmos em periódicos, imagine que o periódico A publique 100 artigos no ano, e apenas 40 são citados, imagine que o periódico B  publique 50 artigos no ano, e 40 são citados. Percebemos que o periódico B é mais relevante que o A porque ele é menos citado.

**Comment by RPostalli** [comment]
:thumbsup:

**Comment by lpanebr** [comment]
@RPostalli e @robertatakenaka : Também não sou especialista, mas essa conversa me deixou um pouco menos ignorante no assunto. ;-)

Obrigado!

:-)
