### ISSUE TITLE
Verificar possibilidade de uso de pub-type collection 

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#565]
Temos atualmente uma grande demanda para publicação contínua (PC), muitas das revistas seguem a risca o teor de adiantar a publicação e por exemplo em 2017 já lançam seus artigos referente ao volume/números de 2018. Mas o pub-date fica com data epub (dia-mês-ano) de 2017 num fascículo referente ao ano de 2018. gera conflito para citação, onde a data de legenda bibliográfica do artigo é diferente do fascículo ao qual ele pertence, mas o uso da publicação para adiantar a publicação está correta:

Exemplo: BJMBR 
Braz J Med Biol Res vol.51 no.1 Ribeirão Preto  2018  Epub Nov 17, 2017

http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0100-879X2018000100603&lng=en&nrm=iso&tlng=en

No XML:

```xml
<pub-date pub-type="epub">
				<day>17</day>
				<month>11</month>
				<year>2017</year>
			</pub-date>
```

PMC adota o tipo collection para representar o ano do fascículo, ficando:

No XML:

```xml
<pub-date pub-type="epub">
				<day>17</day>
				<month>11</month>
				<year>2017</year>
			</pub-date>
			<pub-date pub-type="collection">				
				<year>2018</year>
			</pub-date>
```

Acontece que já usamos a ideia do collection para EX-AOP, exemplo:

```xml
<pub-date pub-type="epub">
				<day>27</day>
				<month>11</month>
				<year>2017</year>
			</pub-date>
			<pub-date pub-type="collection">
				<season>Jan</season>
				<year>2018</year>
			</pub-date>
```

O uso me parece bem similar e acredito que possamos adotar para PC o pub-type de collection também.

Questões:
Adotamos para todos os artigos PC?
Ou só os que publicam adiantado um ano a frente? (PMC: Adota para todos)
PMC usa datas de EX-AOP diferente (epub mais ppub sem collection) Impacta na interoperabilidade SciELO X PMC

**Comment by RPostalli** [comment]
Devido aos recentes problemas de datas com AOP (Lattes, CrossRef e SciELOCI) torna-se importante adotar para PC a data de collection.

**Comment by gustavofonseca** [comment]
@RPostalli e @scieloorg/sig-members-commiters, penso que a abordagem de uso do _collection_ não é boa pelo seguinte motivo:

Necessitamos representar 2 momentos distintos: o de disponibilização em SciELO e o de publicação (editorial ou do fascículo como a @RPostalli usou na descrição acima). Em casos onde **não** se trata de publicação contínua ou adiantada, o valor de `<pub-date pub-type="epub">` representará a data de publicação e no outro caso representará a data de disponibilização em SciELO. Esse uso não exclusivo do elemento `<pub-date pub-type="epub">` torna a especificação mais complicada de maneira desnecessária. 

Por exemplo, um software ao interpretar um documento em XML de um artigo adiantado terá de verificar a ocorrência do elemento `<pub-date pub-type="collection">` para decidir se deve interpretar `<pub-date pub-type="epub">` como data de publicação ou de disponibilização em SciELO. 

Minha sugestão é de simplificarmos a regra: `<pub-date pub-type="epub">` representa somente a data de publicação e `<pub-date pub-type="scielo">` representa apenas a data em que o documento vai ao ar no SciELO. Vou descrever essa proposta melhor em outro ticket.

**Comment by RPostalli** [comment]
**ESTUDO /  LEVANTAMENTO para documentação do caso (SPS versão 1.9):**

OBS: Não está sendo considerado ainda que a nova interface criei sozinha a data de publicação de SciELO que hoje é inserida “manualmente” no XML.

- Datas existentes de publicação (4):

![image](https://user-images.githubusercontent.com/6084959/53173348-3c1f6d00-35c6-11e9-8e45-288e33d46a59.png)

- Datas a serem criadas:

![image](https://user-images.githubusercontent.com/6084959/53173397-59543b80-35c6-11e9-92c0-40dd0787de61.png)

Sendo:
* Tipo de data SciELO: Sempre data completa (dia + mês + ano);
* Representa a data em que o artigo foi publicado efetivamente em SciELO;
* Outras datas de publicação da revista/artigo devem ficar em datas de histórico.

Tipo de data Collection: Podem ser de 3 tipos:
(Representa a data do fascículo ao qual o artigo pertence)
* ano ou;
* mês + ano ou;
* season + ano.
	

- Observações Gerais:

* É irracional supor que uma revista é impressa só pelo fato dela não adotar a modalidade PC (obrigar o uso de epub-ppub). Não temos controle de quais revistas são ou não impressas, ou quais delas imprimem apenas por demanda (incluindo as PCs).

* A data do tipo collection é a data que deve ser usada no como citar dos artigos.

* Nenhum dos tipos de @pub-type existem na JATS 1.1, os tipos permitidos são: https://jats.nlm.nih.gov/publishing/tag-library/1.1/attribute/pub-type.html

* O collection é uma data utilizada pelo [PMC](https://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/tags.html#el-pubdate):

"Articles Published Online and Collected into "Issues" Online Model — Issues here do not need to be named "Issue 1", "Issue 2", etc. These are just collections of articles online. The collecting might be done by dates (Months, Quarters, Years) or by Volume. For this model, each article will have <pub-date> with @pub-type="epub" to represent its individual publication date and a `<pub-date>` with @pub-type="collection" to represent the date of the online collection it belongs in. This date may be a day/month/year, month/year, season/year, or just year."

- Para SPS: 

* Teria que retirar a documentação da tag `[<pub-date>](https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-pub-date.html#pub-date)` (mudaria tudo)
* Criar em Regras Específicas para SciELO Brasil a nova tag `<pub-date>`
* Rever exemplos gerais que possam ter a atribuição de pub-date

- Processos de Trabalho:

Prestador/editor deve enviar os XMLs com as tags das datas, mas s data scielo sem preenchimento de conteúdo???? Ou vamos inserir manualmente? Isso refletiria em validação…
Muda geração de arquivos para [PMC](https://docs.google.com/document/d/1VGj4Bw-2LzO6T8hECA9DqDYei2Pp104Bm43H_STDrVo/edit#heading=h.wuchbaqj7i30). Em especial ex-aop 

"Articles Published Online and Collected into Print Issues Model — For this model, each article will have `<pub-date>` with @pub-type="epub" to represent its individual publication date and a `<pub-date>` with @pub-type="ppub" to represent publication date of the print issue."

- Ferramentarias:

* XC - Tem que adequar
* XPM -  Tem que adequar
* Site -  Tem que adequar
* Style Checker -  Tem que adequar
* Markup:  Tem que adequar

**Comment by lpanebr** [comment]
Para ajudar no estudo:

@RPostalli essas descrições que vc colocou do PMC são referentes à antiga versão 3.0 amarela (antes da JATS):
![image](https://user-images.githubusercontent.com/129185/53201267-4cedd400-3602-11e9-913e-8039c5b094e4.png)

Na versão verde (JATS 1.1) o atributo `@pub-type` somente é utilizado no caso abaixo.
![image](https://user-images.githubusercontent.com/129185/53201335-81fa2680-3602-11e9-85bf-55d1277fdb27.png)
provavelmente pois na JATS 1.1 o atributo `@pub-type` está deprecado[1]
![image](https://user-images.githubusercontent.com/129185/53201688-5c215180-3603-11e9-981c-955b27cb9881.png)


[1] https://jats.nlm.nih.gov/publishing/tag-library/1.1/attribute/pub-type.html

**Comment by RPostalli** [comment]
@lpanebr obrigada pelo apoio. A versão PMC é antiga mas é aceita, e é essa a versão que usamos, por isso eu mencionei ela. Mas a geração PMC é só um dos problemas, o principal aqui é definir os tipos de datas para publicação em SciELO, os ajustes para PMC serão vistos depois.

**Comment by gustavofonseca** [comment]
Penso que devemos considerar atualizar as regras da SciELO PS relativas a `pub-date` e `@pub-type`. Vou abrir um outro ticket para isso.

**Comment by RPostalli** [comment]
@gustavofonseca já existe outro ticket para isso. https://github.com/scieloorg/scielo_publishing_schema/issues/772

Eu estou tentando colocar todas as discussões num lugar só.

**Comment by gustavofonseca** [comment]
Estou reabrindo o ticket para que seja discutido o escopo correto desta regra e eventuais ajustes.

**Comment by RPostalli** [comment]
Documentar para SPS com JATS 1.1 (estudar)
Documentar para Rede (retirar de Regras específicas para scielo Brasil)

**Comment by RPostalli** [comment]
```
<pub-date publication-format="eletronic" date-type="scielo">
   <day>01</day>
   <month>01</month>
   <year>2018</year>
</pub-date>
 <pub-date publication-format="eletronic" date-type="collection">
   <season>Jan-Feb</season>
   <year>2018</year>
</pub-date>
```

**Comment by RPostalli** [comment]
Definido como Data de publicação em pub-date:

- Documenta o uso da tag para versão 1.1
- Documenta uso obrigatório de @publication-format com valor "electronic"
- Documenta uso de valor em @date-type pub ao invés de scielo
 
Exemplo:


```
<pub-date publication-format="electronic" date-type="pub">
   <day>01</day>
   <month>01</month>
   <year>2018</year>
</pub-date>
 <pub-date publication-format="electronic" date-type="collection">
   <season>Jan-Feb</season>
   <year>2018</year>
</pub-date>
```

**Comment by RPostalli** [comment]
Aberto novo ticket para correção
https://github.com/scieloorg/scielo_publishing_schema/issues/835
