### ISSUE TITLE
Alterações realizadas na documentação 1.1

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/scielo_publishing_schema#59]
As alterações realizadas na documentação 1.1 foram:

- Alteração no nome "Regra de Atribuição..." para "Sugestão de atribuição..";
- Atributo @country="" passa a ser obrigatório;
- Correção em exemplo de ```<app>```. (Estava apresentando o id em <app-group>, quando deveria estar em ```<app>```);
- Retirado ```<p>``` de ```<sig>```;
- Inserido mais 2 tipos de "fn" (presented-by e presented-at);
- Inserido mais 1 tipo de ref (other);
- Inserido ```<title>``` para ```<abstract>```, ```<trans-abstract>```, Referências e keywords (foi add uma informação de que deve conter ```<title>```);
- Inserido uma nota em ```<fig>``` para fonte em imagens;
- Alteração na informação "Os valores de dia, mês e ano devem ser representados...";
- Adicionado exemplo de seção com número;
- Alterado informação "Aparece em" de ```<funding-source>``` e ```<award-id>```;
- Correção na ref "Situação de saúde e grau de dependência de pessoas idosas...". Foi retirado @xml:lang="" de ```<article-title>```;
- Adicionado documentação de elemento ```<response>```, ```<sub-article>```, ```<verse-group>```, ```<front-stub>```, ```<boxed-text>```;
- Alteração em todos os exemplos que apresentavam a tag ```<country>``` para a tag com atributo: ```<country country="SIGLA">```;
- Alteração em todos os exemplos que apresentavam o valor "sps-1.1" para "sps-1.2"
- Adicionado modelo de referência bibliográfica incompleta.

**Comment by gustavofonseca** [comment]
O ticket #64 sugere uma outra maneira de identificar referências incompletas.
