### ISSUE TITLE
Não identificar algumas tags para *ahead of print*

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#6]
## Descrição

Eu (@leticiaquino) estava pensando se no balaio é possível não identificarmos algumas tags para Ahead Of Print. No processo atual precisamos identificar para AOP <volume>, <numero> e <paginação> como "00", conforme segue abaixo:

```
<volume>00</volume>
<issue>00</issue>
<fpage>00</fpage>
<lpage>00</lpage>
```

## Proposta de solução

A ausência dos campos acima configurar um artigo tipo *ahead of print*.

----
https://groups.google.com/d/msgid/scielo-xml-sig/c4bd57d0-40ec-4956-98f5-d7e2d0df0882%40googlegroups.com  (apenas membros do scielo-xml-sig)

**Comment by leticiaquino** [comment]
Inválido.
