### ISSUE TITLE
Marcação para Registro Clínico usando a tag de related-object.

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#601]
Marcação para Registro Clínico usando a tag de related-object.

[jats-list] JATS4R draft recommendation for Clinical Trials open for comments

Hello JATS users,

JATS4R working group has developed a draft recommendation for the tagging of Clinical Trials. This recommendation is now open for comment. Please make comments on the google doc version https://docs.google.com/document/d/1Oa9IAUWfHzBuhWevKKipLihH07pLrGuKv7FS2dRslE4/edit?usp=sharing, which is publicly available. The deadline for adding comments is Friday, March 9th, 2018. 

Para documentar na seção "Ensaio Clínico" http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/narr/ensaio-clinico.html

**Comment by gustavofonseca** [comment]
Relacionado com #861

**Comment by gustavofonseca** [comment]
Este ticket está duplicado.
