### ISSUE TITLE
Como representar institution-wrap, considerando os vários tipos de institution

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scielo_publishing_schema#603]
Para representar o institution-id, há a necessidade de estar dentro de institution-wrap, que contém:

```(institution | institution-id)*```

Description
Any combination of:

   ```<institution>``` Institution Name: in an Address
    ```<institution-id>``` Institution Identifier

Exemplo:
```xml
<institution-wrap>
<institution-id institution-id-type="Ringgold">1846</institution-id>
<institution-id institution-id-type="ISNI">0000 0001 2170 1429</institution-id>
<institution content-type="university">Boston University</institution>
</institution-wrap>
```

Pelos exemplos, o content-type tem o papel de indicar que tipo de instituição é (mas é sugestão e não regra).

```xml
<institution-wrap>
  <institution content-type="edu">
    University of Frostbite Falls</institution>
  <institution-id>Moo-U-41</institution-id>
</institution-wrap>
<institution-wrap>
  <institution content-type="dept">
    Dept of Campus Security</institution>
  <institution-id>dept-42s</institution-id>
</institution-wrap>
<institution-wrap>
  <institution content-type="dept">
    Dept of Moose and Squirrel Security</institution>
  <institution-id>rcky-n-bllw</institution-id>
</institution-wrap>
<institution-wrap>
  <institution content-type="office">
    Office of the Acting Dean</institution>
  <institution-id>4850ws</institution-id>
</institution-wrap>
```
No SPS, usamos em institution content-type os valores:

- original (obrigatório)
- normalized (opcional)
- orgname (obrigatório)

A questão é como representar em **aff**, institution e institution-wrap.

**Opção A:** Manter **institution(s)** como está + incluir **institution-wrap**
```xml
<aff id="aff2">
    <label>II</label>
    <institution content-type="original">
        Doutora em Educação pela Universidade de São Paulo (USP), São Paulo, São Paulo, Brasil. 0000 0004 1937 0722</institution>
    <institution content-type="normalized">Universidade de São Paulo</institution>
    <institution content-type="orgname">Universidade de São Paulo (USP)</institution>
    <institution-wrap>
        <institution-id institution-id-type="isni">0000 0004 1937 0722</institution-id>
    </institution-wrap>
    <addr-line>
        <city>São Paulo</city>
	<state>São Paulo</state>
    </addr-line>
    <country country="BR">Brazil</country>
</aff>
```

**Opção B:** Todos os institutions ficam dentro de **institution-wrap**
```xml
<aff id="aff2">
    <label>II</label>
    <institution-wrap>
        <institution content-type="original">
        Doutora em Educação pela Universidade de São Paulo (USP), São Paulo, São Paulo, Brasil. 0000 0004 1937 0722</institution>
        <institution content-type="normalized">Universidade de São Paulo</institution>
        <institution>Universidade de São Paulo (USP)</institution>
        <institution-id institution-id-type="isni">0000 0004 1937 0722</institution-id>
    </institution-wrap>
    <addr-line>
        <city>São Paulo</city>
	<state>São Paulo</state>
    </addr-line>
    <country country="BR">Brazil</country>
</aff>
```

**Comment by RPostalli** [comment]
Voto na A

**Comment by jenniferamato** [comment]
Roberta,

Voto na A também.

Atenciosamente,

*Jennifer Gonçalves Amato*
Bibliotecária
______

[Atenção: A versão 1.5 do SciELO PS, foi descontinuada em 29 de setembro de
2017. Por gentileza, passem a utilizar a versão 1.6 ou 1.7 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>. | As
versões anteriores do XPM foram descontinuadas em *15 de outubro de 2017*.
Por gentileza, passem a utilizar a versão *4.0.094 - *release 29/09/2017]


SciELO - Scientific Electronic Library Online
FAPESP - CAPES - CNPq - BIREME - FAP UNIFESP
www.scielo.org | www.scielo.br


Em 22 de fevereiro de 2018 15:57, Roberta Takenaka <notifications@github.com

**Comment by gustavofonseca** [comment]
@RPostalli e @jenniferamato, podem argumentar em favor da opção A?

**Comment by RPostalli** [comment]
@gustavofonseca posso sim.

O intuito do acréscimo da tag ```<institution-wrap>``` é exclusivamente a marcação da tag ```<institution-id institution-id-type="isni">```. Esta tag terá pouco uso uma vez que é raro números de instituições serem informados nos artigos publicados em SciELO. Sendo assim a opção A mantem a estrutura já usada por nós com o acréscimo das 2 novas (pai e filho). Neste sentido quando não houver o dado (99.9% dos casos) a marcação se dará da mesma forma que já ocorre hoje, não causando estranheza pelos usuários o que nos fará ter menos requisição de suporte referente ao tagueamento de aff como um todo.
Além disso a tag de ```<institution-wrap>```  só permite como filho apenas uma tag de ```<institution>```, como informou a Roberta, então escolhendo a opção A, esta regra não é quebrada.

**Comment by gustavofonseca** [comment]
Legal, valeu!

**Comment by RPostalli** [comment]
Para documentar em SPS:

<institution-wrap>

Aparece em         Ocorre
<aff>                   Zero ou uma vez

Elemento que designa em afiliação um identificador padronizado para instituição <institution-id> que obrigatoriamente deve possuir o atributo @institution-id-type.

Exemplo:
<aff id="aff2">
    <label>2</label>
    <institution content-type="original">Universidade de São Paulo (USP), São Paulo, SP, Brasil. 0000 0004 1937 0722</institution>
    <institution content-type="normalized">Universidade de São Paulo</institution>
    <institution content-type="orgname">Universidade de São Paulo (USP)</institution>
    <institution-wrap>
        <institution-id institution-id-type="insi">0000 0004 1937 0722</institution-id>
    </institution-wrap>
</aff>
