### ISSUE TITLE
NISO JATS Standing Committee Recommended Changes Between NISO/JATS 1.1 and JATS 1.2d1 

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#615]
PARA AVALIAR

NISO JATS Standing Committee Recommended Changes Between NISO/JATS 1.1 and JATS 1.2d1 (Committee Draft) (in Response to Comments on NISO Z39.96-2015 (JATS V1.1) through April 10, 2017)

https://groups.niso.org/apps/group_public/download.php/18337/NISO-JATS-1-1-to-1-2d1.pdf

**Comment by RPostalli** [comment]
Deaft version https://jats.nlm.nih.gov/publishing/tag-library/1.2d1/index.html

**Comment by RPostalli** [comment]
Hello List,

 

Today we are releasing the non-normative supporting materials including the schemas and Tag Library documentation for NISO Z39.86-2019 JATS 1.2. The new standard is official and is available from the NISO site: https://www.niso.org/publications/z3996-2019-jats

 

***************************************************************************************

Use https://groups.niso.org/apps/group_public/add_comment.php?document_id=20934 for all suggestions for updates to or corrections of the JATS 1.2 Standard.

***************************************************************************************

 

The documentation and schemas are available on http://jats.nlm.nih.gov

 

All of the changes between JATS version 1.1 and JATS version 1.2 are listed in the Change Report, which is now delivered in each of the Tag Libraries: https://jats.nlm.nih.gov/archiving/tag-library/1.2/chapter/version-1.2-chg.html

 

The new Tag Libraries are here:

Archiving (green): http://jats.nlm.nih.gov/archiving/tag-library/1.2/

Publishing (blue): http://jats.nlm.nih.gov/publishing/tag-library/1.2/

Authoring (orange): http://jats.nlm.nih.gov/articleauthoring/tag-library/1.2/

 

Files are available for download here:

Archiving (green): ftp://ftp.ncbi.nlm.nih.gov/pub/jats/archiving/1.2/

Publishing (blue): ftp://ftp.ncbi.nlm.nih.gov/pub/jats/publishing/1.2/

Authoring (orange): ftp://ftp.ncbi.nlm.nih.gov/pub/jats/articleauthoring/1.2/

 

Please send questions to this list. You can submit suggestions on the NISO site here:  https://groups.niso.org/apps/group_public/add_comment.php?document_id=20934

 

As you know, NISO Z39.96 JATS is in continuous maintenance at NISO. Public comments are collected at the NISO site and are addressed by the JATS Standing Committee. The Standard will not be updated more than once per year, but as Public Comments are addressed, we will be releasing draft versions of the non-normative supporting materials.

 

I want to thank the Standing Committee, Mulberry Technologies, and NISO for all of their work getting this version ready for release.

 

Happy JATSing

 

Jeff Beck

**Comment by RPostalli** [comment]
https://jats.nlm.nih.gov/publishing/tag-library/1.2/chapter/version-1.2-chg.html

**Comment by gustavofonseca** [comment]
Estou fechando este ticket uma vez que a versão 1.2 já foi lançada e não faz mais sentido avaliar um rascunho.

**Comment by RPostalli** [comment]
@gustavofonseca esse ticket é um lembrete para estudarmos as diferenças entre as versões 1.1 JATS que adotamos no SPS 1.9 contra a versão 1.2 JATS que deveremos adotar no SPS 2.0. (ou não?!);. Após o estudo e provavelmente abertura de novos tickets relacionados a este estudo ai sim este ticket poderá ser fechado.
Alguém do grupo SPS já fez esse levantamento?
