### ISSUE TITLE
adicionar mime-type na lista de atributos obrigatórios, para o tag: <media>

### ISSUE THREAD

**Issue by jfunez** [scieloorg/scielo_publishing_schema#62]
Atualmente aparece como atributos obrigatórios:
- ``mime-subtype``
- ``xlink:href``

Mas conferindo com @gustavofonseca vemos que o atributo: ``mime-type`` também é obrigatorio.

**Comment by leticiaquino** [comment]
@jfunez e @gustavofonseca Essa é uma regra SciELO?
notei que os validadores PMC não apresentam erro se inserido ```<media>```só com @mime-subtype e @xlink:href. O mesmo para ```<supplementary-material>```.

**Comment by gustavofonseca** [comment]
@leticiaquino e @jfunez Esse é o tipo de ticket que eu sou citado mas não me lembro de um dia ter tido conhecimento sobre...  Não sei quais seriam os prós e contras de ter apenas o *subtype* pois não investiguei.

**Comment by gustavofonseca** [comment]
O *internet media type* é composto por *tipo* e *subtipo* + alguns parâmetros opcionais, além disso são organizados em árvores. Me parece sensato que, mesmo não entendendo a razão do PMC para permitir a ausência do *mime-type*, nós devemos seguir a rfc2046 e esperar os dois níveis.

https://tools.ietf.org/html/rfc2046#section-1
