### ISSUE TITLE
Documentar obrigatoriedade de ORCID <contrib-id> em Regras SciELO Brasil

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#634]
Conforme informado pelos Critérios SciELO (2018), contrib-id do tipo ORCID será obrigatório em 2019, que será data em que será lançada a versão SPS 1.9. 
Deve-se criar seção para Regras Específicas para SciELO Brasil.

**Comment by RPostalli** [comment]
Em conversa com Solange 18/02/2019, ainda não tornaremos obrigatório a publicação com ORCID. Aberto ticket para mostrar apenas warning no XPM https://github.com/scieloorg/PC-Programs/issues/3034.

O ticket deverá ser revisto para versão 2.0 de 2020.

**Comment by francine-curivil** [comment]
@jenniferamato @robertatakenaka @gustavofonseca segue minhas sugestões para incluir nas Regras:

<contrib-id>
Este elemento em <contrib> com o valor "orcid" é obrigatório para SciELO Brasil e deve ocorrer uma ou mais vezes.
OU
Este elemento em <contrib> com o atributo @contrib-id-type e valor "orcid" é obrigatório para SciELO Brasil e deve ocorrer uma ou mais vezes.

**Comment by robertatakenaka** [comment]
No lugar de `

> deve ocorrer uma ou mais vezes.

deveria ser:

`deve ocorre 1 vez para cada contribuidor`

**Comment by jenniferamato** [comment]
@francine-curivil 
Concordo com a sugestão da @robertatakenaka

**Comment by francine-curivil** [comment]
Nova sugestão:

Este elemento em `<contrib>` com o atributo `@contrib-id-type` e valor `orcid` é obrigatório para SciELO Brasil em pelo menos um dos autores e deve ocorrer uma vez para cada autor.

Nas sugestões anteriores dá a entender que é obrigatório para todos os autores, mas por enquanto é obrigatório para pelo menos um autor.

**Comment by gustavofonseca** [comment]
Acho confuso este desmembramento por extenso da estrutura XML. E se falarmos algo como: 

Para que o documento seja submetido para a coleção SciELO Brasil, ao menos um dos autores deve possuir o identificador _ORCID_ atribuído, conforme o exemplo: 

```xml
<!-- precisa bolar um fragmento direito.. esse é só ilustrativo -->
<contrib-group>
    .... 
    <contrib @contrib-id-type="orcid">blabla</contrib>
    ...
</contrib-group>
```

**Comment by jenniferamato** [comment]
@gustavofonseca 
Não sei se seria o caso de inserir exemplo em SciELO Brasil, já há exemplo em:
https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-contrib-id.html

Até o momento em [Regras Específicas para SciELO Brasil](https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/narr/scielo-brasil.html) não colocamos nenhum exemplo, apenas é listamos o que é obrigatório para SciELO Brasil. 
Já que como deve ser feito está especificado em ```<contrib-id>```, estaríamos repetindo informação.

**Comment by robertatakenaka** [comment]
> Nova sugestão:
> 
> Este elemento em `<contrib>` com o atributo `@contrib-id-type` e valor `orcid` é obrigatório para SciELO Brasil em pelo menos um dos autores e deve ocorrer uma vez para cada autor.
> 
> Nas sugestões anteriores dá a entender que é obrigatório para todos os autores, mas por enquanto é obrigatório para pelo menos um autor.

Não, @francine-curivil. Não, @gustavofonseca .
O elemento e o atributo seguem a seguinte estrutura:

```xml
<contrib-group>
<contrib>
        ...
        <contrib-id contrib-id-type="orcid">1111-2222-3333-4444</contrib-id>
        <contrib-id contrib-id-type="lattes">????</contrib-id>
</contrib>
<contrib>
        ...
        <contrib-id contrib-id-type="orcid">1111-2222-3333-4444</contrib-id>
        <contrib-id contrib-id-type="lattes">????</contrib-id>
</contrib>
</contrib-group>
```

Só pode ter 1 e não 1 ou mais `contrib-id[@contrib-id-type="orcid"]`  por `contrib`.
Fazendo uma analogia, vc pode ter vários tipos de documento de identificação: RG, Carteira de motorista, CNH, Passaporte, Carteira de Trabalho. Em teoria, ninguém pode ter mais de um RG ou qualquer um destes ítens.
Mas, sim, todos os contrib (autores) podem ter mais de 1 ID. Ficou mais claro?

**Comment by robertatakenaka** [comment]
> @gustavofonseca
> Não sei se seria o caso de inserir exemplo em SciELO Brasil, já há exemplo em:
> https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-contrib-id.html
> 
> Até o momento em [Regras Específicas para SciELO Brasil](https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/narr/scielo-brasil.html) não colocamos nenhum exemplo, apenas listamos o que é obrigatório para SciELO Brasil.
> Já que como deve ser feito está especificado em `<contrib-id>`, estaríamos repetindo informação.

concordo

**Comment by francine-curivil** [comment]
@robertatakenaka , ficou claro sim.

Somente o valor "orcid" é obrigatório e ele só pode ocorrer uma vez por autor (já que não faz sentido que um autor tenha mais de um ORCID), então não entendi porque a seguinte sugestão está errada:

Este elemento em `<contrib>` com o atributo `@contrib-id-type` e valor `orcid` é obrigatório para SciELO Brasil em pelo menos um dos autores e deve ocorrer uma vez para cada autor.
