### ISSUE TITLE
Classificar referências incompletas

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#64]
Referências do tipo ``journal`` deve apresentar, no mínimo, os elementos:

* **journal**: 
  * ``element-citation/person-group[person-group-type="author"]/name[1]/surname``
  * ``article-title``
  * ``source``
  * ``year``

Caso a referência não apresente esses elementos, esta deve ser classificada com o atributo ``element-citation/@specific-use="display-only"``.

**Comment by gustavofonseca** [comment]
Ver os tickets:
* https://github.com/scieloorg/balaio/issues/301
* https://github.com/scieloorg/balaio/issues/300
* https://github.com/scieloorg/balaio/issues/299
* https://github.com/scieloorg/balaio/issues/298
* https://github.com/scieloorg/balaio/issues/297

**Comment by gustavofonseca** [comment]
A validação foi implementada no packtools [https://github.com/scieloorg/packtools/commit/cd2dd0e3335af062147cbd9fda80d3bac0241d6e]

**Comment by leticiaquino** [comment]
Ticket inválido.
