### ISSUE TITLE
[est. 1 hora] Incoerência em obrigatoriedade de @id em <app> e <supplementary-material>

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#66]
Dizemos no SPS que @id é obrigatório tanto em ``<app>`` quanto em ``<supplementary-material>``, no entanto em casos como o ocorrido na ni v11n4 (arquivo: 1679-6225-ni-11-04-00747.xml), não faz sentido a inserção de @id nas duas tags já que no texto em ``<body>`` deverá ser feito uma única xref do tipo app OU supplementary-material.

``
<app-group>
...
<app>
				<label>Supplementary File 1: Script used for tree searches.</label>
				<supplementary-material id="suppl01" mimetype="application" mime-subtype="pdf" xlink:href="1679-6225-ni-11-04-00747-s1.pdf"/>
	</app>``

Recomendo retirar o atributo como obrigatório das duas tags, somente mencionar que caso exista xref correspondente deve-se realizar o link das informações obrigatoriamente.

Ver regra <app>: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset.html#app-group

Ver regra <supplementary-material>: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset.html#supplementary-material

**Comment by gustavofonseca** [comment]
Decidimos, em reunião, que a melhor abordagem será de corrigir os exemplos onde o elemento **app** não contém o atributo *@id*, inserindo-o-o.
