### ISSUE TITLE
[Revisão: parte 1] Melhoria em <issn>

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#681]
Em issn, acrescentar na nota, mais um parágrafo informando.
- Pode-se também consultar o site do ISSN (linkar com: https://portal.issn.org/)

Relação com #608

**Comment by gustavofonseca** [comment]
@RPostalli, pq isso? Ao meu ver o termo ISSN comunica muito mais dq sua versão por extenso, além do que o guia conta com um glossário, hyperlinks e tal.

**Comment by RPostalli** [comment]
@gustavofonseca a questão do link tem que ficar, o site do ISSN é o local da consulta oficial e um ótimo lugar de consulta
