### ISSUE TITLE
tag <named-content> não abarca todas as necessidades SciELO

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#69]
Acrescentar na tag named-content a informação em maiúsculo:

Aparece em:
addr-line E INSTITUTION

Acrescentar na tabela  o valor "email".

Inserir nota de que named-content do tipo email só pode aparecer na tag de institution do tipo "original" somente.

**Comment by gustavofonseca** [comment]
@RPostalli, de acordo com a JATS 1.0, o elemento *institution* não permite *named-content* como filho. Veja http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-6hk2.html

**Comment by gustavofonseca** [comment]
relacionado ao ticket https://github.com/scieloorg/packtools/issues/21

**Comment by RPostalli** [comment]
Retirar urgente de todos os exemplos de institution do tipo original a tag named-content content-type="email". Pensar em outra tag para identificação de email.

**Comment by leticiaquino** [comment]
@RPostalli e @gustavofonseca  informo que isso já havia sido corrigido no tagset, porém não havíamos disponibilizado no docs.
