### ISSUE TITLE
acréscimo de informação em subj-group

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#72]
O SPS diz: "...e para ahead-of-print deve ser adotado sempre a seção Articles."

Sugiro acrescentar: Artigos, e Artículos.

Não faz sentido manter uma título de seção (subject) de aop em inglês em um artigo em português ou espanhol.

PS: Sugiro também criar uma seção da tag "subject".

**Comment by gustavofonseca** [comment]
E faz sentido a existência de título de seção em artigos AOP? Até onde eu sei esses são disassociados de fascículos e sua estrutura.

**Comment by RPostalli** [comment]
Sim, faz já que <subject> é obrigatório, por isso adotamos o Articles.

**Comment by gustavofonseca** [comment]
Só pra eclarecer a questão da obrigatoriedade... de acordo com a JATS1.0 o elemento *subj-group* não é obrigatório. Essa obrigatoriedade foi estabelecida na SciELO PS por motivos de compatibilidade com a PMC3.0, que por sua vez não lida com arquivos AOP. Por isso minha pergunta: Faz sentido a existência de título de seção em artigos AOP?

**Comment by RPostalli** [comment]
Então Gustavo, nos já falamos isso em reunião. Quando uma AOP chega na SciELO, alguns constam com título de seção outros não, um lote de AOP pode ter vários tipos de seção diferentes ou nenhuma seção. Nesse sentido consideramos todos os AOP's com subject obrigatório e para questão de padronização e fluxo de trabalho sempre com a seção "Articles". A equipe quando migra o AOP para o fascículo só altera a seção (e possível article-type) para a seção mencionada no sumário, e ai neste caso esse ex AOP necessita obrigatoriamente de seção, já que ele agora deixa de ser um AOP.
Então respondendo sua pergunta, acredito que não, AOP não precisa de seção, mas já que este AOP será inevitavelmente um artigo de fascículo que sim, obrigatoriamente precisa de seção, vejo que a obrigatoriedade de um arquivo que é mutável (AOP) necessite de seção sim.
Obviamente que isso tudo que te falo remete a processo de trabalho, facilita o processo de trabalho da equipe de marcação. Mas fica a seu critério a análise da estrutura deste tipo de documento. De qualquer forma vindo ou não com seção no sumário do site scielo não ira aparecer seção, só no artigo AOP em si.
Em resumo, não acho que deveríamos alterar este "regra" no SPS.

**Comment by gustavofonseca** [comment]
Como o nome da seção deverá ser ajustado no momento em que o AOP entrar para um fascículo regular, o valor durante o seu período em AOP não faz diferença. Em reunião decidimos manter como está.
