### ISSUE TITLE
Erro em exemplo de <sig-block>

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#73]
Pesquisando na JATS notei que o exemplo 2 da tag ```<sig-block>``` esta incorreta. Deve-se retirar a informação de parágrafo ```<p>```, pelo que percebi dentro de ```<sig>``` não pode usar ```<p>```.

**Comment by leticiaquino** [comment]
@RPostalli e @gustavofonseca  informo que isso já havia sido corrigido no tagset, porém não havíamos disponibilizado no docs.
