### ISSUE TITLE
Arquivo exemplo

### ISSUE THREAD

**Issue by jobdiogenes** [scieloorg/scielo_publishing_schema#766]
Olá,

Estou estudando as definições Sielo PS, para desenvolver um conversor.
No entanto para compreender melhor o formato é importante que 
seja disponibilizado aqui no github e no "Read The Docs" do Sielo  para o Scielo PS, 
exemplos de arquivos de arqtigos completos (xml+arquivos).
Notadamente que contenham figuras (jpg,svg,tiff), tabelas simples e  mais complexas e fórmulas. 

No momento só achei exemplos para Jats no site do Jats (NHI), porém isso não é suficiente para atender o ScieloPS. 

Alguém poderia me fornecer algum? (ficarei  muito grato)

**Comment by gustavofonseca** [comment]
Olá @jobdiogenes, eu estou de acordo com a inclusão de artigos completos como exemplos no guia.

 Atualmente não temos uma maneira simples de navegar entre os arquivos XML e selecioná-los conforme sua solicitação. Vamos avaliar uma maneira boa de fazer isso.

**Comment by jobdiogenes** [comment]
Olá @gustavofonseca , obrigado pela atenção.

Um exemplo adequado seria de uma pasta compactada (zip) contento todos os arquivos que compõe um artigo completo, xml, figuras (svg, tiff, jpg, png, ...), tabelas, etc. ou seja o arquivo xml e todos arquivos externos anexos. E é claro seguindo a nomenclatura de arquivos desejada pela Scielo.

Por hora fico no aguardo  e trabalhando com o que esta disponível.

Obrigado.
