### ISSUE TITLE
Nomeação de arquivos e pastas incorreto no site

### ISSUE THREAD

**Issue by PriscilaLeme** [scieloorg/scielo_publishing_schema#771]
Boa tarde,

Os exemplos de nomeação de pastas e arquivos para envio à SciELO não estão de acordo no site.

![nomecao](https://user-images.githubusercontent.com/39777778/45307028-64be1980-b4f4-11e8-8315-a3098a5dd420.jpg)

Atenciosamente,
Priscila Requena

**Comment by gustavofonseca** [comment]
@PriscilaLeme, mas qual delas deve prevalecer?

**Comment by PriscilaLeme** [comment]
Boa tarde Gustavo, as regras precisam estar de acordo com o exemplo 

- Publicação Contínua com um volume ao ano forma correta: ISSN-acrônimo-volume-elocation / 0124-4567-scie-41-e0123
- Publicação Contínua com um volume e números (este a regra não está de acordo com o título) o correto seria: ISSN-acrônimo-volume-número-elocation / 0124-4567-scie-41-02-e234

Isso na nomeação de arquivos, note que na nomeação de pastas acontece a mesma coisa:

- Publicação Contínua com um volume e números forma correta: ISSN-acrônimo-volume-número-nº lote / 0124-4567-scie-41-02-01

Atenciosamente,
Priscila Requena

**Comment by gustavofonseca** [comment]
Perfeito, @PriscilaLeme. Grato por esclarecer.
