### ISSUE TITLE
Elemento para representar data de publicação no SciELO

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#772]
O problema que este issue visa resolver está descrito no ticket #565, e eu vou reescrevê-lo aqui a fim de facilitar o entendimento:

> Temos atualmente uma grande demanda para publicação contínua (PC). Muitas das revistas seguem à risca o teor de adiantar a publicação e, por exemplo, em 2017 já disponibilizam os artigos de 2018. 

Essa proposta de solução prevê a criação de um novo valor possível para o atributo `@pub-type="scielo"`, para representar a data em que o documento vai ao ar no SciELO.

Em resumo, `<pub-date pub-type="epub">` deve ser utilizado para representar somente a data de publicação enquanto `<pub-date pub-type="scielo">` apenas a data em que o documento vai ao ar no SciELO.

Esta proposta substitui a de #565.

**Comment by gustavofonseca** [comment]
Acabei de ver que existe discussão sobre isso no Texture. Vou investigar um pouco mais para amadurecer essa ideia antes de tomarmos uma decisão, ok?

**Comment by gustavofonseca** [comment]
@lpanebr, eu gostaria se possível da sua opinião sobre esse assunto. Está relacionado com a questão de `<pub-date pub-type="collection">` que está em discussão no contexto do Texture.

**Comment by lpanebr** [comment]
Confesso que pensar nos use-cases scielo é _mind-bending_ pois algumas revistas o usam como plataforma de publicação, enquanto outras apenas como arquivo de preservação/indexação... Alguém poderia argumentar que o schema adotado por scielo poderia/deveria ser bem diferente dependendo do seu posicionamento. Além disso existem a questão original em #565 de qual data usar no widget de "como citar" que dificulta um pouco sobre qual o propósito da criação das regras no scielo PS..

Mas enfim...

Dei uma olhada no PMC e a única regra publicada nas guidelines é de que 
> "Articles cannot have more than one <pub-date> with the same combination of @date-type and @publication-format." [1]
De modo que podem ser usados vários `pub-dates` desde que a chave única mista `@date-type @publication-format` não se repita.. Eu gosto dessa regra.

Ela permitiria usar o atributo `date-type="scielo"` que, penso, talvez seja mais apropriado para seu use-case, pois representaria a **data de publicação no scielo**. Assim poderiam preservar intactos os formatos e datas de publicação originais da revista (como tenta fazer o PMC).

Dessa forma ficariam com:
```xml
<!-- data de publicação do artigo no site da revista -->
<pub-date date-type="pub" publication-format="electronic">
	<day>17</day>
	<month>11</month>
	<year>2017</year>
</pub-date>

<!-- data de publicação do fascículo/edição artigo no site da revista -->
<pub-date date-type="collection" publication-format="electronic">				
	<year>2018</year>
</pub-date>

<!-- data de publicação do artigo no site scielo -->
<pub-date date-type="scielo" publication-format="electronic">
	<day>27</day>
	<month>11</month>
	<year>2017</year>
</pub-date>
```

Por outro lado, o JATS4R tem uma recomendação bem diferente, que anda está _pending_, de usar apenas 2 elementos `<pub-date>`, um para a data original da primeira publicação e outro para a data mais atual, enquanto qualquer outra data intermediária que o publisher queira guardar deve ser colocada em `/history/event/date`.[2]

Do modo com vejo a guideline PMC faz sentido para um portal de arquivamento e preservação, enquanto o JATS4R, está mais alinhado à ideia de preservar informações relevantes para o publisher.

[1] https://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/tags.html#el-pubdate
[2] https://jats4r.org/article-publication-and-history-dates

**Comment by robertatakenaka** [comment]
@gustavofonseca por favor, ver meu comentário no ticket #565

**Comment by gustavofonseca** [comment]
Rejeitado em favor do ticket #565
