### ISSUE TITLE
Suportar *visual abstracts*

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo_publishing_schema#773]
Exemplos: https://jasn.asnjournals.org/content/29/7/1825, https://www.sciencedirect.com/science/article/pii/S004040201101177X, https://www.sciencedirect.com/science/article/pii/S0169409X11001384, https://www.elsevier.com/authors/journal-authors/graphical-abstract

**Comment by RPostalli** [comment]
https://jats.nlm.nih.gov/publishing/tag-library/1.1/attribute/abstract-type.html
Usar: graphical | A pictorial representation such as a picture or a video
** Fazer teste em homolog

```xml
<abstract>
				<p>xxxxx</p>
			</abstract>
			<abstract abstract-type="graphical">
				<p>
				<fig id="vsf01">
                               <label>Visual Abstract</label>
                                 <caption>
                                     <title>Título<title>                                     
                                </caption>    
                                 <graphic xlink:href="1234-5678-zwy-12-04-0123-vs01.tif"/>                                 
                        </fig>
                        </p>
			</abstract>
```

**Comment by RPostalli** [comment]
Testado

![image](https://user-images.githubusercontent.com/6084959/52968185-32f68c00-338b-11e9-9774-5d7a102d783b.png)

**Comment by gustavofonseca** [comment]
> Testado
> 
> ![image](https://user-images.githubusercontent.com/6084959/52968185-32f68c00-338b-11e9-9774-5d7a102d783b.png)

Testado aonde?

**Comment by RPostalli** [comment]
@gustavofonseca testado em BR vintage pq temos homolog. Se tivesse homolog do new BR também daria para testar.

**Comment by gustavofonseca** [comment]
@RPostalli, qual o motivo de ser permitido o uso de xml:lang em visual abstract?

**Comment by RPostalli** [comment]
@gustavofonseca isso discutido em reunião 27/02/2019, consta na ata. Pode haver mais de um visual abstract, pode haver tradução de visual abstract assim como ocorre com o abstract normal.
abstract + trans abstract, logo deve haver a possibilidade de visual abstract idioma X + visual abstract idioma Y.

**Comment by gustavofonseca** [comment]
Na ata não consta nenhuma justificativa para o atributo, apenas a afirmativa "Acrescentar obrigatoriedade de @xml:lang em abstract do tipo graphical.", e eu não me recordo de termos apresentado essas justificativas durante a reunião. 

Bom, da mesma maneira que o visual abstract, o abstract tradicional também pode ser traduzido. Então por que eles necessitam regras distintas? Exceto pela referência a um ativo digital, eu não vejo diferenças significativas entre ambos os tipos.

**Comment by RPostalli** [comment]
Tudo o que está na ata foi decidido em reunião, vocês mesmo buscou na JATS a informação de que abstract suportava um atributo xml:lang. Inicialmente eu criei sem o xml:lang mas foi decidido que deveria ter o xml:lang para representar o visual abstract traduzido já que não existe a possibilidade de uns trans visual abstract.

Sugiro que realize a validação tal qual foi decidida em reunião, esta regra está sendo aplicada pela @robertatakenaka nas ferramentarias dela. Não temos tempo hábil para rediscutir o que já foi definido e retestar.

Nas próximas atas, farei um seção de motivos pelas escolhas e quem as decidiu para que não ocorram mais esses questionamentos.

Por favor siga com a inclusão do xml:lang.

**Comment by gustavofonseca** [comment]
Eu já conversei com a @robertatakenaka  e nós vamos reavaliar esta decisão. As eventuais traduções do visual abstract deverão utilizar o elemento *trans-abstract*, da mesma maneira que é feita por qualquer outro abstract.

**Comment by RPostalli** [comment]
Legal Gustavo. Vou reabrir o ticket do SPS então, e te marcar para vc corrigir conforme vc e a Roberta discutiram.

**Comment by RPostalli** [comment]
ticket feito.
