### ISSUE TITLE
Valores de <list>

### ISSUE THREAD

**Issue by natalieakemi** [scieloorg/scielo_publishing_schema#783]
Corrigir as informações abaixo:

**order** | Lista ordenada,   cujo prefixo é um número ou letra, dependendo do estilo utilizado.
**bullet** | Lista   desordenada, cujo prefixo utilizado é um ponto, barra ou outro símbolo.

O correto é:
**order** | Lista ordenada,   cujo prefixo é um número.
**bullet** | Lista   desordenada, cujo prefixo utilizado é um ponto.

Seria interessante inserir em **simple** os casos com símbolos não especificados acima. 
Exemplos:

Lista que numérica não começa inicia em 1:

![image](https://user-images.githubusercontent.com/19558447/52783653-bafe2e00-3039-11e9-9bcf-5f729bc98773.png)

![image](https://user-images.githubusercontent.com/19558447/52783669-c18ca580-3039-11e9-985b-1889b8231fbc.png)

Lista com outros símbolos:
Exemplo: 

`<`list list-type="simple"`>`

`<`list-item`>`

`<`label`>`*`<`/label`>`

`<`p`>`Dado uma imagem binária (img) onde os pixels objeto valem um e o fundo zero;`<`/p`>`

**Comment by RPostalli** [comment]
Alterado apenas o item order.
