### ISSUE TITLE
[DOIMultilingue] Documentar uso de DOI em sub-article

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scielo_publishing_schema#784]

**Comment by RPostalli** [comment]
@robertatakenaka este ticket já existe

https://github.com/scieloorg/scielo_publishing_schema/issues/175

**Comment by RPostalli** [comment]
Documentado em:
`<front-stub>`
`<article-id>`
`<article-id>` de Regras Específicas para SciELO Brasil

#175

**Comment by RPostalli** [comment]
@robertatakenaka 

XC - Cinthia fez o teste inserindo o doi em sub-article, o XC não acusa erro, mas também não informa a existência deste doi para tradução
XPM - Buga, não gera relatórios.
Site - Ignora a apresentação do DOI da tradução
Style Checker - Valida OK
Markup: Tem que adequar
