### ISSUE TITLE
Texto Padrão para License-p em SciELO Brasil

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#789]
obrigar o uso da seguinte frase para license

PT: Este é um artigo publicado em acesso aberto sob uma licença Creative Commons
EN: This is an article published in open access under a Creative Commons license
ES: Este es un artículo publicado en acceso abierto bajo una licencia Creative Commons

**Comment by RPostalli** [comment]
feito
https://github.com/scieloorg/scielo_publishing_schema/pull/790

**Comment by gustavofonseca** [comment]
@RPostalli, eu entendo as motivações mas não concordo com essa solução. Penso que devemos conversar mais antes de baixar essa regra que eu considero bizarra.

**Comment by RPostalli** [comment]
@gustavofonseca podemos rediscutir, mas a única solução para que a gente consiga validar o texto que é incluído nesta tag, é padronizando ela.

Desde que a inserção de licença passou a ser obrigatório no PDF ([Critérios SciELO Brasil 2017](http://www.scielo.br/avaliacao/Criterios_SciELO_Brasil_versao_revisada_atualizada_outubro_20171206.pdf)) informamos para as revistas que elas devem adotar qualquer diagramação nos PDFs, que podem ser: só logo, só texto, ou logo mais texto e onde elas preferirem, ao final do artigo, no início, cabeçalho, rodapé e etc. O texto incluído também é livre, apenas deve condizer com as diretrizes da licença adotada.

Posto isso, os textos inseridos nos XMLs, são em sua grande maioria criados pelas empresas contratadas por estas revistas, ou seja, não é necessariamente um texto que passou pela aprovação da revista (não temos como saber).

Mais detalhes do que motivou essa regra pode ser visto no meu último comentário deste [ticket](https://github.com/scieloorg/PC-Programs/issues/3039).

Entendo que pode ser arbitrário restringir a liberdade de criação dos textos possíveis de CC que possam ser inseridos em license-p, mas veja bem, este texto não é o espelho do original PDF, ele é representado apenas no insumo XML necessário para publicação em SciELO (demanda SciELO) e para muitas de nossas interoperações (PMC, SciELOCI, etc), logo temos grande responsabilidade em representar a licença (e o texto dela) de forma correta, mantendo o que a revista adota e está registrado em nossa title oficial.

Você mencionou na última reunião que podem haver partes do texto ou ativos digitais que estão licenciados de forma diferente do todo, mas quando uma publicação deste tipo ocorreu em SciELO? Até onde eu saiba, não ocorreu.

Tivemos artigos (no todo) publicados em fascículos fechados cuja os autores só autorizaram a publicação sobre uma licença diferente da adotada pela revista. Isso não é problema hoje e não será se essa nova regra for incluída.

Acredito que temos que tratar as excepcionalidades conforme elas aparecerem e mantermos um registro seguro do texto da licença no XML, onde teremos controle da qualidade do dado ali inserido.

- Porque considera a regra de padronização de texto de licença bizarro? 
- Qual seria sua sugestão de solução?
- Existe outra forma de garantir que o texto da licença represente de fato a licença descrita em license (e que já validada pelo XC consultando a title da revista)?

**Comment by RPostalli** [comment]
Criar alerta no XPM
Para PMC - criar texto padrão
