### ISSUE TITLE
Excluir exemplo 2 em <sig-block>

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#80]
Acredito que o segundo exemplo (após a exclusão de ```<p>```) não faz sentido mante-lo pois sem a inserção do ```<break/>``` a informação não ficará formatada em linhas separadas. É preferível mantermos uma única forma de inserir a tag e em minha opinião a primeira é a melhor.

**Comment by leticiaquino** [comment]
@RPostalli de acordo com a JATS o elemento ```<p>``` não pode constar em ```<sig-block>``` e em ```<sig>```.  No SPS 1.1 foi inserido erroneamente o elemento ```<p>```.

Veja o link sobre ```<sig-block>``` http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-msf0.html
 e ```<sig>``` http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-qxf0.html

Note também que se inserir o ```<break/>``` em ```<sig>``` a informação fica formatada de acordo com o esperado.
![exemplo](https://cloud.githubusercontent.com/assets/4397365/7299148/9404403e-e9aa-11e4-9d6a-e225c2f24a23.jpg)

![exemplo2](https://cloud.githubusercontent.com/assets/4397365/7299150/97cdfc28-e9aa-11e4-9452-9ba920eec236.jpg)

Caso no site não apareça dessa forma sugiro verificar com a Roberta.

**Comment by RPostalli** [comment]
Não é o problema de aparecer ou não no site, to partindo do princípio daquela discussão que tivemos sobre a tag email e named com o tipo email, Para que documentar duas formas de fazer a mesma coisa?

**Comment by leticiaquino** [comment]
@RPostalli não são duas formas de fazer a mesma coisa, mas sim uma correção.
Podemos inserir alguma nota informando o erro.

**Comment by RPostalli** [comment]
Acho mais fácil apagar um exemplo do que inserir uma nota. Mas fica a seu critério.

**Comment by javani** [comment]
@leticiaquino neste caso é melhor tirar o exemplo que está com problema. Pensando que a consulta será feita sempre na última versão, alguém pode passar batido pela nota e teremos mais problemas.
