### ISSUE TITLE
Taxonomia CRediT (Contributor Roles Taxonomy), proposta de CASRAI

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#821]
Verificar na JATS se a contribuição de cada autor tipo uso da Taxonomia CASRAI é identificada dentro das informações sobre autores
tipo authorgroup
https://casrai.org/credit/
ver BJCVS, MIOC, REF

MAKE CRediT MACHINE READABLE - CRediT tagged contributions should be coded in JATS xml v1.2
(Abel)

**Comment by RPostalli** [comment]
ESTUDO

*O que é CASRAI (Consortia Advancing Standards in Research Administration)*:  É uma organização de pesquisa que desenvolve taxonomias (vocabulário controlado) para facilitar a troca de informações entre as organizações de pesquisa.

*O que é CREDIT (Contributor Roles Taxonomy)*: É a Taxonomia da CASRAI para identificação de contribuição de autoria, dividida em 14 categorias.

*Para que serve o CREDIT*: Melhorar a acessibilidade e a visibilidade da gama de contribuições de autoria para os resultados da pesquisa publicada. (mais benefícios da adoção do método pode ser visto na lista (com bolinha azul) [aqui](https://casrai.org/credit/).

*[Critérios SciELO Brasil 2017](http://www.scielo.br/avaliacao/Criterios_SciELO_Brasil_versao_revisada_atualizada_outubro_20171206.pdf)*:  O item 5.2.22. Declaração da contribuição de autores e colaboradores, diz que: “A autoria de um documento atribui crédito e implica em responsabilidade pelo conteúdo publicado. Os periódicos SciELO devem instruir os autores a registrar no final dos artigos a contribuição de cada um dos autores e colaboradores, expressa nas instruções aos autores, com utilização de dois critérios mínimos de autoria:
a. Participar ativamente da discussão dos resultados;
b. Revisão e aprovação da versão final do trabalho. ”

*CREDIT: 14 Categorias*: (Descrição das categorias na tabela [aqui](https://casrai.org/credit/))

1. Conceptualization / Conceituação
2. Data curation / Curadoria de dados
3. Formal analysis / Análise formal
4. Aquisição de financiamento / Funding acquisition
5. Investigation /Investigação	
6. Methodology / Metodologia
7. Project administration / Administração de projetos
8. Resources / Recursos
9. Software / Programas
10. Supervision / Supervisão
11. Validation / Validação
12. Visualization / Visualização
13. Writing – original draft / Escrita - rascunho original
14. Writing – review & editing / Escrita - revisão e edição

Ver também: https://dictionary.casrai.org/Contributor_Roles

*5 recomendações para adoção da taxonomia CREDIT*:
1. Criar lista de todas as contribuições
2. Informar papéis múltiplos possíveis
3. Informar o grau de contribuição opcional (liderança, igualitária, suporte)
4. Responsabilidade compartilhada onde o autor correspondente assume responsabilidade de atribuição de funções
5. Codificar as contribuições em JATS xml v1.2

JATS 1.2d2
`<role>` https://jats.nlm.nih.gov/publishing/tag-library/1.2d2/element/role.html

CRediT Contributor Roles: The CRediT (Contributor Roles Taxonomy) Taxonomy (http://dictionary.casrai.org/Contributor_Roles) has been written to better define and communicate the different kinds of contributor roles in research outputs, and more and more publishers are defining the role of their contributors and collaborations. JATS therefore needs to be able to:

* Attach role information to a contributor (`<contrib>`);
* Support multiple roles for a single contributor;
* Support CRediT terms to describe this role, but also non-CRediT terms as well as free-text qualifiers to terms; and
* Be able to specify the term source (such as CRediT).

Role Attributes Record Taxonomy: If the content of the `<role>` element is a term from a controlled vocabulary (ontology, taxonomy, term-list, vocabulary, industry glossary, or other known source), the vocabulary attributes should be used to record that source. This source is typically a formal ontology or taxonomy such as CRediT. Four attributes can be used in this Tag Set to identify a term from such a controlled vocabulary:

- vocab
Name of the controlled or uncontrolled vocabulary, taxonomy, ontology, index, database, or similar that is the source of the term. For example, for a role, a value might be the CRediT taxonomy (“credit”) or MESH Headings (“mesh”). For an uncontrolled term, the value might be merely the word “uncontrolled”.

- vocab-identifier
Unique identifier of the vocabulary, such as (but not limited to) a URI or DOI. For example, for Dublin Core (DCC), the identifier may be http://dublincore.org/documents/2012/06/14/dces/. For CRediT, the identifier may be http://dictionary.casrai.org/Contributor_Roles.

- vocab-term
The content of the element is the display version of the vocabulary or taxonomic term. The @vocab-term attribute holds the canonical version of the same term, as it appears in the vocabulary. For example, if the attribute value was “Writer — original draft”, the element might contain the display text “Author”.
Character Caution: Characters such as Ndash are used in the cannonical CRediT names, and they may also be used in the content of the `<role>` element. But General Entities (such as –) should be used in the value of this attribute. Inside the @vocab-term value, use the Unicode character reference “—” for an Ndash.

- vocab-term-identifier
Unique identifier of the term within a specific vocabulary, such as (but not limited to) an item number, an accession number, a URI, a DOI, etc.

CRediT Best Practice: Although the @content-type attribute on the element `<role>` is designed to accept any text as its value, Best Practice is to tag the CRediT contributor role taxonomy terms when such use is possible. CRediT roles, might include, for example, “Conceptualization” (ideas; formulation or evolution of overarching research goals and aims), “Data curation” (management activities to annotate [produce metadata], scrub data and maintain research data [including software code, where it is necessary for interpreting the data itself] for initial use and later reuse), or “Writing – original draft” (creation and/or presentation of the published work, specifically writing the initial draft). Additional non-CRediT values such as “deep sea diver” may also be used. If a single contributor played more than one role in the creation of an article, the <role> element may be repeated, with a different @content-type attribute for each.

Example 2
As part of contributor information, with CRediT taxonomy shown:

```
<contrib-group>
<contrib>
<string-name><given-names>Barbara</given-names> <surname>Johnston</surname></string-name>
<role vocab="CRediT" 
vocab-identifier="http://dictionary.casrai.org/Contributor_Roles"
vocab-term="Conceptualization"
vocab-term-identifier="http://dictionary.casrai.org/Contributor_Roles/Conceptualization" 
degree-contribution="lead">study designer</role>
</contrib>
<contrib>
<string-name><given-names>Brooke</given-names> <surname>Jackson</surname></string-name>
<role vocab="CRediT" 
vocab-identifier="http://dictionary.casrai.org/Contributor_Roles"
vocab-term="Writing &#8212; Original Draft"
vocab-term-identifier="http://dictionary.casrai.org/Contributor_Roles/Writing_%E2%80%93_original_draft" 
degree-contribution="lead">writer</role>
</contrib>
</contrib-group>
```

Example 3
Special characters in CRediT attribute values need to be given as Unicode character references. In narrative text, Unicode character references, general entities, or characters may be used.

```
<contrib-group>
<contrib>
<string-name><given-names>Anne</given-names> <surname>Berns</surname></string-name>
<role vocab="CRediT" 
vocab-identifier="http://dictionary.casrai.org/Contributor_Roles"
vocab-term="Writing &#8212; Original Draft"
vocab-term-identifier="http://dictionary.casrai.org/Contributor_Roles/Writing_%E2%80%93_original_draft" 
degree-contribution="lead">Writing &ndash; Original Draft</role>
</contrib>
</contrib-group>
```

Ver também:
@vocab https://jats.nlm.nih.gov/publishing/tag-library/1.2d2/attribute/vocab.html
@vocab-identifier https://jats.nlm.nih.gov/publishing/tag-library/1.2d2/attribute/vocab-identifier.html

*Como o dado vem nos PDFs de revistas indexadas em SciELO hoje (mar. 2019).*

IMPORTANTE: Diagramação no PDF:
Nenhuma diretriz da CASRAI define diagramação específica para o PDF. Ou seja, os editores são livres para escolher em qual local do PDF é melhor.


REF - Revista Estudos Feministas
Ao final do documento.
http://www.scielo.br/pdf/ref/v27n1/1806-9584-ref-27-01-e50550.pdf

Marcado XML como: apêndice em back
```
<app-group>
			<app id="app1">
				<label>Notas de Autor</label>
				<p>Mônica Saldanha Dalcol</p>
				<p>Doutoranda em Estudos Literários pelo Programa de Pós-Graduação da Universidade Federal de Santa Maria.</p>
				<p>Filósofa e mestre em Filosofia pelo Programa de Pós-Graduação em Filosofia da Universidade Federal de Santa Maria</p>
				<p>Universidade Federal de Santa Maria, Departamento de Letras Vernáculas</p>
				<p>Av. Roraima, n. 1000 - Centro de Artes e Letras - Prédio 40A</p>
				<p>Campus Universitário UFSM - Bairro Camobi</p>
				<p>97105-900 - Santa Maria - RS</p>
				<p>(55) 3220 8087 e (55) 3220 8480</p>
				<p>dlvcal@gmail.com; www.ufsm.br/dlv</p>
				<p>Anselmo Peres Alós</p>
				<p>Doutor em Letras pela Universidade Federal do Rio Grande do Sul</p>
				<p>Pós-doutor pelo Programa de Pós-Graduação em Letras da Universidade Federal de Pernambuco como bolsista do Plano Nacional de Pós-Doutoramento (PNPD/CAPES), sob supervisão do Prof. Dr. Roland Walter. Atualmente, é professor Adjunto III no Departamento de Letras Vernáculas da UFSM e Docente Permanente do Programa de Pós-Graduação em Letras dessa mesma instituição.</p>
				<p>Universidade Federal de Santa Maria, Departamento de Letras Vernáculas</p>
				<p>Av. Roraima, n. 1000 - Centro de Artes e Letras - Prédio 40A</p>
				<p>Campus Universitário UFSM - Bairro Camobi</p>
				<p>97105-900 - Santa Maria - RS</p>
				<p>(55) 3220 8087 e (55) 3220 8480</p>
				<p>dlvcal@gmail.com; www.ufsm.br/dlv</p>
				<p>Como citar esse artigo de acordo com as normas da revista</p>
				<p>DALCOL, Mônica Saldanha; ALÓS, Anselmo Peres. “O <italic>mundo da vida</italic> e o <italic>mundo do texto</italic> em <italic>Úrsula</italic>, de Maria Firmina dos Reis”. <italic>Revista Estudos Feministas</italic>, Florianópolis, v. 27, n. 1, e50550, 2019.</p>
				<p>Contribuição de autoria</p>
				<p>Mônica Saldanha Dalcol - Concepção. Coleta de dados, Análise de dados, Elaboração do manuscrito, revisão e aprovação da versão final do trabalho</p>
				<p>Anselmo Peres Alós - Concepção e elaboração do manuscrito. Coleta de dados Participação ativa da discussão dos resultados; Revisão e aprovação da versão final do trabalho.</p>
				<p>Financiamento</p>
				<p>Mônica Saldanha Dalcol - Bolsa CAPES - 2016-2017</p>
				<p>Anselmo Peres Alós - Bolsa de Produtividade em pesquisa CNPQ</p>
				<p>Consentimento de uso de imagem</p>
				<p>Não se aplica.</p>
				<p>Aprovação de comitê de ética em pesquisa</p>
				<p>Não se aplica.</p>
				<p>Conflito de interesses</p>
				<p>Não houve conflitos.</p>
			</app>
		</app-group>
```

MIOC: Memórias do Instituto Oswaldo Cruz
Ao final do documento.
http://www.scielo.br/pdf/mioc/v114/1678-8060-mioc-114-e180432.pdf

Marcado XML como: author notes em front
```
<author-notes>
				<corresp id="c1">+ Corresponding author: <email>ematos@bio.fiocruz.br</email>
				</corresp>
				<fn fn-type="con" id="fn2">
					<p>EMS, TGN, ISA and RLSC - Contributed to the preparation and review of this
						paper; CLVF - responsible for the investigational products of the clinical
						trial and contributed to the preparation and review of this paper; RCB -
						responsible for the collection of blood samples and contributed to the
						preparation and review of this paper; PMNO - responsible for the adverse
						events notification and investigation and contributed to the preparation and
						review of this paper; MMS - responsible for the blood assays (ELISA and IgG)
						and contributed to the preparation and review of this paper; MCL -
						responsible for the development of the vaccine and contributed to the
						preparation and review of this paper; FLPR - contributed to the preparation
						and review of this paper; CMB - coordinator of the clinical trial; LABC -
						contributed to the preparation and review of this paper; MLSM - contributed
						to the preparation and review of this paper.</p>
				</fn>
			</author-notes>
```

RBCCV: Brazilian Journal of Cardiovascular Surgery
Ao final do documento.
http://www.scielo.br/pdf/rbccv/v34n1/0102-7638-rbccv-34-01-0033.pdf

Marcado XML como: table em body 
```
<table-wrap id="t4">
				<table frame="hsides" rules="groups">
					<colgroup>
						<col width="5%"/>
						<col width="95%"/>
					</colgroup>
					<thead>
						<tr>
							<th align="left" colspan="2">Authors' roles &amp; responsibilities</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td align="left" valign="top">WJ</td>
							<td align="left" valign="top">Analyzed the data, interpreted the results
								and writing; final approval of the version to be published</td>
						</tr>
						<tr>
							<td align="left" valign="top">BS</td>
							<td align="left" valign="top">Analyzed the data; interpreted the results
								and writing; final approval of the version to be published</td>
						</tr>
						<tr>
							<td align="left" valign="top">YW</td>
							<td align="left" valign="top">Participated in data collection and
								maintenance; final approval of the version to be published</td>
						</tr>
						<tr>
							<td align="left" valign="top">JX</td>
							<td align="left" valign="top">Analyzed the data; final approval of the
								version to be published</td>
						</tr>
						<tr>
							<td align="left" valign="top">ZL</td>
							<td align="left" valign="top">Participated in reviewing the manuscript;
								final approval of the version to be published</td>
						</tr>
						<tr>
							<td align="left" valign="top">XD</td>
							<td align="left" valign="top">Designed and directed the study; final
								approval of the version to be published</td>
						</tr>
						<tr>
							<td align="left" valign="top">JT</td>
							<td align="left" valign="top">Designed and directed the study; final
								approval of the version to be published</td>
						</tr>
					</tbody>
				</table>
			</table-wrap>
		</sec>
	</body>
```


*Como o dado vem nos PDFs de revistas indexadas em outras bases*:

eLife
https://elifesciences.org/articles/43114

F1000 Research
https://f1000research.com/articles/8-159/v1

BMJ Open Science
https://openscience.bmj.com/content/3/1/e000006

*Proposta para Documentação SPS*.

- SPS 1.9: Impossível documentar para a versão 1.9 uma vez que a versão da JATS que suporta este tagueamento ainda é uma versão Draft (JATS 1.2), não suportada pela SPS 1.9 (JATS 1.1)

- SPS 2.0: Documentar a possibilidade de uso do vocabulário controlado CrediT na versão SPS 2.0 que deverá manter o suporte a versão JATS 1. e acrescentar o suporte a versão JATS 1.2 (OBS: Ver lançamento da versão JATS 1.2 hoje na versão 1.2d2)

*Decisões para direção/coordenação (relação com a forma como vamos documentar)*
- Taxonomia CASRAI vai ser obrigatória?
- Outras taxonomias serão aceitas? Quais?
- Será documentado nos Critérios SciELO Brasil (assim como foi feito com ORCID)?

*Como documentar a tag role para SPS 2.0*
???????????????????????

**Comment by RPostalli** [comment]
JATS4R documentou recomendação para marcação de taxonomia CASRAI
https://jats4r.org/credit-taxonomy

**Comment by gustavofonseca** [comment]
> JATS4R documentou recomendação para marcação de taxonomia CASRAI
> https://jats4r.org/credit-taxonomy
> 
> Em: [jats-list] An outstanding question regarding the JATS4R CredIT recommendation

Eu voto por adotarmos a recomendação da JATS4R. Ela inclusive compreende as versões 1.1 e 1.2 da JATS, o que seria bastante conveniente para nós.

**Comment by gustavofonseca** [comment]
Produzi um rascunho da documentação narrativa para este tema em https://docs.google.com/document/d/1UwHgZc-99cnRlg5lfbLMPAbfWmDLmgMYY1fxgdh9ScI/edit?usp=sharing

@scieloorg/scielo-ps-developers poderiam verificar e passar suas impressões?

**Comment by RPostalli** [comment]
@gustavofonseca para mim está ótimo, só fiz um comentário no documento.

Sugiro que o texto passe por revisão da Solange.

**Comment by RPostalli** [comment]
@gustavofonseca me parece que os links  dos papéis `<role>` da [documentação do Credit no SPS](https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/master/narr/taxonomia-credit.html) não estão funcionando.

https://casrai.org/Contributor_Roles/Formal_analysis

![image](https://user-images.githubusercontent.com/6084959/72986171-5e1d0300-3dc6-11ea-9699-db5374efe1dd.png)

Pode verificar por favor?

**Comment by RPostalli** [comment]
@gustavofonseca como os links ainda estão quebrados e não temos retorno de quando vai ser corrigido (nem se vai ser mesmo) sugiro deixarmos o CREDIT como uma taxonomia sugerida assim como foi feito nos critérios. Para isso sugiro que na versão SPS 1.10:

1. Excluir a seção exclusiva de CRediT do sumário:
![image](https://user-images.githubusercontent.com/6084959/82226530-fd797f00-98fc-11ea-88a6-31db893019c9.png)

2. Inserir em role o link para a documentação geral do [CRediT](https://casrai.org/credit/). (Hoje o link redireciona para a seção CRediT do SPS) 
![image](https://user-images.githubusercontent.com/6084959/82226800-547f5400-98fd-11ea-9a9d-27ba6809ce52.png)

O que acha?

Referência:
Ver mais em [Critérios](https://www.scielo.br/avaliacao/20200500%20Criterios%20SciELO%20Brasil.pdf) item 5.2.6.4.1. Créditos aos autores

**Comment by gustavofonseca** [comment]
Oi @RPostalli. Eu considero complicado deixarmos algo como sugerido mas sem apresentarmos a estrutura de marcação sugerida. Chegarão estruturas das mais variadas. 

Eu prefiro simplesmente não mencionarmos o CRediT no SciELO PS até que se tenha de fato uma estrutura definida.

**Comment by RPostalli** [comment]
@gustavofonseca concordo plenamente com vc. E que mesmo sem a validação estrutural da taxonomia CrediT o SPS tb tem a função de estar alinhado ao Critérios. Mas neste caso em específico realmente não fará diferença para o SPS já que de fato não teremos como garantir o dado.

Então podemos só apagar a seção CrediT e corrigir a `<role>` excluindo a informação CrediT, certo?  Eu posso seguir com essa correção?

**Comment by gustavofonseca** [comment]
@scieloorg/scielo-ps-developers, estão de acordo?

**Comment by RPostalli** [comment]
Vamos entrar em contato com JATS4R e perguntar sobre essa documentação que continua ativa lá. (Renata)
Prazo 1 semana.

**Comment by RPostalli** [comment]
Os links existem em outras URLs.

URL Contributor Roles: https://casrai.org/term/contributor-roles/

Contributor Roles/Conceptualization
https://casrai.org/term/contributor-roles-conceptualization/

Contributor Roles/Data curation
https://casrai.org/term/contributor-roles-data-curation/

Contributor Roles/Formal analysis
https://casrai.org/term/contributor-roles-formal-analysis/

Contributor Roles/Funding acquisition
https://casrai.org/term/contributor-roles-funding-acquisition/

Contributor Roles/Investigation
https://casrai.org/term/contributor-roles-investigation/

Contributor Roles/Methodology
https://casrai.org/term/contributor-roles-methodology/

Contributor Roles/Project administration
https://casrai.org/term/contributor-roles-project-administration/

Contributor Roles/Resources
https://casrai.org/term/contributor-roles-resources/

Contributor Roles/Software
https://casrai.org/term/contributor-roles-software/

Contributor Roles/Supervision
https://casrai.org/term/contributor-roles-supervision/

Contributor Roles/Validation
https://casrai.org/term/contributor-roles-validation/

Contributor Roles/Visualization
https://web.archive.org/web/20180313224017/http://dictionary.casrai.org/Contributor_Roles/Visualization

Contributor Roles/Writing – original draft
https://casrai.org/term/contributor-roles-writing-original-draft/

Contributor Roles/Writing – review & editing
https://casrai.org/term/contributor-roles-writing-review-editing/


@gustavofonseca @robertatakenaka @cinthia-vieira Mantemos a documentação só trocando os links?

**Comment by cinthia-vieira** [comment]
@RPostalli por mim, OK.

**Comment by gustavofonseca** [comment]
> @gustavofonseca @robertatakenaka @cinthia-vieira Mantemos a documentação só trocando os links?

Acho que faz sentido =]
