### ISSUE TITLE
Definir a estrutrura de documento do tipo data-article

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#834]
Definir a estrutrura de documento do tipo data-article

Seguem os elementos obrigatórios e os opcionais em um data article:

Elementos obrigatórios:

- DOI
- Título diferente da seção. Ou seja, ter títulos dos documentos com nomes significativos. Evitar que haja vários documentos diferentes como o mesmo título da seção, por exemplo, não ter vários documentos com o título: Editorial, não sendo possível identificar o seu conteúdo pelo título.
- Autores
- Afiliação
- Resumo
- Palavras-chave
- Seções
- Citações
- Referências
- Licença CC
- Histórico

------
O artigo de dados é um tipo de publicação cujo principal objetivo é descrever uma coleção/conjunto de dados de pesquisa. Esse tipo de publicação não apenas descreve os metadados dos dados de pesquisa também relata as etapas metodológicas de obtenção dos dados (descrição minuciosa dos dados e dos ativos que compõem o conjunto de dados).

Esses artigos são, em alguns aspectos, semelhantes a um artigo científico convencional, podendo incluir tópicos como: resumo, introdução e contextualização, procedimentos metodológicos e conflito de interesses, agradecimentos e referências. Além desses tópicos comuns aos artigos científicos tradicionais, os artigos de dados apresentam seções específicas deste formato de publicação. Normalmente, para a publicação dos artigos de dados, os periódicos solicitam que seja incluída na seção que detalha a descrição dos dados a composição, o formato, a localização e as formas de acesso e manipulação dos dados, sistemas e softwares para processamento, entre outros.

Exemplos:

https://bdj.pensoft.net/article/1114/
[data-04-00130.pdf](https://github.com/scieloorg/scielo_publishing_schema/files/3799023/data-04-00130.pdf)
[bmdj.01301_Mice_Myocardial_Infarction.pdf](https://github.com/scieloorg/scielo_publishing_schema/files/3799024/bmdj.01301_Mice_Myocardial_Infarction.pdf)

**Comment by gustavofonseca** [comment]
> Descrever melhor
> 
> Seguem os elementos obrigatórios e os opcionais em um data article:
> 
> Elementos obrigatórios:
> 
> DOI

Para a coleção Brasil esta obrigatoriedade já vale. Para a Rede ela não pode existir.

> Título diferente da seção

Não entendi. Poderia elaborar?

> Autores
> Afiliação
> Resumo
> Palavras-chave
> Seções
> Citações
> Referências
> Licença CC
> 
> Elementos opcionais:
> 
> Histórico

Eu gostaria de entender qual conceito de _data article_ que nós estamos utilizando. Caso sejam artigos revisados por pares, como na Elsevier, penso que o histórico não deveria ser opcional.

> Data articles are brief, peer-reviewed publications about research data. Sharing data makes it accessible and enables others to gain new insights and make interpretations for their own research. Thanks to a detailed dataset description, the data published in data articles can be reused, reanalyzed and reproduced by others.

https://www.elsevier.com/authors/author-resources/research-data/data-articles

**Comment by francine-curivil** [comment]
@gustavofonseca eu e a @jenniferamato conversamos com a Solange na semana passada e ela disse para documentarmos que o data-article deve ter todos os elementos mencionados (tanto obrigatórios quanto opcionais), mas nos validadores a ausência de histórico deve apresentar somente erro (não barrar a publicação do artigo).

Também entendemos que um data-article deve ser revisado por pares.

**Comment by robertatakenaka** [comment]
Deve ser documentado na seção de "Tipos Especiais de Documentos"

**Comment by robertatakenaka** [comment]
@alexxxmendonca você poderia dar alguns exemplos reais de data article?

**Comment by alexxxmendonca** [comment]
acho que a @RPostalli ou alguém da produção pode ajudar melhor com isso, não?

**Comment by jenniferamato** [comment]
@robertatakenaka e @alexxxmendonca até o momento não temos o conhecimento de nenhum data article em SciELO.

**Comment by francine-curivil** [comment]
Segue sugestão de texto para documentação: https://docs.google.com/document/d/17ncEyyetx6HBtX4C7nOOG7jV-CjWh4pLrc7wCxSIQ0w/edit.

Vocês acham que seria interessante colocar o link para um data-article publicado por algum periódico (mesmo que não faça parte da Coleção SciELO)?
