### ISSUE TITLE
Inserir link de consulta em <institution>

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#84]
Inserir na tag ```<intitution>``` na tabela no campo:

normalized	Nome da instituição na forma normalizada pela SciELO. ***Consulte dados normalizados no link: http://wayta.scielo.org/*** 

Inserir nota:

No caso da busca de alguma instituição que ainda não consta na lista, entre em contato com a SciELO no email: scielo@scielo.org e informe a instituição para análise e posterior alimentação da lista para consulta.

**Comment by javani** [comment]
@RPostalli o wayta está apresentando algumas inconsistências nos resultados. Vou verificar com o Fábio como resolver isso. Por outro lado, solicitei ao pessoal de conversão que vejam uma forma de apresentação do dado para o usuário final (autor/editor). Acredito que este deverá ser o link a ser incluído. Vamos aguardar um pouco
