### ISSUE TITLE
Inserir Guias direto no Git

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#843]
Inserir Guias direto no Git 

https://www.scielo.org/pt/sobre-o-scielo/scielo/procedimentos-de-publicacao-no-scielo/
https://www.scielo.org/pt/sobre-o-scielo/scielo/

**Comment by gustavofonseca** [comment]
Este ticket não está relacionado com o desenvolvimento do SciELO PS. Caso ainda seja relevante, podemos discutir e encontrar o melhor local para registro.

**Comment by RPostalli** [comment]
@gustavofonseca apenas para recorda-lo que este ticket foi aberto quando percebemos que os links dos guias em scielo.org estavam mudando constantemente as url's e estavam quebrando os links do SPS e eu estava corrigindo manualmente um a um. Você havia informado que esse problema poderia ser terminado "inserindo os guias direto no SPS".
