### ISSUE TITLE
Corrigir valor de @pub-id-type

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/scielo_publishing_schema#868]
O valor de @pub-id-type em pub-id para o PMC ID está incorreto.
Na tabela de valores possíveis está: 
pcmid 

![image](https://user-images.githubusercontent.com/16937218/67204128-2aa39480-f3e3-11e9-8d22-7a3310f3fc0a.png)

O correto seria:
pmcid

https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-pub-id.html

A correção deve ser realizada também no StyleChecker:

![image](https://user-images.githubusercontent.com/16937218/67204176-4f980780-f3e3-11e9-9e20-71ee7cdfd72e.png)

**Comment by gustavofonseca** [comment]
A mensagem exibida pelo _stylechecker_ indica que o XML em questão é inválido em relação à DTD, pois é ela que controla os valores possíveis para o atributo `pub-id/@pub-id-type`. Portanto, não há o que ser corrigido no _packtools_.
