### ISSUE TITLE
Considerar uso da tag <events> para histórico 

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/scielo_publishing_schema#873]
Atualmente, a tag utilizada para descrever o ciclo de vida dos artigos é `<history>`. Entretanto, a tag não suporta (sem gambiarras) o versionamento das revisões.

No futuro, será mais comum os periódicos informarem todas as datas de recebimento de revisão dos artigos (algumas já o fazem, como a [Cerâmica](http://www.scielo.br/pdf/ce/v65n375/1678-4553-ce-65-375-443.pdf)) e, embora seja deduzível pela ordem das datas qual a ordem das revisões, creio que seja interessante dar mais informações sobre.

Uma vez que a tag [`<events>`](https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/counts.html) permite a descrição da história do documento como um todo, sugiro estudarmos a possibilidade do uso da mesma.

*** lembrando que esta tag é da JATS 1.2

**Comment by gustavofonseca** [comment]
A JATS4R apresenta uma recomendação, ainda pendente de aprovação, sobre histórico: https://jats4r.org/article-publication-and-history-dates

**Comment by gustavofonseca** [comment]
O ticket #833 inclui o uso do elemento `<events>` nos mesmos termos descritos neste ticket. Estou marcando este como _duplicado_ e vamos seguir com o outro.
