### ISSUE TITLE
Correção de Glossário SPS

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/scielo_publishing_schema#879]
Em: https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/glossary.html

Trocar

De: SciELO Publishing Schema
Composta pela especificação: NISO JATS Journal Publishing, versão 1.1. mais o Estilo SciELO PS com regras especializadas da Metodologia SciELO.

Para: SciELO Publishing Schema
Composta pela especificação: NISO JATS Journal Publishing, versão 1.1 e 1.2 mais o Estilo SciELO PS com regras especializadas da Metodologia SciELO.

Acrescentar Itens:

JATS4R: Descrição??????
CREDIT: Descrição??????
CASRAI: Descrição??????
ORCID: Descrição??????
Taxonomia: Descrição??????
Highlights: Descrição??????

**Comment by RPostalli** [comment]
@jenniferamato @gustavofonseca @robertatakenaka Criei os textos para os termos faltantes, podem verificar por favor. https://docs.google.com/document/d/1ImjUDzxP8eiszWkbTdaL_l0rjQiACWzqhtG2Gdcf9sM/edit

**Comment by gustavofonseca** [comment]
> @jenniferamato @gustavofonseca @robertatakenaka Criei os textos para os termos faltantes, podem verificar por favor. https://docs.google.com/document/d/1ImjUDzxP8eiszWkbTdaL_l0rjQiACWzqhtG2Gdcf9sM/edit

Excelente, @RPostalli. Deixei comentários lá.
