### ISSUE TITLE
Sugestão para documentação de Video Abstract

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/scielo_publishing_schema#899]
Existem alguns editores perguntando sobre a publicação de resumos em vídeo. Em testes realizados no site de QA, conseguimos resultados positivos utilizando o seguinte código XML. Lembrando que o _upload_ de arquivos de vídeo como `"graphical"` abstract é suportada pela [JATS](https://jats.nlm.nih.gov/publishing/tag-library/1.1/attribute/abstract-type.html)

```xml 
<abstract abstract-type="graphical">
 <title>Video Abstract</title>
  <p>
   <media mimetype="video" mime-subtype="mp4" xlink:href="1982-5765-aval-25-01-5-va.mp4"/>
  </p>
</abstract>
```

_Screenshot_ do código no site de QA:
![image](https://user-images.githubusercontent.com/27728729/82087201-fe749b80-96c5-11ea-832d-49f78a7e2427.png)

Caso seja necessária a criação de um _mockup_ para verificação do artigo no site de QA, por favor me avisem para que eu possa providenciar, pois os testes foram realizados com um artigo já corrigido de periódico em processo de QA.

**Comment by gustavofonseca** [comment]
Muito bom @cinthia-vieira. Essa estrutura assume que o vídeo (arquivo .mp4) faz parte do pacote SciELO PS. No caso do vídeo estar disponibilizado em uma plataforma externa, como o YouTube, a mesma estrutura de marcação seria mantida mas trocando a URI para uma URL absoluta?

**Comment by RPostalli** [comment]
@gustavofonseca bem lembrado. Quando é link externo a gente usa o [<ext-link>](https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-ext-link.html)

Ai ficaria:

```
<abstract abstract-type="graphical">
 <title>Video Abstract</title>
  <p>
   <ext-link ext-link-type="uri" xlink:href="https://www.youtube.com">https://www.youtube.com</ext-link>
  </p>
</abstract>
```

Podemos documentar os dois tipos.

**Comment by gustavofonseca** [comment]
> @gustavofonseca bem lembrado. Quando é link externo a gente usa o [ext-link](https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-ext-link.html)

Entendi. Olhando a documentação da JATS eu fiquei em dúvida se não seria o caso de utilizarmos o próprio elemento _media_. Vocês chegaram a avaliar isso?

**Comment by cinthia-vieira** [comment]
@RPostalli @gustavofonseca Acho que o único "contra" de se colocar um vídeo hospedado em plataforma externa seria que, em termos de visualização, o resumo seria apenas um link e não um player de vídeo como no arquivo mp4 hospedado em SciELO.

Com relação ao elemento `<media>` para links externos, não chegamos a avaliar, não rs. Também não faço ideia de como o site se comportaria com esse tipo de uso da tag `<media>`, creio que nunca usamos ela com links externos.

Acham necessário rodar um teste sob essas condições pra ver como fica a visualização?

**Comment by RPostalli** [comment]
@gustavofonseca realmente é possível sim usar o link em media segundo a JATS, mas como toda a nossa documentação (SPS) indica que para uso de link externo deve ser usado o <ext-link> acho que fica mais coerente com o resto da documentação. 

@cinthia-vieira não vejo um problema o resumo ficar apenas com um link quando for externo. Apenas isso deve ser considerado no site novo, nao sei como os resumos com imagem/video estão sendo considerados no sumário eletrônico.

O que acham? Como devemos documentar?

**Comment by gustavofonseca** [comment]
> @RPostalli @gustavofonseca Acho que o único "contra" de se colocar um vídeo hospedado em plataforma externa seria que, em termos de visualização, o resumo seria apenas um link e não um player de vídeo como no arquivo mp4 hospedado em SciELO.

Não necessariamente. A gente poderia estudar a viabilidade de embutir o player do Youtube quando identificarmos que se trata de um vídeo publicado lá.

> Com relação ao elemento <media> para links externos, não chegamos a avaliar, não rs. Também não faço ideia de como o site se comportaria com esse tipo de uso da tag <media>, creio que nunca usamos ela com links externos.

> Acham necessário rodar um teste sob essas condições pra ver como fica a visualização?

Penso que seria interessante. Algo me diz que o elemento _media_ é mais adequado do que o _ext-link_ para este caso de uso.

**Comment by RPostalli** [comment]
@gustavofonseca OK faremos com o media então. @cinthia-vieira pode por favor criar um modelo com media +link externo por favor e colocar aqui (teste em QA antes por favor, nos mostre como fica hoje)? Assim documentamos os dois tipos:

1. Media + video no pacote
2. Media + link externo

**Comment by gustavofonseca** [comment]
Percebo nos textos de vocês que o termo _link_ é usado como sinônimo de _URL_, o que não é muito preciso. Entendo _link_ como _hyperlink_, ou seja, aquele texto sensibilizado que, quando clicado, direciona o leitor para um outro documento. O elemento _ext-link_ então seria um _hyperlink_ para um recurso externo que, de alguma maneira, enriquece o primeiro.

Já no elemento _media_ eu não estou criando um _hyperlink_ entre documentos, mas estou dizendo que o documento possui um arquivo de mídia que é parte dele. 

Não sei se estou forçando a interpretação do uso destes elementos, mas vem daí a pulga atrás da minha orelha rs. O que vocês pensam sobre isso?

**Comment by cinthia-vieira** [comment]
Concordo com o uso do _media_ mesmo que pra vídeos de fontes externas, acho que realmente faz mais sentido que _ext-link_, uma vez que dado não é só uma ligação externa, mas um arquivo de mídia tal qual o outro hospedado em SciELO.

Eu só não lembrava que dava pra fazer isso com _media_ no SPS, por isso não sugeri rs

**Comment by cinthia-vieira** [comment]
Pessoal, testei a seguinte estrutura XML:

```xml
<abstract abstract-type="graphical">
  <title>Video Abstract</title>
  <p>
    <media mimetype="video" mime-subtype="mp4" xlink:href="https://www.youtube.com/watch?v=5qap5aO4i9A"/>
  </p>
</abstract>
```

O resultado foi o seguinte:
![image](https://user-images.githubusercontent.com/27728729/82327870-6f150400-99b5-11ea-9887-ca1ece43bd05.png).

Creio que possa ser por conta do valor de `@mime-subtype`, já que o xlink não é exatamente um vídeo mp4, mas uma URL.

**Comment by RPostalli** [comment]
@cinthia-vieira @gustavofonseca Quando de tratar de uma URL não temos como saber específicamente qual é o formato do video (Ter que ir na fonte para buscar informação não é produtivo). Acho que podemos seguir sem o @mime-subtype, esse [atributo é opcional](https://jats.nlm.nih.gov/publishing/tag-library/1.1/attribute/mime-subtype.html). O que acham?

Ai ficaria:

```
<abstract abstract-type="graphical">
  <title>Video Abstract</title>
  <p>
    <media mimetype="video" xlink:href="https://www.youtube.com/watch?v=5qap5aO4i9A"/>
  </p>
</abstract>
```

**Comment by cinthia-vieira** [comment]
@RPostalli `@mime-subtype` é [obrigatório](https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-media.html) no SPS :(

Vou subir um teste sem o `@mime-subtype` pra ver como a plataforma se comporta, se funcionar, podemos ver de re-documentar a tag `<media>`, talvez?

**Comment by gustavofonseca** [comment]
> @cinthia-vieira @gustavofonseca Quando de tratar de uma URL não temos como saber específicamente qual é o formato do video (Ter que ir na fonte para buscar informação não é produtivo). Acho que podemos seguir sem o @mime-subtype, esse [atributo é opcional](https://jats.nlm.nih.gov/publishing/tag-library/1.1/attribute/mime-subtype.html). O que acham?
> 
> Ai ficaria:
> 
> ```
> <abstract abstract-type="graphical">
>   <title>Video Abstract</title>
>   <p>
>     <media mimetype="video" xlink:href="https://www.youtube.com/watch?v=5qap5aO4i9A"/>
>   </p>
> </abstract>
> ```

Estou de acordo. Podemos adicionar no guia instruções ou exemplos específicos para esses grandes serviços de difusão de vídeo, como YouTube e Vímeo.

**Comment by RPostalli** [comment]
@cinthia-vieira a gente muda a obrigatoriedade quando se tratar se uso de media com URL. Para media com video mantem-se o atributo já que nossa plataforma exige ser mp4.

@gustavofonseca boa, podemos sim documentar desta forma.

**Comment by cinthia-vieira** [comment]
Pessoal, fiz o teste retirando o `@mime-subtype` e é assim que a plataforma mostra o resumo:

![image](https://user-images.githubusercontent.com/27728729/82341257-8f00f380-99c6-11ea-874b-d3fb0702f1e8.png)


Só para registro, nos links de "Resumo em [idioma]" apenas resumos em texto são mostrados.

**Comment by RPostalli** [comment]
Reunião 04/06/2020
@robertatakenaka verificar ajustes na tag de` <media>`
