### ISSUE TITLE
Exemplo incompleto de ref do tipo "webpage"

### ISSUE THREAD

**Issue by suelylc** [scieloorg/scielo_publishing_schema#94]
O dado marcado com ```<year>``` corresponde à data do documento que está disponível no site. Mas no exemplo do guia o elemento ```<year>``` está marcando a mesma informação de ```<date-in-citation>```.Está faltando a informação de ano em ```<mixed-citation>```.

Abaixo um exemplo completo

Fugh-Berman A. PharmedOUT [Internet]. Washington: Georgetown University, Department of Physiology and Biophysics; c2006 [cited 2007 Mar 23]. Available from: http://www.pharmedout.org/. 

```<element-citation publication-type="webpage">
  <name>
    <surname>Fugh-Berman</surname>
    <given-names>A</given-names>
  </name>
  <source>PharmedOUT [Internet]</source>
  <publisher-loc>Washington</publisher-loc>
  <publisher-name>Georgetown University, Department of Physiology and Biophysics</publisher-name>
  <year>c2006</year>
  <date-in-citation>cited 2007 Mar 23</date-in-citation>
  <comment>Available from: <ext-link ext-link-type="uri" xlink:href="http://www.pharmedout.org">http://www.pharmedout.org</ext-link></comment>
</element-citation> ```

Estrutura consultada em 
http://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/citations/v3/websites.html#d3e60698

**Comment by leticiaquino** [comment]
@suelylc na verdade Suely, foi inserido uma informação a mais: ```<year>```. Vamos retirar essa informação.
Note que pode existir webpage sem data: http://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/citations/v3/websites.html#d3e61420


Vamos corrigir isso.

**Comment by suelylc** [comment]
Sim, Acho que seria melhor manter os dois exemplos um sem dada e outro com. Embora, em grande parte dos arquivos esteja sem data ela é requerida na elaboração desse tipo de referência e o relatório de teste está considerando isso indicando "ERRO" quanda falta ```<year```.

**Comment by leticiaquino** [comment]
@suelylc você pode me dar um exemplo desse erro?
De acordo com as regras de validação do converter, em webpage é verificado se existe apenas o date-in-citation e o ext-link.

**Comment by suelylc** [comment]
Inseri exemplo ao final do doc https://docs.google.com/document/d/1rZ4j56RKcj0wUV_tKMKYI76t1HUGTyBqzwpv8OEKSOw/edit#heading=h.8ddbbkya45g0

Este relatório tem vários erros sobre ausência de year
http://homolog.xml.scielo.br/reports/rcefac/v17n2/xml_converter.html
